### ISSUE TITLE
[bug]: chan_pjsip_hangup executed twice, causing a crash

### ISSUE THREAD

**Issue by Tinet-mucw** [asterisk/asterisk#1003]
### Severity

Trivial

### Versions

18.10

### Components/Modules

main

### Operating Environment

centos8

### Frequency of Occurrence

Occasional

### Issue Description

```c
static int hangup(void *data)
{
	struct hangup_data *h_data = data;
	struct ast_channel *ast = h_data->chan;
	struct ast_sip_channel_pvt *channel = ast_channel_tech_pvt(ast);
	SCOPE_ENTER(1, "%s\n", ast_channel_name(ast));

	/*
	 * Before cleaning we have to ensure that channel or its session is not NULL
	 * we have seen rare case when taskprocessor calls hangup but channel is NULL
	 * due to SIP session timeout and answer happening at the same time
	 */
	if (channel) {
```
	
	From the above code, we can see:
	we have seen rare case duing to SIP session timeout and answer happening at the same time.
	
	I currently don't know the race condition in my situation. The sip destination of the App Dial is a softphone implemented by WebRTC. After 40 seconds of the call, a sip end request was received from WebRTC. The system crashed after executing the hangup handler of the main channel.
	
	I don't think the modification in hangup can completely resolve the race condition.  a flag or member variable should be set to indicate that func hangup has already been executed, the hangup conditon should be placed before putting hangup into the serializer

[core-asterisk-2024-11-12T02-58-43Z-brief.txt](https://github.com/user-attachments/files/17898238/core-asterisk-2024-11-12T02-58-43Z-brief.txt)
[core-asterisk-2024-11-12T02-58-43Z-full.txt](https://github.com/user-attachments/files/17898239/core-asterisk-2024-11-12T02-58-43Z-full.txt)
[core-asterisk-2024-11-12T02-58-43Z-info.txt](https://github.com/user-attachments/files/17898240/core-asterisk-2024-11-12T02-58-43Z-info.txt)
[core-asterisk-2024-11-12T02-58-43Z-locks.txt](https://github.com/user-attachments/files/17898241/core-asterisk-2024-11-12T02-58-43Z-locks.txt)
[core-asterisk-2024-11-12T02-58-43Z-thread1.txt](https://github.com/user-attachments/files/17898242/core-asterisk-2024-11-12T02-58-43Z-thread1.txt)

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Is this really on Asterisk 18.10? Has it been experienced on a currently supported recent version?

**Comment by Tinet-mucw** [comment]
We have already planned to upgrade to version 22.0.0 and are gradually replacing it. The replacement will not be completed until mid-next year.

In previous years, we encountered this issue about once a year; this year we've already faced it approximately five times.

**Comment by jcolp** [comment]
18.10.0 is approaching 3 years old, and I have a memory of things in this area being investigated in the past few years. I think it had something to do with underlying reference counting, though I could be mistaken. I would really like to see if it can be reproduced on a modern version.

**Comment by Tinet-mucw** [comment]
[Nov 27 01:55:12] VERBOSE[213] res_pjsip_logger.c: <--- Received SIP request (924 bytes) from UDP:123.127.194.4:32766 --->
INVITE sip:0150****1701@58.57.109.227 SIP/2.0^M
Via: SIP/2.0/UDP 123.127.194.4:32766;branch=z9hG4bK73be2e080a52466a^M
From: <sip:05337430895@123.127.194.4>;tag=0034dd982a66d30a^M
To: <sip:0150****1701@58.57.109.227>^M
Call-ID: 3ee7332363616c6c1703a330@123.127.194.4^M
CSeq: 21703 INVITE^M
Contact: <sip:05337430895@123.127.194.4:32766>^M
Allow: INVITE, ACK, CANCEL, BYE, OPTIONS, INFO, UPDATE, PRACK^M
Supported: linknat^M
Original-Info: SBIgSkgapzNIEiBKVhwAdVYECBdBAAlSUhYAFwJVVAZXRRZDUggVFwdVXQWW^M
Max-Forwards: 70^M
User-Agent: VOS3000 V2.1.7.03^M
Original-ID: ODM5NDhiZWFmZWJjZThiMjVjNzA4ODBiN2EzMGYwMTc.^M
Content-Type: application/sdp^M
Content-Length: 271^M
^M

v=0^M
o=- 31743 31743 IN IP4 123.127.194.4^M
s=VOS3000^M
c=IN IP4 123.127.194.4^M
t=0 0^M
m=audio 16130 RTP/AVP 18 8 0 101^M
a=rtpmap:18 G729/8000^M
a=fmtp:18 annexb=no^M
a=rtpmap:8 PCMA/8000^M
a=rtpmap:0 PCMU/8000^M
a=rtpmap:101 telephone-event/8000^M
a=fmtp:101 0-15^M
a=sendrecv^M

[Nov 27 01:55:12] DEBUG[213] config.c: extract uint from [1] in [0, 4294967295] gives [1](0)
[Nov 27 01:55:12] DEBUG[213] config.c: extract uint from [0] in [0, 65535] gives [0](0)
[Nov 27 01:55:12] DEBUG[213] config.c: extract int from [100] in [1, 2147483647] gives [100](0)
[Nov 27 01:55:12] DEBUG[213] config.c: extract int from [1] in [-2147483648, 2147483647] gives [1](0)
[Nov 27 01:55:12] DEBUG[213] config.c: extract uint from [0] in [0, 4294967295] gives [0](0)
[Nov 27 01:55:12] DEBUG[213] config.c: extract int from [30] in [-2147483648, 2147483647] gives [30](0)
[Nov 27 01:55:12] DEBUG[213] config.c: extract int from [5] in [-2147483648, 2147483647] gives [5](0)
[Nov 27 01:55:12] DEBUG[213] config.c: extract int from [100] in [1, 2147483647] gives [100](0)
[Nov 27 01:55:12] DEBUG[213] config.c: extract uint from [0] in [0, 4294967295] gives [0](0)
[Nov 27 01:55:12] DEBUG[213] acl.c: 58.57.109.227:0/255.255.255.255:0 sense 0 appended to ACL
[Nov 27 01:55:12] DEBUG[213] config.c: extract int from [1] in [-2147483648, 2147483647] gives [1](0)
[Nov 27 01:55:12] DEBUG[213] config.c: extract uint from [1] in [0, 4294967295] gives [1](0)
[Nov 27 01:55:12] DEBUG[213] config.c: extract int from [30] in [-2147483648, 2147483647] gives [30](0)
[Nov 27 01:55:12] DEBUG[213] config.c: extract uint from [0] in [0, 65535] gives [0](0)
[Nov 27 01:55:12] DEBUG[213] config.c: extract int from [5] in [-2147483648, 2147483647] gives [5](0)
[Nov 27 01:55:12] DEBUG[213] res_pjsip/pjsip_distributor.c: Could not find matching transaction for Request msg INVITE/cseq=21703 (rdata0x7fc4522757f8)
[Nov 27 01:55:12] DEBUG[213] res_pjsip/pjsip_distributor.c: Taskprocessor overload alert: Ignoring 'Request msg INVITE/cseq=21703 (rdata0x7fc4522757f8)'.


pjsip/distributor-0000001f                                                   2399          0          3        450        500
pjsip/distributor-00000020                                                    955        504          4        450        500
pjsip/distributor-00000021                                                   2321          0          4        450        500
pjsip/distributor-00000022                                                   2214          0          3        450        500
pjsip/distributor-00000023                                                   2543          0          4        450        500
pjsip/distributor-00000024                                                   2343          0          4        450        500
pjsip/distributor-00000025                                                   2523          0          3        450        500
pjsip/distributor-00000026                                                   2322          0          3        450        500
pjsip/distributor-00000027                                                   2274          0          4        450        500
pjsip/distributor-00000028                                                   2393          0          3        450        500
pjsip/distributor-00000029                                                   2360          0          3        450        500
pjsip/distributor-0000002a                                                   2227          0          4        450        500
pjsip/distributor-0000002b                                                   2565          0          3        450        500
pjsip/distributor-0000002c                                                   2302          0          3        450        500
pjsip/distributor-0000002d                                                   2722          0          3        450        500



After upgrading to version 22.0.0, I encountered a new issue. However, in the rush to restore the service, I forgot to dump the core file. 

This is just a note for now. I will create an issue later after dumping the core file.

The following is the complete output.



LZiBo-MINISBC1*CLI> core show taskprocessors

Processor                                                               Processed   In Queue  Max Depth  Low water High water
ast_msg_queue                                                                   0          0          0        450        500
CCSS_core                                                                       0          0          0        450        500
dns_system_resolver_tp                                                          0          0          0        450        500
pjsip/default-00000010                                                       5166          0          2        450        500
pjsip/default-00000011                                                          0          0          0        450        500
pjsip/default-00000012                                                          0          0          0        450        500
pjsip/default-00000013                                                          0          0          0        450        500
pjsip/default-00000014                                                          0          0          0        450        500
pjsip/default-00000015                                                          0          0          0        450        500
pjsip/default-00000016                                                          0          0          0        450        500
pjsip/default-00000017                                                          0          0          0        450        500
pjsip/distributor-0000001f                                                   2399          0          3        450        500
pjsip/distributor-00000020                                                    955        504          4        450        500
pjsip/distributor-00000021                                                   2321          0          4        450        500
pjsip/distributor-00000022                                                   2214          0          3        450        500
pjsip/distributor-00000023                                                   2543          0          4        450        500
pjsip/distributor-00000024                                                   2343          0          4        450        500
pjsip/distributor-00000025                                                   2523          0          3        450        500
pjsip/distributor-00000026                                                   2322          0          3        450        500
pjsip/distributor-00000027                                                   2274          0          4        450        500
pjsip/distributor-00000028                                                   2393          0          3        450        500
pjsip/distributor-00000029                                                   2360          0          3        450        500
pjsip/distributor-0000002a                                                   2227          0          4        450        500
pjsip/distributor-0000002b                                                   2565          0          3        450        500
pjsip/distributor-0000002c                                                   2302          0          3        450        500
pjsip/distributor-0000002d                                                   2722          0          3        450        500
pjsip/distributor-0000002e                                                   2414          0          3        450        500
pjsip/distributor-0000002f                                                   2436          0          3        450        500
pjsip/distributor-00000030                                                   2491          0          3        450        500
pjsip/distributor-00000031                                                   2398          0          3        450        500
pjsip/distributor-00000032                                                   2323          0          3        450        500
pjsip/distributor-00000033                                                   2536          0          3        450        500
pjsip/distributor-00000034                                                   2260          0          3        450        500
pjsip/distributor-00000035                                                   2384          0          4        450        500
pjsip/distributor-00000036                                                   2374          0          3        450        500
pjsip/distributor-00000037                                                   2264          0          3        450        500
pjsip/distributor-00000038                                                   2095          0          3        450        500
pjsip/distributor-00000039                                                   2510          0          3        450        500
pjsip/distributor-0000003a                                                   2233          0          4        450        500
pjsip/distributor-0000003b                                                   2568          0          3        450        500
pjsip/distributor-0000003c                                                   2520          0          4        450        500
pjsip/distributor-0000003d                                                   2123          0          3        450        500
pjsip/exten_state                                                               0          0          0        450        500
pjsip/messaging                                                                 0          0          0        450        500
pjsip/mwi-00000047                                                              1          0          1        450        500
pjsip/mwi-00000048                                                              0          0          0        450        500
pjsip/mwi-00000049                                                              0          0          0        450        500
pjsip/mwi-0000004a                                                              0          0          0        450        500
pjsip/mwi-0000004b                                                              0          0          0        450        500
pjsip/mwi-0000004c                                                              0          0          0        450        500
pjsip/mwi-0000004d                                                              0          0          0        450        500
pjsip/mwi-0000004e                                                              0          0          0        450        500
pjsip/options/manage                                                           15          0          3       4500       5000
pjsip/options/outgoing-0000003e                                               655          0          2        450        500
pjsip/options/outgoing-huru-0000003f                                          787          0          2        450        500
pjsip/outsess/outgoing-00000eae                                                14          0          2        450        500
pjsip/outsess/outgoing-0000126c                                                12          0          2        450        500
pjsip/outsess/outgoing-000012fe                                                14          0          2        450        500
pjsip/outsess/outgoing-0000136e                                                15          0          2        450        500
pjsip/outsess/outgoing-000013cd                                                14          0          2        450        500
pjsip/outsess/outgoing-000013e9                                                15          0          2        450        500
pjsip/outsess/outgoing-0000141a                                                15          0          2        450        500
pjsip/outsess/outgoing-0000144e                                                15          0          2        450        500
pjsip/pool                                                                 130605          0          3        450        500
pjsip/pool-control                                                         261270          0          6        450        500
pjsip/refer                                                                     0          0          0        450        500
sorcery/acl-00000051                                                            0          0          0        450        500
sorcery/aor-0000000b                                                            3          0          1        450        500
sorcery/asterisk-publication-00000050                                           0          0          0        450        500
sorcery/auth-0000000a                                                           0          0          0        450        500
sorcery/bucket-00000000                                                         0          0          0        450        500
sorcery/client-00000041                                                         0          0          0        450        500
sorcery/contact-0000000d                                                        0          0          0       1350       1500
sorcery/domain_alias-0000000c                                                   0          0          0        450        500
sorcery/endpoint-00000009                                                       5          0          1        450        500
sorcery/file-00000001                                                           0          0          0        450        500
sorcery/global-00000019                                                         5          0          1        450        500
sorcery/identify-00000040                                                       0          0          0        450        500
sorcery/inbound-publication-00000045                                            0          0          0        450        500
sorcery/log_mappings-00000008                                                   0          0          0        450        500
sorcery/nat_hook-00000018                                                       0          0          0        450        500
sorcery/outbound-publish-00000042                                               0          0          0        450        500
sorcery/pool                                                                   14          0          2        450        500
sorcery/pool-control                                                           32          0          2        450        500
sorcery/registration-00000053                                                   1          0          1        450        500
sorcery/resource_list-00000044                                                  0          0          0        450        500
sorcery/subscription_persistence-00000043                                       0          0          0        450        500
sorcery/system-0000000e                                                         0          0          0        450        500
sorcery/transport-0000000f                                                      0          0          0        450        500
stasis/m:ari:application/call-00000062                                     289868          0         16        450        500
stasis/m:ari:application/config-00000060                                        1          0          1        450        500
stasis/m:bridge:all-00000055                                                    3          0          1        450        500
stasis/m:bridge:all-0000005f                                                    2          0          1        450        500
stasis/m:bridge:all-00000061                                                    1          0          1        450        500
stasis/m:cache_pattern:0/endpoint:all-00000007                                 16          0          2        450        500
stasis/m:cache_pattern:0/endpoint:all-0000005c                              20493          0          2        450        500
stasis/m:cdr:aggregator-00000005                                                1          0          1       4500       5000
stasis/m:channel:all-00000056                                                   3          0          1        450        500
stasis/m:channel:all-0000005a                                              205444          0         11        450        500
stasis/m:channel:all-0000005b                                              205443          0         10        450        500
stasis/m:devicestate:all-00000002                                           28976          0          2        450        500
stasis/m:devicestate:all-00000003                                           28976          0          5        450        500
stasis/m:manager:core-00000006                                             325600          0         23       2700       3000
stasis/m:mwi:all-00000057                                                       1          0          1        450        500
stasis/m:parking:all-00000058                                                   1          0          1        450        500
stasis/m:presence_state:all-00000004                                            1          0          1        450        500
stasis/m:security:all-0000001e                                                  1          0          1        450        500
stasis/m:security:all-00000052                                                  1          0          1        450        500
stasis/m:security:all-0000005e                                                130          0          1        450        500
stasis/m:system:all-00000054                                                    1          0          1        450        500
stasis/m:system:all-0000005d                                                    1          0          1        450        500
stasis/p:endpoint:PJSIP/incoming-0000001a                                   63526          0          6        450        500
stasis/p:endpoint:PJSIP/incoming-huru-0000001b                              14592          0          4        450        500
stasis/p:endpoint:PJSIP/outgoing-0000001c                                   75326          0          5        450        500
stasis/p:endpoint:PJSIP/outgoing-huru-0000001d                              17230          0          4        450        500
stasis/pool                                                                166457          0          4        450        500
stasis/pool-control                                                        332980          0          5        450        500

117 taskprocessors

**Comment by gtjoseph** [comment]
@Tinet-mucw Can you clarify the status of this issue?  It seems that after upgrading the originally reported issue went away but you have a new issue now?  Can we close this issue and will you be opening a new one?

**Comment by Tinet-mucw** [comment]
just as i said ， This is just a note for now. I will create an issue later after dumping the core file.

Can be ignored.

**Comment by Tinet-mucw** [comment]
This issue can also be closed, as the recurrence of such issues typically happens on a yearly basis.
