### ISSUE TITLE
[bug]: MixMonitor option D: Documentation claims it's support in Asterisk 20 - it's not.

### ISSUE THREAD

**Issue by Alec-Davis-NZ** [asterisk/asterisk#1009]
### Severity

Trivial

### Versions

20

### Components/Modules

documentation

### Operating Environment

Debain

### Frequency of Occurrence

None

### Issue Description

https://docs.asterisk.org/Asterisk_20_Documentation/API_Documentation/Dialplan_Applications/MixMonitor/

It was added in 21.6.0

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
The documentation is currently generated nightly from the individual branches, so as soon as it is merged in the next day it appears on the docs site. In the future we hope to include version information of when stuff is added to make it clearer, but that is not present as of this time.
