### ISSUE TITLE
[bug]: pjsip not authenticating with some providers

### ISSUE THREAD

**Issue by Kaalaaa** [asterisk/asterisk#1010]
### Severity

Trivial

### Versions

Current 

### Components/Modules

Pjsip

### Operating Environment

Debian 12

### Frequency of Occurrence

None

### Issue Description

Other flavors of pjsip or based on pjsip like micro sip are working fine with providers but pjsip is not communicating it gives errors and or problem in module host unreachable 

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
We appreciate the difficulties you are facing, however this does not appear to be a bug report and your request or comments would be better served in a different forum.

The Asterisk community provides support over IRC, mailing lists, and forums[1] as described at http://asterisk.org/community. The Asterisk issue tracker is used specifically to track issues concerning bugs and documentation errors.

Thanks!

[1] https://community.asterisk.org/
