### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by howardlowndes** [asterisk/asterisk#1012]
### Severity

Minor

### Versions

22.1.0

### Components/Modules

res_pjsip.so

### Operating Environment

Raspberry Pi 3+ running Raspian PiOS (debian bookworm 12) (aarch64) 
Clean download of asterisk-22.1.0
libjansson-dev installed

### Frequency of Occurrence

Constant

### Issue Description

When running ./configure , in the early stages, the script complains about OpenSSL >= 1.1.0 not being installed.
In fact the installed version of openssl is:
howard@raspi-dmz:~/asterisk-22.1.0 $ openssl version
OpenSSL 3.0.15 3 Sep 2024 (Library: OpenSSL 3.0.15 3 Sep 2024)
The impact of this is that module res_pjsip.so fail to be built and result in many downline modules failing to load

### Relevant log output

```shell
configure: checking OPENSSL with pkg-config
configure: checking whether system openssl > 1.1.0
checking for openssl >= 1.1.0... no
configure: checking whether alternate openssl11 is installed
checking for openssl11... no
configure: checking fallback system openssl
checking for openssl... no
configure: WARNING: OpenSSL does not seem to be installed

howard@raspi-dmz:~ $ sudo asterisk -rv
Asterisk 22.1.0, Copyright (C) 1999 - 2022, Sangoma Technologies Corporation and others.
Created by Mark Spencer <markster@digium.com>
Asterisk comes with ABSOLUTELY NO WARRANTY; type 'core show warranty' for details.
This is free software, with components licensed under the GNU General Public
License version 2 and other licenses; you are welcome to redistribute it under
certain conditions. Type 'core show license' for details.
=========================================================================
Connected to Asterisk 22.1.0 currently running on raspi-dmz (pid = 127473)
raspi-dmz*CLI> module load res_pjsip.so
Unable to load module res_pjsip.so
Command 'module load res_pjsip.so' failed.
[Dec  2 21:55:47] ERROR[127570]: loader.c:283 module_load_error: Error loading module 'res_pjsip.so': /usr/lib/asterisk/modules/res_pjsip.so: undefined symbol: pjsip_tls_transport_restart
raspi-dmz*CLI>
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Please attach the config.log file

**Comment by jcolp** [comment]
And is the libssl-dev package installed?

**Comment by howardlowndes** [comment]
woops

**Comment by jcolp** [comment]
I'll take that as a no?

**Comment by howardlowndes** [comment]
Reopening this please.
 I've installed libssl-dev and libtls-dev and rerun 'sudo make', 'sudo make install', 'sudo service asterisk restart'.
I still get res_pjsip.so to load.
Screen shot, ./config.log, and /var/log/asterisk/messages.log attached.

> =========================================================================
> Connected to Asterisk 22.1.0 currently running on raspi-dmz (pid = 192944)
> raspi-dmz*CLI> module load res_pjsip.so
> Unable to load module res_pjsip.so
> Command 'module load res_pjsip.so' failed.
> [Dec  3 07:50:13] ERROR[193012]: loader.c:283 module_load_error: Error loading module 'res_pjsip.so': /usr/lib/asterisk/modules/res_pjsip.so: undefined symbol: pjsip_tls_transport_restart
> raspi-dmz*CLI> 
> 

[config.log.txt](https://github.com/user-attachments/files/17984158/config.log.txt)
[messages.log.txt](https://github.com/user-attachments/files/17984160/messages.log.txt)

**Comment by howardlowndes** [comment]
TYPO
I still get res_pjsip.so to load.
I still **CAN'T** get res_pjsip.so to load.

**Comment by jcolp** [comment]
Are there other installations of PJSIP on the system? That behavior can occur if there is a conflicting installation of PJSIP on the system built differently.

**Comment by howardlowndes** [comment]
None. It's a pretty clean system that I am trying to build up.
I could clean out all references to asterisk and rebuild from fresh.

**Comment by jcolp** [comment]
Is there a pjproject or pjsip package installed? What is the output of "ls /usr/include/pjsip*" and "ls /usr/local/include/pjsip*"?

**Comment by jcolp** [comment]
And I would indeed suggest a "make distclean" and rebuild just in case.

**Comment by howardlowndes** [comment]
BINGO !!!
It looks as if  that might have been the enema it needed. 
One query tho... When I run 'sudo netstat -pant' I see no evidence of port 5060, but I do see evidence of asterisk ports when I run 'sudo netstat -panu'. I would have expected 5060/tcp to have kicked in when I started asterisk.

Many thanks for your assistance !!!

[config.log.txt](https://github.com/user-attachments/files/17984839/config.log.txt)
[messages.log.txt](https://github.com/user-attachments/files/17984842/messages.log.txt)
