### ISSUE TITLE
[bug]: Strange warning - 'T' option is not compatible with remote console mode and has no effect.

### ISSUE THREAD

**Issue by intellasoft** [asterisk/asterisk#102]
### Severity

Trivial

### Versions

18, 19, 20, 21

### Components/Modules

cli

### Operating Environment

Any

### Frequency of Occurrence

Constant

### Issue Description

```
root# asterisk -rvvvv -T
'T' option is not compatible with remote console mode and has no effect.

Asterisk 18.14.0, Copyright (C) 1999 - 2022, Sangoma Technologies Corporation and others.
Created by Mark Spencer <markster@digium.com>
Asterisk comes with ABSOLUTELY NO WARRANTY; type 'core show warranty' for details.
This is free software, with components licensed under the GNU General Public
License version 2 and other licenses; you are welcome to redistribute it under
certain conditions. Type 'core show license' for details.
=========================================================================
Connected to Asterisk 18.14.0 currently running on IS-COMM-NYC-01 (pid = 26094)
[2023-05-18 14:27:18.293-0400] VERBOSE[21689][C-00001348]: <PJSIP/c30081-101-00001d9f> Playing 'vm-Old.ulaw' (language 'en')
[2023-05-18 14:27:18.878-0400] VERBOSE[21689][C-00001348]: <PJSIP/c30081-101-00001d9f> Spawn extension (checkOwnVoicemail, s, 18) exited non-zero
[2023-05-18 14:27:18.878-0400] VERBOSE[21689][C-00001348]: <PJSIP/c30081-101-00001d9f> Got SoftHangup Request (0x7ffab049f6d0) (cause: 16)

```
But.. the -T option *does* have an effect.  It turns on timestamps for all console messages, even if asterisk is not configured to do so by default.

@InterLinked1 

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
@InterLinked1 This warning came from you. Can you clarify why you thought T didn't work on remote console, and if you were incorrect?

**Comment by jcolp** [comment]
I'm not sure what you' referring to. I didn't tag you or anything. Naveen Albert is InterLinked.

**Comment by InterLinked1** [comment]
> @InterLinked1 This warning came from you. Can you clarify why you thought T didn't work on remote console, and if you were incorrect?

Probably just an oversight. I just tested this and the 'T' option does seem to have some special handling at least for verbose messages. I can fix the warning if you assign this to me.

**Comment by intellasoft** [comment]
@jcolp  Whoops sorry.  I didn't process the tag aspect.  Still getting familiar with github.

I can't change assignments I don't believe.

**Comment by intellasoft** [comment]
@InterLinked1 Here's something to check out.

If you run asterisk out of the box without any special options or logging setup.. timestamps only print to the log file, and then when you connect via asterisk -r, there's no timestamps on verbose messages, you only get timestamps on errors,warnings,notices

If you do asterisk -rT, then you do get timestampes on all verbose messages
