### ISSUE TITLE
[new-feature]: fair handling of calls in multi-queue scenarios

### ISSUE THREAD

**Issue by nbruning** [asterisk/asterisk#108]
### Feature Description

Currently, Asterisk queue handling is performed from the perspective of the caller: for a given call, find an agent that could handle the call.

When an agent is in multiple queues, there may be many callers that want to be connected - any asterisk does not guarantee which one is handled first. For call centers, it makes sense to handle callers "in order", ie. handle first the caller that is waiting for the longest period of time.

This was previously discussed in these issues:
- https://issues.asterisk.org/jira/browse/ASTERISK-17732
- https://issues.asterisk.org/jira/browse/ASTERISK-17570

**Comment by jcolp** [comment]
Will this be going up as a pull request? If not there is a separate repository for feature requests.
