### ISSUE TITLE
[bug]: SIP Reason: "Call completed elsewhere" no longer propagating

### ISSUE THREAD

**Issue by AstersikRoss** [asterisk/asterisk#116]
### Severity

Minor

### Versions

18, 20, 21, master

### Components/Modules

res_pjsip_rfc3326

### Operating Environment

Cent OS

### Frequency of Occurrence

None

### Issue Description

Since Gerrit commit 19570 the 'Call completed elsewhere' reason is not passed on to endpoints.

The setup is as follows:

    Endpoint -> Asterisk 1 (via Call Group) -> Asterisk 2 -> Endpoint

To test make a call from one Endpoint on Asterisk 1 which contains a group with two endpoints on Asterisk 2. Answer the call on one of the endpoints in the group. Asterisk 1 sends headers:

    CSeq: 29930 CANCEL
    Reason: SIP;cause=200;text="Call completed elsewhere"
    Reason: Q.850;cause=26
    Max-Forwards: 70
    User-Agent: Asterisk
    Content-Length: 0

Asterisk 2 does not send on the 'Reason' headers.

Asterisk 1 does not contain the patch and passes on the Headers correctly.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by AstersikRoss** [comment]
> static void rfc3326_use_reason_header(struct ast_sip_session *session, struct pjsip_rx_data *rdata)

This method appears to remove the cause text from the header and doesn't account for the string 'Call completed elsewhere' being present indicating that the cause code within Asterisk should be set to AST_CAUSE_ANSWERED_ELSEWHERE

**Comment by seanbright** [comment]
@AstersikRoss can you please test the patch at https://github.com/asterisk/asterisk/pull/161 and let us know if it resolves this?
