### ISSUE TITLE
[bug]: command output "core show channels verbose" now has two lines

### ISSUE THREAD

**Issue by silentindark** [asterisk/asterisk#117]
### Severity

Trivial

### Versions

18.18.0

### Components/Modules

cli

### Operating Environment

Debian 11.7

### Frequency of Occurrence

Constant

### Issue Description

In Asterisk 18.18.0 command output "core show channels verbose" now has two lines, I think that is not correct

Asterisk 18.18.0 (output in two lines)
CLI> core show channels verbose
Channel                                                                          Context                  Extension                Prio State   Application  Data                      CallerID        Duration Accountcode PeerAccount BridgeID

Asterisk 18.17.0 (output in one line)
CLI> core show channels verbose
Channel              Context              Extension        Prio State   Application  Data                      CallerID        Duration Accountcode PeerAccount BridgeID

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by silentindark** [comment]
The commit being referred to https://github.com/asterisk/asterisk/commit/20b0cfca396cf3e724fcf8dc8f850593469b05fd

**Comment by jcolp** [comment]
The line is a single line, what is happening is that in some terminals the string is now wide enough that the terminal wraps it and displays it visually on two lines, even though it is a single line.

**Comment by jcolp** [comment]
I'm not sure there is a real good "fix" for this while keeping it verbose and trying to give full information. We could go back to the old way, and things would go back to being cut off.

**Comment by mbradeen** [comment]
@silentindark - as this is due to wrapping due on terminal width, would you still be in favor of reverting the change or perhaps something else?

**Comment by smurfix** [comment]
So make the terminal wider / the font smaller? This is hardly an Asterisk-specific problem IMHO.
