### ISSUE TITLE
[bug]: Asterisk fails to start with res_srtp / Enterprise Linux 9

### ISSUE THREAD

**Issue by neimaravila** [asterisk/asterisk#125]
### Severity

Blocker

### Versions

20.3.0

### Components/Modules

res_srtp

### Operating Environment

Alma Linux 9
Red Hat Enterprise 9
Oracle Linux 9
Rocky Linux 9

### Frequency of Occurrence

Constant

### Issue Description

Asterisk crash on startup, when module res_srtp is loading.
Issue ocur when using latest libsrtp (2.3.0).

If I build libsrtp 1.5 (rpm rebuild from EL8), issue not ocur.

### Relevant log output

```shell
Loading res_srtp.so.
[May 26 12:52:12] WARNING[1277916]: res_srtp.c:1238 res_srtp_init: Failed to initialize libsrtp
[May 26 12:52:12] ERROR[1277916]: loader.c:2524 load_modules: *** Failed to load module res_srtp.so
[May 26 12:52:12] ERROR[1277916]: asterisk.c:4039 check_init: Module initialization failed.  ASTERISK EXITING!
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by seanbright** [comment]
There is no crash here. Asterisk says it's going to exit and then it does.

**Comment by neimaravila** [comment]
Ok, crash is not the best word to describe. 
Asterisk not work if module is load.

**Comment by seanbright** [comment]
This does not appear to be specific to asterisk. If you compile and run this simple program:

```
[rocky@host]$ cat simple.c
#include <stdio.h>
#include <srtp2/srtp.h>

int main(int argc, char *argv[])
{
  srtp_err_status_t status = srtp_init();
  if (status != srtp_err_status_ok) {
    fprintf(stderr, "Failed to initialize libsrtp (%d)\n", status);
    return 1;
  }

  srtp_shutdown();
  return 0;
}
[rocky@host]$ LDLIBS=$(pkg-config libsrtp2 --libs) make simple
cc     simple.c  -lsrtp2 -lssl3 -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -lpthread -ldl  -o simple
[rocky@host]$ ./simple
Failed to initialize libsrtp (8)
```

Error `8` is `srtp_err_status_cipher_fail`. I haven't dug in to this enough to know why it's happening but it's not asterisk that is causing it.

**Comment by jcolp** [comment]
As @seanbright stated, this is not an Asterisk issue but an issue with the underlying system libsrtp.
