### ISSUE TITLE
[bug]: res_speech_aeap: Crash due to NULL format on setup

### ISSUE THREAD

**Issue by wphowell** [asterisk/asterisk#129]
### Severity

Trivial

### Versions

18.14.0, 18.16.0, 20.2.0

### Components/Modules

res_speech_aeap

### Operating Environment

Amazon Linux 2 on x86_64 and aarch64

### Frequency of Occurrence

None

### Issue Description

This is a carry forward of https://issues.asterisk.org/jira/browse/ASTERISK-30420 which has been reconfirmed as a continuing issue on v20 as well as v18.

We receive from Asterisk:
```
{
    "request": "setup",
    "version": "0.1.0",
    "codecs":
    [
        {
            "name": "ulaw"
        }
    ],
    "params":
    {},
    "id": "211233a3-48de-4758-b46c-90b3701a3d06"
}
```

We reply successfully with:
```
{
    "response": "setup",
    "id": "211233a3-48de-4758-b46c-90b3701a3d06",
    "codecs":
    [
        {
            "name": "ulaw"
        }
    ]
}
```

Asterisk shows the following, and then SEGFAULTs:

```fundamental
ERROR[19158] res_aeap/transaction.c: AEAP transaction (0x7f5f0800f8d0): message 'setup' timed out
VERBOSE[8438][C-0000003b] pbx.c: Executing [17195559990@dial-out:7] SpeechStart("IAX2/hwl-pbx-5767", "") in new stack
VERBOSE[8438][C-0000003b] pbx.c: Spawn extension (dial-out, 17195559990, 7) exited non-zero on 'IAX2/hwl-pbx-5767'
VERBOSE[8438][C-0000003b] chan_iax2.c: Hungup 'IAX2/hwl-pbx-5767'
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by wphowell** [comment]
We have one customer where this bug is happening about 7 times per day (and they lose about 50 active calls), but with other customers infrequently.  If you need more data on reproducing this, I can certainly provide more debug if it's useful.

**Comment by jcolp** [comment]
If any additional information is required then it will be asked for here. Ultimately someone has to take on this issue, investigate, and resolve it.

**Comment by wphowell** [comment]
I'm sure that someone probably wants to look deeper into this, but can we just push this for now?

res/res_speech_aeap.c
281a282,286
>       if (!format) {
>               log_error(aeap, "no 'format' received");
>               return -1;
>       }
>

**Comment by jcolp** [comment]
I'm not working on this issue. In general any PRs that go up for review get reviewed.

**Comment by mbradeen** [comment]
@wphowell are you getting an assertion / backtrace when this happens?

**Comment by wphowell** [comment]
[core-asterisk-2023-08-21T22-14-51Z-thread1.txt](https://github.com/asterisk/asterisk/files/12424912/core-asterisk-2023-08-21T22-14-51Z-thread1.txt)
[core-asterisk-2023-08-21T22-14-51Z-locks.txt](https://github.com/asterisk/asterisk/files/12424913/core-asterisk-2023-08-21T22-14-51Z-locks.txt)
[core-asterisk-2023-08-21T22-14-51Z-info.txt](https://github.com/asterisk/asterisk/files/12424914/core-asterisk-2023-08-21T22-14-51Z-info.txt)
[core-asterisk-2023-08-21T22-14-51Z-full.txt](https://github.com/asterisk/asterisk/files/12424915/core-asterisk-2023-08-21T22-14-51Z-full.txt)
[core-asterisk-2023-08-21T22-14-51Z-brief.txt](https://github.com/asterisk/asterisk/files/12424916/core-asterisk-2023-08-21T22-14-51Z-brief.txt)

**Comment by wphowell** [comment]
This type of crash occurs over a dozen times per day.  We have the patch listed above in a few call centers and have seen 0 crashes, since adding that patch.
