### ISSUE TITLE
[improvement]: Fix TLS handling within Asterisk / pjsip.

### ISSUE THREAD

**Issue by CRCinAU** [asterisk/asterisk#162]
### Improvement Description

As listed here: https://github.com/asterisk/asterisk-feature-requests/issues/6
Currently, when configuring Asterisk + PJSIP for a TLS transport, there is only the ability to set ONE TLS level. These options are like:
* SSLv2 (method = sslv2)
* SSLv3 (method = sslv3)
* SSLv2+SSLv3 (method = sslv23)
* TLSv1 (method = tlsv1)
* TLSv1.1 (method = tlsv1_1)
* TLSv1.2 (method = tlsv1_2)

It is not possible to set multiple TLS levels like most server software allows, and allow the client to negotiate to the highest supported TLS level.

As such, an expected valid, but non-available configuration would be: method = tlsv1_1, tlsv1_2

This would allow the transport to support both TLSv1.1 and TLSv1.2 protocols.

The Mozilla SSL Configuration Generator is a good example on how the majority of popular server software is configured for different cipher + TLS levels, such as:

* Apache: `SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1`
* Dovecot: `ssl_min_protocol = TLSv1.2`
* nginx: `ssl_protocols TLSv1.2 TLSv1.3;`
* postfix: `smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1`
* postgres: `ssl_min_protocol_version = 'TLSv1.2'`

Asterisk support for setting the TLS protocol levels seems to be handled here:
https://github.com/asterisk/asterisk/blob/master/res/res_pjsip/config_transport.c#L1209

As this is an entire if / else if block, it does not seem to be able to process multiple configuration items for a TLS transport.

As a best practice however, it should probably be prudent to remove SSLv2 and SSLv3 support completely. They are utterly broken and should not be used for *any* purpose these days.

Further to this topic, the Asterisk documentation still uses examples to enable / use `sslv23` for the example TLS configurations:
https://wiki.asterisk.org/wiki/display/AST/Secure+Calling+Tutorial

This is horribly wrong, but should be updated to reflect:
a) An improved TLS handling within Asterisk / PJSIP interface; and
b) Document the new implementation of TLS handling; and
c) Provide an example of at least a 'best-practice' compliant settings; and
d) As PJSIP is compiled against OpenSSL v3, then TLSv1.3 should also be implemented and be available

There is also a followup on this where there is a requirement to load a trusted bundle of root certs for validation of outgoing TLS connections to TLS enabled SIP servers.

The only way I've found to do this is to add something like ca_list_file=/etc/pki/tls/cert.pem to the pjsip.conf file. This allows certificates to be validated, however, it also adds them all to the TLS CA List for Client Auth - which is obviously incorrect behaviour.

As such, there probably needs to be a way to supply a cert bundle of trusted roots to be able to validate TLS certificates on outbound connections / registrations.

**Comment by jcolp** [comment]
Feature requests and improvement requests are in the repository you've already put an issue in. This repository is if you have code changes to put up for PR, or for bug reports.
