### ISSUE TITLE
[bug]: pjsip_ua_find_dialog panic

### ISSUE THREAD

**Issue by Tinet-mucw** [asterisk/asterisk#164]
[core-asterisk-2023-06-19T09-59-01Z-info.txt](https://github.com/asterisk/asterisk/files/11787399/core-asterisk-2023-06-19T09-59-01Z-info.txt)
[core-asterisk-2023-06-19T09-59-01Z-full.txt](https://github.com/asterisk/asterisk/files/11787400/core-asterisk-2023-06-19T09-59-01Z-full.txt)
[core-asterisk-2023-06-19T09-59-01Z-locks.txt](https://github.com/asterisk/asterisk/files/11787401/core-asterisk-2023-06-19T09-59-01Z-locks.txt)
[core-asterisk-2023-06-19T09-59-01Z-brief.txt](https://github.com/asterisk/asterisk/files/11787402/core-asterisk-2023-06-19T09-59-01Z-brief.txt)
[core-asterisk-2023-06-19T09-59-01Z-thread1.txt](https://github.com/asterisk/asterisk/files/11787403/core-asterisk-2023-06-19T09-59-01Z-thread1.txt)
### Severity

Trivial

### Versions

18.10

### Components/Modules

res_pjsip

### Operating Environment

docker :
/]# cat /etc/os-release 
NAME="openEuler"
VERSION="20.03 (LTS)"
ID="openEuler"
VERSION_ID="20.03"
PRETTY_NAME="openEuler 20.03 (LTS)"
ANSI_COLOR="0;31"

machine：
cat /etc/os-release 
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

### Frequency of Occurrence

Occasional

### Issue Description

When both the SIP messages 183 and 200Ok arrive at the same time, there is a chance of a crash in the execution of the pjsip_ua_find_dialog function. The pjsip_ua_find_dialog function finds the associated serializer to ensure sequential processing of SIP messages with the same call ID. However, the execution of the pjsip_ua_find_dialog function and the processing of distribute and subsequent logic happen simultaneously.

Looking at the core file, we can see that the stack data is correct, but the register data is incorrect.

Translation:

(gdb) info register
x0 0x0 0
x1 0xffff985cab1a 281473237953306
x2 0x10 16
x3 0x0 0
x4 0xffffa7b8f3a8 281473495659432
x5 0xffff5d562870 281472247670896
x6 0x39 57
x7 0xffffa7b2b560 281473495250272
x8 0x62 98
x9 0xffff5d562870 281472247670896
x10 0xa 10
x11 0xffffffffffffffff -1
x12 0x2e39312e31332e32 3330747473880886834
x13 0x303630353a3039 13570379561447481
x14 0x11 17
x15 0xa 10
x16 0xffffa87fb160 281473508684128
x17 0xffffa7a91420 281473494619168
x18 0xffff5d560f78 281472247664504
x19 0xffff5d562170 281472247669104
x20 0xfffff46ef640 281474782656064
x21 0xfffff46ef5ae 281474782655918
x22 0xfffff46ef5af 281474782655919
x23 0x1000 4096
x24 0x29282e48 690499144
x25 0xffffa7ed2000 281473499078656
x26 0xffff5d562870 281472247670896
x27 0xfffff46ef640 281474782656064
x28 0xffff5d562170 281472247669104
x29 0xffff5d5610b0 281472247664816
x30 0xffffa8791454 281473508250708
sp 0xffff5d5610b0 0xffff5d5610b0
pc 0xffffa8791454 0xffffa8791454 <pj_stricmp+148>
cpsr 0x80001000 [ EL=0 N ]
fpsr 0x10 16
fpcr 0x0 0
vg 0x2 2

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
It appears the bug you have submitted is against a rather old version of a supported branch of Asterisk. There have been many issues fixed between the version you are using and the current version of your branch. Please test with the latest version in your Asterisk branch and report whether the issue persists.

Please see the Asterisk Versions [1] wiki page for info on which versions of Asterisk are supported.
[1] https://wiki.asterisk.org/wiki/display/AST/Asterisk+Versions

**Comment by Tinet-mucw** [comment]
Due to the close association between Asterisk and the product, upgrading the Asterisk version requires careful consideration and thorough functional testing. Therefore, updating the Asterisk version is currently not being considered. The following is a description of a recent system crash, where thread 1 and thread 2 belonged to the same dialog.

[core-asterisk-2023-06-25T05-13-58Z-info.txt](https://github.com/asterisk/asterisk/files/11858996/core-asterisk-2023-06-25T05-13-58Z-info.txt)
[core-asterisk-2023-06-25T05-13-58Z-full.txt](https://github.com/asterisk/asterisk/files/11858997/core-asterisk-2023-06-25T05-13-58Z-full.txt)
[core-asterisk-2023-06-25T05-13-58Z-locks.txt](https://github.com/asterisk/asterisk/files/11858998/core-asterisk-2023-06-25T05-13-58Z-locks.txt)
[core-asterisk-2023-06-25T05-13-58Z-brief.txt](https://github.com/asterisk/asterisk/files/11858999/core-asterisk-2023-06-25T05-13-58Z-brief.txt)
[core-asterisk-2023-06-25T05-13-58Z-thread1.txt](https://github.com/asterisk/asterisk/files/11859000/core-asterisk-2023-06-25T05-13-58Z-thread1.txt)

**Comment by jcolp** [comment]
The issue is that you are majorly behind on Asterisk, and PJSIP has also been updated since. You're on an old version of each. Investigating old versions is something we try to avoid, because of the waste of time it can be due to things being fixed. I'll leave this untouched for now.

**Comment by Tinet-mucw** [comment]
Hello, we plan to upgrade our Asterisk version to 18.17, which uses PJSIP version 2.13, the latest version (PJSIP has undergone significant changes in recent releases).
thanks。
