### ISSUE TITLE
Asterisk with autoscaling support feature

### ISSUE THREAD

**Issue by vignesh-githunt** [asterisk/asterisk#166]
### Feature Description

Hi Team,

 We want to use auto scaling feature in Asterisk server please help on this..

**Comment by jcolp** [comment]
We appreciate the difficulties you are facing, however this does not appear to be a bug report and your request or comments would be better served in a different forum.

The Asterisk community provides support over IRC, mailing lists, and forums as described at https://asterisk.org/community. The Asterisk issue tracker is used specifically to track issues concerning bugs and documentation errors.

Please see the Asterisk Issue Guidelines [1] for instruction on the intended use of the Asterisk issue tracker.

Thanks!

[1] https://wiki.asterisk.org/wiki/display/AST/Asterisk+Issue+Guidelines
