### ISSUE TITLE
[bug]: Playback() does not support ampersand in URLs

### ISSUE THREAD

**Issue by wphowell** [asterisk/asterisk#172]
### Severity

Trivial

### Versions

18.18.0

### Components/Modules

app_playback

### Operating Environment

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
aarch64

### Frequency of Occurrence

Constant

### Issue Description

Playback supports URLs, but not if they contain an ampersand character -- which is valid in a URL.  S3 playback assets have many arguments that must be passed for authentication, but Playback will try to play each component separated by an ampersand independently; thereby playing no assets.

The strsep() function appears to not check for any escape character before the token, nor does app_playback.c -- (front = strsep(&back, "&"))); so there isn't any way to pass an S3 URL, for example.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by wphowell** [comment]
I should also add that we tried a URL shortener as a work-around, but then got:

res_http_media_cache.c:68 curl_header_callback: cURL header length of '1248' is too large: max 1023

So, it would seem that S3 URLs are just too long.

res/res_http_media_cache.c:#define MAX_HEADER_LENGTH 1023

**Comment by seanbright** [comment]
[Potential fix for this is up.](https://github.com/asterisk/asterisk/pull/418)

Due to the way that application arguments are parsed, you will need to double escape the ampersands for this new parsing code to see them. For example:

```
exten => 555,n,Playback(vm-login&https://whatever.com/get?filename=foo\\&blah=bar)
                                                                      ^^^
```

**Comment by seanbright** [comment]
[18.18.0.patch](https://github.com/asterisk/asterisk/files/13289061/18.18.0.patch)

And here is a patch against 18.18.0 so you could potentially test this for us?
