### ISSUE TITLE
[bug]: Queue strategy “Linear” with Asterisk 20 on Realtime

### ISSUE THREAD

**Issue by celsoannes** [asterisk/asterisk#179]
### Severity

Minor

### Versions

Asterisk 20.1.0

### Components/Modules

app_queue

### Operating Environment

```
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
```
psql (PostgreSQL) 13.11 (Debian 13.11-0+deb11u1)
```

### Frequency of Occurrence

Constant

### Issue Description

When using realtime to create a linear queue using PostgreSQL, the order in which extensions should be called is not respected.

I am defining the order in which extensions should be called based on the **`uniqueid`** column of the **`queue_members`** table. However, regardless of the order I specify or the order in which I perform the **`INSERT`** operations, Asterisk always sorts based on the **`interface`** column:

```
SELECT * FROM public.queue_members ORDER BY uniqueid ;
 queue_name | interface  | membername | state_interface  | penalty | paused | uniqueid | wrapuptime | ringinuse
------------+------------+------------+------------------+---------+--------+----------+------------+-----------
 demo       | PJSIP/4001 |            | hit:4001@default |         |      0 |        1 |            |
 demo       | PJSIP/2000 |            | hit:2000@default |         |      0 |        2 |            |
 demo       | PJSIP/4000 |            | hit:4000@default |         |      0 |        3 |            |
(3 rows)
```
The order defined in the database was:

1. 4001
2. 2000
3. 4000

Asterisk always load and ring queue based on the **`interface`** numeric order:

```
CLI> queue show
demo has 0 calls (max unlimited) in 'linear' strategy (0s holdtime, 0s talktime), W:0, C:0, A:0, SL:0.0%, SL2:0.0% within 0s
   Members:
      PJSIP/2000 (ringinuse disabled) (realtime) (Invalid) has taken no calls yet (login was 1191 secs ago)
      PJSIP/4000 (ringinuse disabled) (realtime) (Invalid) has taken no calls yet (login was 1191 secs ago)
      PJSIP/4001 (ringinuse disabled) (realtime) (Invalid) has taken no calls yet (login was 1191 secs ago)
   No Callers
```

### Asterisk Issue Guidelines

- [x] Yes, I have read the Asterisk Issue Guidelines

**Comment by seanbright** [comment]
Asterisk does not specify an order while querying the data so whatever order PostgreSQL returns the rows is what will get used. This usually means primary key order. You could potentially update your PK to `queue_name, uniqueid, interface` which would get you the order you want.

There is also a [`CLUSTER` command](https://www.postgresql.org/docs/current/sql-cluster.html) that looks potentially useful but I don't know much about PostreSQL to know for sure.

**Comment by celsoannes** [comment]
> Asterisk does not specify an order while querying the data so whatever order PostgreSQL returns the rows is what will get used. This usually means primary key order. You could potentially update your PK to `queue_name, uniqueid, interface` which would get you the order you want.
> 
> There is also a [`CLUSTER` command](https://www.postgresql.org/docs/current/sql-cluster.html) that looks potentially useful but I don't know much about PostreSQL to know for sure.

Thank you for the suggestion, but I have already tried creating the table with a column called `id` and set it as the only `primary key`, yet Asterisk ignores the defined order and continues to sort based on the `interface` column.
One thing that partially works is adding the extensions one by one, insert by insert, then Asterisk respects the order... until it is restarted. Then it goes back to sorting based on the `interface` column.

I haven't tested it yet, but I believe the `CLUSTER` option won't work because Asterisk seems to ignore any existing ordering in the database and sorts based on the `interface` column.

If it works, I'll come back to inform you.

**Comment by seanbright** [comment]
As I mentioned, Asterisk does not request a specific order from the database.

**Comment by celsoannes** [comment]
> As I mentioned, Asterisk does not request a specific order from the database.

I have to disagree with you, Asterisk is ordering by the `interface` column.

If I execute this sequence of `INSERT` statements:

```
INSERT INTO public.queue_members(
	queue_name, interface, uniqueid, state_interface)
	VALUES ('demo', 'PJSIP/4001', 1, 'hint:4001@default');

INSERT INTO public.queue_members(
	queue_name, interface, uniqueid, state_interface)
	VALUES ('demo', 'PJSIP/4000', 2, 'hint:4000@default');

INSERT INTO public.queue_members(
	queue_name, interface, uniqueid, state_interface)
	VALUES ('demo', 'PJSIP/2000', 3, 'hint:2000@default');
```

And then I execute the `queue show` command, the result is as follows:
```
bruce*CLI> queue show
demo has 0 calls (max unlimited) in 'linear' strategy (0s holdtime, 0s talktime), W:0, C:0, A:0, SL:0.0%, SL2:0.0% within 0s
   Members:
      PJSIP/2000 (ringinuse disabled) (realtime) (Unavailable) has taken no calls yet (login was 440 secs ago)
      PJSIP/4000 (ringinuse disabled) (realtime) (Unavailable) has taken no calls yet (login was 440 secs ago)
      PJSIP/4001 (ringinuse disabled) (realtime) (Unavailable) has taken no calls yet (login was 440 secs ago)
   No Callers
```
If I perform an `INSERT` and then execute a `queue show` command immediately after, it correctly orders the results.

```
INSERT INTO public.queue_members(
	queue_name, interface, uniqueid, state_interface)
	VALUES ('demo', 'PJSIP/4001', 1, 'hint:4001@default');
```
```
bruce*CLI> queue show
demo has 0 calls (max unlimited) in 'linear' strategy (0s holdtime, 0s talktime), W:0, C:0, A:0, SL:0.0%, SL2:0.0% within 0s
   Members:
      PJSIP/4001 (ringinuse disabled) (realtime) (Unavailable) has taken no calls yet (login was 0 secs ago)
   No Callers
```
```
INSERT INTO public.queue_members(
	queue_name, interface, uniqueid, state_interface)
	VALUES ('demo', 'PJSIP/4000', 2, 'hint:4000@default');
```
```
bruce*CLI> queue show
demo has 0 calls (max unlimited) in 'linear' strategy (0s holdtime, 0s talktime), W:0, C:0, A:0, SL:0.0%, SL2:0.0% within 0s
   Members:
      PJSIP/4001 (ringinuse disabled) (realtime) (Unavailable) has taken no calls yet (login was 25 secs ago)
      PJSIP/4000 (ringinuse disabled) (realtime) (Unavailable) has taken no calls yet (login was 0 secs ago)
   No Callers
```
```
INSERT INTO public.queue_members(
	queue_name, interface, uniqueid, state_interface)
	VALUES ('demo', 'PJSIP/2000', 3, 'hint:2000@default');
```
```
bruce*CLI> queue show
demo has 0 calls (max unlimited) in 'linear' strategy (0s holdtime, 0s talktime), W:0, C:0, A:0, SL:0.0%, SL2:0.0% within 0s
   Members:
      PJSIP/4001 (ringinuse disabled) (realtime) (Unavailable) has taken no calls yet (login was 63 secs ago)
      PJSIP/4000 (ringinuse disabled) (realtime) (Unavailable) has taken no calls yet (login was 38 secs ago)
      PJSIP/2000 (ringinuse disabled) (realtime) (Unavailable) has taken no calls yet (login was 0 secs ago)
   No Callers
```

In this way, Asterisk appears to create in the correct order, but if Asterisk is restarted, it reverts to sorting numerically.

These recent tests were conducted using the **CLUSTER** feature, and to work as expected, it needs to load one by one. 

Regardless of how the data is organized, if Asterisk reads everything at once, it will sort based on the interface.

**Comment by seanbright** [comment]
Asterisk does no explicit sorting based on `interface`. It is happenstance that in the specific scenario you are referring to by adding queue members one by one that the resulting internal storage of queue members results in it being sorted as you are stating.

**Comment by celsoannes** [comment]
```
; linear - rings interfaces in the order specified in this configuration file.
;          If you use dynamic members, the members will be rung in the order in
;          which they were added
```

If realtime queues followed the same rules as the configuration file, the interfaces should ring in the order they were added. However, there is no column to specify the order, and it doesn't seem to respect column ordering with a primary key.

It appears that there is no known workaround to bypass this issue and make the queue with a linear strategy behave as expected.

But if you have any other ideas, I'm open to putting them into practice.

**Comment by seanbright** [comment]
I was incorrect, Asterisk does sort by `interface` explicitly:

```
res_config_pgsql.c:184 _pgsql_exec: PostgreSQL query successful: SELECT * FROM queue_members WHERE interface LIKE '%' ESCAPE '\' AND queue_name = 'demo' ORDER BY interface
```

**Comment by seanbright** [comment]
I uploaded [a tentative PR](https://github.com/asterisk/asterisk/pull/207) for this if you are able to apply it and test. Basically you would apply the PR, `make` and `make install` asterisk, and then set:

```
[general]
...
order_multi_row_results_by_initial_column=no
```

in your `res_pgsql.conf` file.

I don't know how reasonable an approach this is, but for backwards compatibility I am not comfortable changing the default behavior.

**Comment by celsoannes** [comment]
I conducted several tests, and as far as I tested, it worked. It continues to respect the order even if you restart Asterisk.

```
SELECT * FROM public.queue_members ORDER BY id;
 id | queue_name | interface  | membername |  state_interface  | penalty | paused | uniqueid | wrapuptime | ringinuse
----+------------+------------+------------+-------------------+---------+--------+----------+------------+-----------
  1 | demo       | PJSIP/500  |            | hint:500@default  |         |        |        1 |            |
  2 | demo       | PJSIP/300  |            | hint:300@default  |         |        |        2 |            |
  3 | demo       | PJSIP/2000 |            | hint:2000@default |         |        |        3 |            |
(3 rows)
```
```
bruce*CLI> queue show
demo has 0 calls (max unlimited) in 'linear' strategy (0s holdtime, 0s talktime), W:0, C:0, A:0, SL:0.0%, SL2:0.0% within 0s
   Members:
      PJSIP/300 (ringinuse disabled) (realtime) (Invalid) has taken no calls yet (login was 2982 secs ago)
      PJSIP/500 (ringinuse disabled) (realtime) (Invalid) has taken no calls yet (login was 2982 secs ago)
      PJSIP/2000 (ringinuse disabled) (realtime) (Unavailable) has taken no calls yet (login was 2868 secs ago)
   No Callers
```

To make it work, you need to follow some rules:

1. The first column needs to be a primary key (PK). If there is no PK, it won't work.
2. Editing the fields to modify the order won't work. You need to delete, `queue show`, and then insert the members in the desired order to define a new order.

I'm glad you have found a way to work around the problem. It would be even better if there was a solution for ODBC.
I haven't checked yet if there are any disadvantages in using pgsql instead of ODBC.

Thank you very much @seanbright .
