### ISSUE TITLE
[bug]: crash when using switch => support in chan_iax2

### ISSUE THREAD

**Issue by 532910** [asterisk/asterisk#180]
### Severity

Trivial

### Versions

16.28 and later, including 20.3

### Components/Modules

iax2

### Operating Environment

debian, openwrt

### Frequency of Occurrence

Constant

### Issue Description

Steps to reproduce:
```
dialplan debug test
```
`extensions.conf`:
```Asterisk
[test]
switch => IAX2/test/tests
```

`iax.conf`:
```Asterisk
[general]
	bindaddr=0.0.0.0
	nochecksums=yes
	bandwidth=high
	autokill=yes

[test]
	disallow=all
	allow=alaw
	type=peer
	host=1.1.1.1
	secret=p
	trunk=yes
	context=*
```

`modules.conf `
```
[modules]
autoload=no
load => pbx_config
load => res_timing_timerfd
load => chan_iax2
```

`asterisk.conf`
```
[directories](!)
astetcdir => /etc/asterisk
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir => /var/lib/asterisk
astkeydir => /var/lib/asterisk
astdatadir => /usr/share/asterisk
astagidir => /usr/share/asterisk/agi-bin
astspooldir => /var/spool/asterisk
astrundir => /var/run/asterisk
astlogdir => /var/log/asterisk
astsbindir => /usr/sbin

[options]
verbose = 3
debug = 3
documentation_language = en_US
```

asterisk 16.16 debian bullseye works as expected:

```
bullseye*CLI> dialplan debug test

     In-mem exten Trie for Fast Extension Pattern Matching:


           Explanation: Node Contents Format = <char(s) to match>:<pattern?>:<specif>:[matched extension]
                        Where <char(s) to match> is a set of chars, any one of which should match the current character
                              <pattern?>: Y if this a pattern match (eg. _XZN[5-7]), N otherwise
                              <specif>: an assigned 'exactness' number for this matching char. The lower the number, the more exact the match
                              [matched exten]: If all chars matched to this point, which extension this matches. In form: EXTEN:<exten string>
                        In general, you match a trie node to a string character, from left to right. All possible matching chars
                        are in a string vertically, separated by an unbroken string of '+' characters.

[ Context 'test' created by 'pbx_config' ]

     No Pattern Trie present. Perhaps the context is empty...or there is trouble...


-= 1 context. =-
[Jun 29 09:26:46] WARNING[227521]: chan_iax2.c:14234 find_cache: Timeout waiting for cellgate/tests exten s
bullseye*CLI> 
```

asterisk 16.28 crashes:
```
bullseye*CLI> dialplan debug test

     In-mem exten Trie for Fast Extension Pattern Matching:


           Explanation: Node Contents Format = <char(s) to match>:<pattern?>:<specif>:[matched extension]
                        Where <char(s) to match> is a set of chars, any one of which should match the current character
                              <pattern?>: Y if this a pattern match (eg. _XZN[5-7]), N otherwise
                              <specif>: an assigned 'exactness' number for this matching char. The lower the number, the more exact the match
                              [matched exten]: If all chars matched to this point, which extension this matches. In form: EXTEN:<exten string>
                        In general, you match a trie node to a string character, from left to right. All possible matching chars
                        are in a string vertically, separated by an unbroken string of '+' characters.

bullseye*CLI> 
Disconnected from Asterisk server
Attempting to reconnect for 30 seconds
```

dmesg:
```
[Thu Jun 29 09:28:22 2023] asterisk[228129]: segfault at 920 ip 00005653828b8bd0 sp 00007fefee3d7e08 error 4 in asterisk[565382842000+1cf000]
[Thu Jun 29 09:28:22 2023] Code: 87 10 08 00 00 c3 0f 1f 40 00 48 8b 87 20 08 00 00 48 8b 97 28 08 00 00 c3 90 f3 0f 6f 06 0f 11 87 20 08 00 00 c3 0f 1f 40 00 <8b> 87 20 09 00 00 c3 66 0f 1f 84 00 00 00 00 00 89 b7 20 09 00 00
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by 532910** [comment]
I belive I have provided "Specific steps taken that lead to the crash" and "All configuration information necesary to reproduce the crash"

**Comment by jcolp** [comment]
You did not provide a backtrace, however, which is needed for crashes.

**Comment by 532910** [comment]
[core-asterisk-2023-06-29T08-49-10Z-thread1.txt](https://github.com/asterisk/asterisk/files/11903873/core-asterisk-2023-06-29T08-49-10Z-thread1.txt)
[core-asterisk-2023-06-29T08-49-10Z-locks.txt](https://github.com/asterisk/asterisk/files/11903874/core-asterisk-2023-06-29T08-49-10Z-locks.txt)
[core-asterisk-2023-06-29T08-49-10Z-info.txt](https://github.com/asterisk/asterisk/files/11903875/core-asterisk-2023-06-29T08-49-10Z-info.txt)
[core-asterisk-2023-06-29T08-49-10Z-full.txt](https://github.com/asterisk/asterisk/files/11903876/core-asterisk-2023-06-29T08-49-10Z-full.txt)
[core-asterisk-2023-06-29T08-49-10Z-brief.txt](https://github.com/asterisk/asterisk/files/11903879/core-asterisk-2023-06-29T08-49-10Z-brief.txt)

**Comment by jcolp** [comment]
Was Asterisk built as stated on the wiki page? The backtrace is lacking a lot of detail.

**Comment by 532910** [comment]
Oh sorry, I missed that.
I've re-run ast_coredumper with `DEBUGINFOD_URLS="https://debuginfod.debian.net"`
Could you say, is it fine now, or I still need to recompile it?
[core-asterisk-2023-06-29T09-12-09Z-thread1.txt](https://github.com/asterisk/asterisk/files/11904128/core-asterisk-2023-06-29T09-12-09Z-thread1.txt)
[core-asterisk-2023-06-29T09-12-09Z-locks.txt](https://github.com/asterisk/asterisk/files/11904129/core-asterisk-2023-06-29T09-12-09Z-locks.txt)
[core-asterisk-2023-06-29T09-12-09Z-info.txt](https://github.com/asterisk/asterisk/files/11904131/core-asterisk-2023-06-29T09-12-09Z-info.txt)
[core-asterisk-2023-06-29T09-12-09Z-full.txt](https://github.com/asterisk/asterisk/files/11904132/core-asterisk-2023-06-29T09-12-09Z-full.txt)
[core-asterisk-2023-06-29T09-12-09Z-brief.txt](https://github.com/asterisk/asterisk/files/11904133/core-asterisk-2023-06-29T09-12-09Z-brief.txt)

**Comment by jcolp** [comment]
It's now fine.
