### ISSUE TITLE
[bug]: (Reverse?) DNS lookup failure matching SIP peer on incoming call, possibly IPv6-related

### ISSUE THREAD

**Issue by madduck** [asterisk/asterisk#186]
### Severity

Minor

### Versions

16.28.0, 20.3.0

### Components/Modules

chan_sip

### Operating Environment

Debian stable, also Debian unstable (tested both), dual-stack (native IPv6), running versions `1:16.28.0~dfsg-0+deb11u3` and `1:20.3.0~dfsg+~cs6.13.40431413-1` respectively.

### Frequency of Occurrence

Frequent

### Issue Description

I have a peer:
```
[lehel-trunk-sipgate]
type=peer
host=sipconnect.sipgate.de
context=lehel-in-trunk-sipgate
[…]
```
and it appears fine:
```
*CLI> sip show peers
lehel-trunk-sipgate/159xx 2001:ab7::9                                 Auto (No)  Auto (No)      5060     OK (10 ms)
[…]
*CLI> sip show peer lehel-trunk-sipgate 
  * Name       : lehel-trunk-sipgate
  Context      : lehel-in-trunk-sipgate
  FromDomain   : sipconnect.sipgate.de Port 5060
  ToHost       : sipconnect.sipgate.de
  Addr->IP     : [2001:ab7::9]:5060
  […]
```
and associated register statement, as well as setting the default context:
```
[general](+)
context=unauthenticated

register => 123456789t1:s3cr3t@sipconnect.sipgate.de/incoming
```
also appear fine:
```
*CLI> sip show registry
sipconnect.sipgate.de:5060              N      159xxxxxt1          105 Registered           Tue, 04 Jul 2023 12:14:15
[…]
```

When a call comes in through the trunk, Asterisk 16.28.0 (Debian oldstable) and 20.3.0 (Debian unstable) don't route it to `incoming@lehel-in-trunk-sipgate`, which I would expect from the register statement, as well as the context definition in the peer stanza. Instead, they attempt to route the call to `incoming@unauthenticated`, i.e. in the default context (see log below)

It seems that the incoming call isn't matched up with the peer, but this used to work just fine.

After a bit of debugging, I found out that the problem seems to have started once the upstream provider either started to use IPv6, or added multiple `AAAA` records to its hostname:

```
% dig +short AAAA sipconnect.sipgate.de | while read i; do echo -n "$i: "; dig +short -x $i; done
2001:ab7::9:  sipconnect.sipgate.de.
2001:ab7::10: sipconnect.sipgate.de.
2001:ab7::12: sipconnect.sipgate.de.
2001:ab7::11: sipconnect.sipgate.de.
```

As you can see, they did it right and it's symmetrical. However, it seems that this is the issue preventing `chan_sip` from matching the peer to use.

If I add the following lines to the SIP peer stanza, then the issue *prevails*:

```
host=2001:ab7::9
host=2001:ab7::10
host=2001:ab7::11
host=2001:ab7::12
```

However, if I *remove* the hostname and just leave the four IPv6 lines, then the issue *goes away*.

Therefore, I assume there's something wrong with DNS or reverse DNS resolution. I.e. either Asterisks tries to get the `PTR` record off the incoming IPv6, and then fails to match it against the `host=sipconnect.sipgate.de` line, or Asterisk resolves the `AAAA` records of said hostname, but then doesn't match the incoming IPv6 against all of them.

As a matter of fact, it *sometimes* works, i.e. the failure isn't permanent. This leads me to speculate that maybe Asterisk resolves the `AAAA` and `A` records (which it receives unordered), but then matches the incoming IP only against the first. With 4 `AAAA` records and 4 associated IPv6 used for incoming traffic, this would mean that 1/16th of all calls get matched, whereas for the majority, the matching fails. But this is just speculations.

I have not yet tested what happens if I disable IPv6 altogether, because this issue is on a live system and I'd rather not mess around too much, but if it helps, I am happy to try.

Also hope I filed this properly, and didn't leave anything out.

### Relevant log output

```shell
== Using SIP RTP CoS mark 5
       > 0x7fbf4ceeb400 -- Strict RTP learning after remote address set to: [2001:ab7:2000::12]:19344
    -- Executing [4989xxxxxxxx@unauthenticated:1] NoOp("SIP/sipconnect.sipgate.de-00010eb5", "Unauthenticated request to 4989xxxxxxxx from "0177xxxxxxxx" <0177xxxxxxxx>") in new stack
    -- Executing [4989xxxxxxxxx@unauthenticated:3] Goto("SIP/sipconnect.sipgate.de-00010eb5", "incoming,4989xxxxxxxxx,1") in new stack
    -- Goto (incoming,4989xxxxxxxxx,1)
    -- Channel 'SIP/sipconnect.sipgate.de-00010eb5' sent to invalid extension: context,exten,priority=incoming,4989xxxxxxxxx,1
    -- Executing [i@incoming:1] NoOp("SIP/sipconnect.sipgate.de-00010eb5", "") in new stack
    -- Auto fallthrough, channel 'SIP/sipconnect.sipgate.de-00010eb5' status is 'UNKNOWN'
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
The chan_sip module is no longer supported or receiving changes (and in fact will not exist in the next major release), and has limitations which have been solved by chan_pjsip. For example chan_sip does not allow you to specify multiple hostnames for a peer, or have multiple resolved addresses. The recommendation is to move to the chan_pjsip module instead.
