### ISSUE TITLE
[new-feature]: sig_analog: Allow flash to time out to silent hold

### ISSUE THREAD

**Issue by InterLinked1** [asterisk/asterisk#205]
### Feature Description

Imported from https://issues.asterisk.org/jira/browse/ASTERISK-30004

Currently, if using simple switch (immediate=no and threewaycalling=yes), if you flash to get a recall dial tone, the dial tone will continue forever to allow using it as a "hold" feature.

To replicate the way some real CO switches handle this, this adds the ability to time out to a "silent hold". Rather than playing dial tone for potentially a while, this allows the dial tone to time out normally, but to silence as opposed to any kind of "permanent signal" condition. This allows the user to then have the call on hold be silent, if this is their actual intention, which is potentially much less annoying.

**Comment by InterLinked1** [comment]
@jcolp sig_analog is core supported, not extended supported, is this the right label?

**Comment by jcolp** [comment]
I've changed it to core.
