### ISSUE TITLE
[improvement]: Accumulating MWI subscriptions with subscribemwi=yes.

### ISSUE THREAD

**Issue by VolodyaIvanets** [asterisk/asterisk#213]
### Improvement Description

Hello!

Not sure it this is a bug of not but the current behavior does not look right. This was tested with Asterisk 18.16.

When the `subscribemwi` setting is set to `yes`, it appears that the new subscription with `Event: message-summary` do not override previous one and that Asterisk does not release expired subscriptions. `sip show subscriptions` shows only one subscription. But if there were 2 or more subscriptions, when there is a change in the VM box, Asterisk will be sending multiple NOTIFY requests. After a while number of NOTIFY requests will become very big.

In this example, Asterisk binds on port 5080.
![Subscriptions](https://github.com/asterisk/asterisk/assets/4404834/95251dc4-0225-4c4e-824d-f2e9e927ae05)

So far I found that only restart of Asterisk will clear these subscriptions. But eventually they will pile up again.

Please let me know what debug information should I provide if necessary.

Thanks a lot!

**Comment by jcolp** [comment]
We are no longer accepting bug reports for the chan_sip module. It has been deprecated and is effectively frozen, it has also been removed from Asterisk master and will not be in the next major release. The recommendation is to move to chan_pjsip which is core supported and the SIP channel driver going forward.
