### ISSUE TITLE
[bug]: Deadlock with MixMonitorMute AMI action

### ISSUE THREAD

**Issue by nikolaciprich** [asterisk/asterisk#233]
### Severity

Major

### Versions

18.18.0

### Components/Modules

mixmonitor, AMI

### Operating Environment

Centos Linux 7, x86_64

### Frequency of Occurrence

Constant

### Issue Description

Since 18.18.0, MixMonitorMute AMI action on recorded WebRTC call causes immediate deadlock. The call remains stuck, AMI stops working, PJSIP starts dropping registrations etc. asterisk cannot be restarted in regular way, needs to be killed by KILL signal. The problem seems to be caused by 03da795e3e0888bad059e98a764f02b83ec44b29, reverting the patch fixes the problem. I can reproduce it in 100% of cases, so I can provide further help with testing if needed.

### Relevant log output
See attached 233.txt file

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
[233.txt](https://github.com/asterisk/asterisk/files/12300064/233.txt)
