### ISSUE TITLE
[bug]: Syntax Error in SQL Code

### ISSUE THREAD

**Issue by celsoannes** [asterisk/asterisk#274]
### Severity

Minor

### Versions

Asterisk 20

### Components/Modules

postgresql_config.sql

### Operating Environment

Any version

### Frequency of Occurrence

Constant

### Issue Description

I am writing to report an issue I've encountered while working with SQL code. The problem is related to a syntax error that is preventing the execution of a specific ALTER TABLE statement. Here are the details:

I am trying to execute the following ALTER TABLE statement in my PostgreSQL database:

```sql
...
ALTER TABLE ps_endpoints ALTER COLUMN 100rel TYPE pjsip_100rel_values_v2 USING 100rel::text::pjsip_100rel_values_v2;
...
```

To resolve this issue, I have enclose the column name "100rel" in double quotes to treat it as an identifier rather than a keyword. The corrected version of the ALTER TABLE statement is as follows:
```sql
...
ALTER TABLE ps_endpoints ALTER COLUMN "100rel" TYPE pjsip_100rel_values_v2 USING "100rel"::text::pjsip_100rel_values_v2;
...
```

### Relevant log output

```shell
ERROR: syntax error at or near "TYPE"
LINE 1491: ALTER TABLE ps_endpoints ALTER COLUMN 100 TYPE pjsip_100rel_...
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by gtjoseph** [comment]
Interesting.  We'll take a look at how this is generated.

**Comment by gtjoseph** [comment]
This will be fixed with the next release.
