### ISSUE TITLE
[bug]:  [PJSIP] When transport fails to load, other transports are affected

### ISSUE THREAD

**Issue by kobaz** [asterisk/asterisk#293]
### Severity

Minor

### Versions

18,20,master

### Components/Modules

PJSIP

### Operating Environment

Debian

### Frequency of Occurrence

Constant

### Issue Description

- Have a transport that fails to load

### Reproduction

- I've now been able to reproduce this several times on demand

Have a working config/environment with three pjsip transports, udp, tcp, tls (in this order)
/etc/init.d/asterisk start
Edit /etc/asterisk/pjsip.conf, cause a transport to fail, like for example 'tls' by specifying a cert/key that doesn't exist
/etc/init.d/asterisk restart
Now pjsip behaves in a very broken way, including not respecting any nat or local_net settings on the two remaining transports that do load

### Cause/Effects
- Lockup? Or race condition issue?
- Wrong media address is used for remaining (properly loaded) transport
- Transports/media in general seem to be broken?  Outgoing media does not make it to the destination.  No audio in either direction upon handling an INVITE and recording/playing audio

So far the steps are:

### Relevant log output

**ip addr**
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether ee:8f:26:a8:fe:f1 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.191/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::ec8f:26ff:fea8:fef1/64 scope link
       valid_lft forever preferred_lft forever
```

**pjsip.conf**
```
[global]
type = global
endpoint_identifier_order=username,ip,anonymous

; Call comes in on this transport
[transport-udp]
type                       = transport
symmetric_transport        = yes
protocol                   = udp
bind                       = 0.0.0.0:5060
allow_reload               = no
tos                        = cs3
cos                        = 3
external_media_address     = 50.12.34.56
external_signaling_address = 50.12.34.56
external_signaling_port    = 5060
local_net                  = 192.168.1.0/24

[transport-tcp]
type                       = transport
symmetric_transport        = yes
protocol                   = tcp
bind                       = 0.0.0.0:5060
allow_reload               = no
tos                        = cs3
cos                        = 3
external_media_address     = 50.12.34.56
external_signaling_address = 50.12.34.56
external_signaling_port    = 5060
local_net                  = 192.168.1.0/24

[transport-tls]
type                       = transport
symmetric_transport        = yes
protocol                   = tls
bind                       = 0.0.0.0:5061
allow_reload               = no
tos                        = cs3
cos                        = 3
cert_file                  = /etc/asterisk/keys/asterisk.crt
priv_key_file              = /etc/asterisk/keys/asterisk.key
method                     = tlsv1_2
external_media_address     = 50.12.34.56
external_signaling_address = 50.12.34.56
external_signaling_port    = 5061
local_net                  = 192.168.1.0/24
```

**pjsip_wizard.conf**
```
[trunk-is-icp-cloud-sbc1]
type = wizard
remote_hosts = something.net
transport = transport-udp
sends_auth = yes
aor/max_contacts = 1
aor/qualify_frequency = 60
aor/qualify_timeout = 2000
aor/remove_existing = yes
endpoint/allow = ulaw
endpoint/context = trunkhandler_default
endpoint/direct_media = no
endpoint/disallow = all
endpoint/force_rport = no
endpoint/ice_support = no
endpoint/log_subscription_error = no
endpoint/rewrite_contact = no
endpoint/rtp_keepalive = 30
endpoint/rtp_symmetric = yes
endpoint/rtp_timeout = 60
endpoint/rtp_timeout_hold = 60
endpoint/send_connected_line = no
endpoint/send_pai = yes
endpoint/send_rpid = yes
endpoint/trust_connected_line = no
endpoint/trust_id_inbound = yes
endpoint/trust_id_outbound = yes
```

The below Console section is an invite from after making the following change to pjsip.conf and restarting Asterisk
```
[transport-tls]
-cert_file                  = /etc/asterisk/keys/asterisk.crt
-priv_key_file              = /etc/asterisk/keys/asterisk.key
+cert_file                  = /etc/asterisk/keys/asterisk.crt.does-not-exist
+priv_key_file              = /etc/asterisk/keys/asterisk.key.does-not-exist
```

**Console** 
```
vbox-markm-x64*CLI> pjsip set logger on
PJSIP Logging enabled

------> Below SIP UDP Source: Definitely an external... does NOT match any local_net
2023-09-01 23:19:35.558-0400] VERBOSE[30874]: <--- Received SIP request (1286 bytes) from UDP:167.98.76.54:5060 --->
INVITE sip:1181179609@50.12.34.56:5060 SIP/2.0
Via: SIP/2.0/UDP 167.98.76.54:5060;rport;branch=z9hG4bKPj81799458-1617-4e28-9dbb-fb1ed11952d0
From: "Intellasoft" <sip:1181207755@167.98.76.54>;tag=0f01683d-05f9-4609-a4c2-102dd5e6bde5
To: <sip:1181179609@50.12.34.56>
Contact: <sip:asterisk@167.98.76.54:5060>
Call-ID: b55f0b6c-1cac-45f8-9510-a5ad2505ebe1
CSeq: 30147 INVITE
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub, histinfo
Session-Expires: 1800
Min-SE: 90
P-Asserted-Identity: "Intellasoft" <sip:1181207755@167.98.76.54>
Remote-Party-ID: "Intellasoft" <sip:1181207755@167.98.76.54>;party=calling;privacy=off;screen=no
In-Reply-To: c0044042-8824-4af2-b15d-b5475f8fc758
Max-Forwards: 70
User-Agent: Asterisk PBX 18.18.0
Content-Type: application/sdp
Content-Length:   312

v=0
o=- 1933143761 1933143761 IN IP4 167.98.76.54     <------ Definitely an external... does NOT match any local_net
s=Asterisk
c=IN IP4 167.98.76.54
t=0 0
m=audio 16468 RTP/AVP 0 8 5 3 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:5 DVI4/8000
a=rtpmap:3 GSM/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:150
a=sendrecv

[2023-09-01 23:19:35.565-0400] VERBOSE[30844]: <--- Transmitting SIP response (461 bytes) to UDP:167.98.76.54:5060 --->
SIP/2.0 100 Trying
Via: SIP/2.0/UDP 167.98.76.54:5060;rport=5060;received=167.98.76.54;branch=z9hG4bKPj81799458-1617-4e28-9dbb-fb1ed11952d0
Call-ID: b55f0b6c-1cac-45f8-9510-a5ad2505ebe1
From: "Intellasoft" <sip:1181207755@167.98.76.54>;tag=0f01683d-05f9-4609-a4c2-102dd5e6bde5
To: <sip:1181179609@50.12.34.56>
CSeq: 30147 INVITE
Server: Asterisk PBX 18.18.0
Content-Length:  0

SIP/2.0 200 OK
Via: SIP/2.0/UDP 167.98.76.54:5060;rport=5060;received=167.98.76.54;branch=z9hG4bKPj81799458-1617-4e28-9dbb-fb1ed11952d0
Call-ID: b55f0b6c-1cac-45f8-9510-a5ad2505ebe1
From: "Intellasoft" <sip:1181207755@167.98.76.54>;tag=0f01683d-05f9-4609-a4c2-102dd5e6bde5
To: <sip:1181179609@50.12.34.56>;tag=e01f9347-2697-4a4b-a69a-5634c216649c
CSeq: 30147 INVITE
Server: Asterisk PBX 18.18.0
Contact: <sip:50.12.34.56:5060>
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub
Session-Expires: 1800;refresher=uac
Require: timer
Content-Type: application/sdp
Content-Length:   237

v=0
o=- 1933143761 1933143763 IN IP4 192.168.1.191  <----------------- ??????
s=Asterisk
c=IN IP4 192.168.1.191
t=0 0
m=audio 18136 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:150
a=sendrecv
```

-- Definitely coming in on the interface/port/transport we're expecting

```
tcpdump udp port 5060
IP 167.98.76.54.5060 > vbox-markm-x64.5060: SIP: INVITE sip:1181179609@50.12.34.56:5060 SIP/2.0
IP vbox-markm-x64.5060 > 167.98.76.54.5060: SIP: SIP/2.0 100 Trying
IP vbox-markm-x64.5060 > 167.98.76.54.5060: SIP: SIP/2.0 200 OK
IP 167.98.76.54.5060 > vbox-markm-x64.5060: SIP: ACK sip:50.12.34.56:5060 SIP/2.0
IP 167.98.76.54.5060 > vbox-markm-x64.5060: SIP: BYE sip:50.12.34.56:5060 SIP/2.0
IP vbox-markm-x64.5060 > 167.98.76.54.5060: SIP: SIP/2.0 200 OK
```

There is not much logging in res_pjsip_session.c regarding the decision making on whether or not to use external_media_address so I've went ahead and added logging for the current 18.18 decision making.

Comparing the configuration for functional transports, everything is identical between Asterisk loads from when pjsip loads normally, verus runs into an error loading the tls transport.  Despite the error in loading the tls transport, the loaded transports are identical, minus of course tls is no longer loaded in the second run.

This entire debug section originates from res_pjsip_nat.c/res_pjsip_session.c in session_outgoing_nat_hook()
The below is the result of the following debug statements running inside the 'if (sdp->conn) {' block of code

This is a log session from prior to 'breaking tls'
```
VERBOSE[29071] res_pjsip_nat.c: [transport-udp] (No Call-id) Request is being sent to NON-local address (192.81.237.20), Processing NAT manipulation (For outgoing: OK)
VERBOSE[29071] res_pjsip_nat.c: [transport-udp] (No Call-id) Re-wrote Contact URI port to 5060 (For outgoing: OK)
VERBOSE[29071] res_pjsip_session.c: [transport-udp] (No Call-id) session_outgoing_nat_hook For External Traffic
VERBOSE[29071] res_pjsip_session.c: [transport-udp] (No Call-id) &our_sdp_addr:                                          192.168.1.191
VERBOSE[29071] res_pjsip_session.c: [transport-udp] (No Call-id) &remote_sip_addr:                                       167.98.76.54
VERBOSE[29071] res_pjsip_session.c: [transport-udp] (No Call-id) transport_state->external_media_address                 50.12.34.56
VERBOSE[29071] res_pjsip_session.c: [transport-udp] (No Call-id) our_sdp_addr is localnet match?                         1
VERBOSE[29071] res_pjsip_session.c: [transport-udp] (No Call-id) ast_sip_transport_is_local (based on our_sdp_addr)?     1
VERBOSE[29071] res_pjsip_session.c: [transport-udp] (No Call-id) ast_sip_transport_localnets?                            1
VERBOSE[29071] res_pjsip_session.c: [transport-udp] (No Call-id) -- Setting external media address to 50.12.34.56
VERBOSE[29071] res_pjsip_session.c: [transport-udp] (No Call-id) -- Final: our_sdp_addr  50.12.34.56
```

The above is a good/proper call handle for nat

The below is this same area of the log after 'breaking tls'
```
  .
```
The above is conspicuously empty, because when the tls transport fails to load... *none* of the debugs print from pjsip_nat or pjsip_session after accepting a call

After fixing transport-tls and allowing it to load correctly, now we have the correct SDP using external_media_address
```
  o=- 439311020 439311022 IN IP4 50.12.34.56
```

_No response_

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Embedding code like this is a mess. If you HAVE to embed code in your issue, which you shouldn't because licensing, then there's a code block to use. As it is right now I'm not going to try to clean up that mess.

The code as it is written already is correct for what it is trying to achieve. It's trying to handle the scenario where direct media is in use resulting in non-local IP address information going in the SDP. In that case you only want to rewrite the local SDP if the IP address present in the SDP is that of the local system. Using the remote IP address of the SIP packet may work sometimes but may not work other times because traffic can be local but SDP can reference non-local. It's using local_net currently to make the determination for whether it should happen or not. It's not working for you because you don't put the network that the system itself is on in the configuration as a local_net, while everyone else I've encountered does.

The patch you've provided is not correct and will not be accepted if put up for PR.

If you come up with an improvement and put it up as a PR that covers the direct media scenario and the fact that the signaling target IP address can differ from that of the SDP IP address, then it'll be reviewed, but I repeat: the changes you've provided already above will not be accepted.

**Comment by jcolp** [comment]
I also don't know what you mean by:

"But then this means that ANY and ALL traffic that's being responded to on this transport will always use external_media_address... this is backwards!?"

Because that's not true, the way it works:

1. If local_net is defined and the target IP address is within the configured local_net then stop and do nothing
2. Update the SIP message with the external_signaling_address information
3. If the SIP message contains SDP and the SDP IP address information is local update the SIP message with the external_media_address

SDP is only touched if 1 determines it is within local_net, so it's not updated for "ANY and ALL traffic".

**Comment by kobaz** [comment]
I fixed up all the formatting.
And, wow, thank you a million percent for checking into this on a holiday weekend.

Thank you for the incredibly thorough review here.  So it must be something else that's causing my ongoing nat issues then, because even with defining the local_net to include the local interface, it still in many situations sends out the wrong media address for SDP, so it must be something else now.  I'm going to keep digging and update the ticket/patch.

Also... I'm not sure what the license issue with putting code snippets on a ticket?  How is this different than a PR?

Please don't rush on any reply.. have a good weekend!

**Comment by jcolp** [comment]
A PR has a specific workflow that shows license status as part of it. License status doesn't exist on issues, unless an admin manually goes and checks the CLA database.

**Comment by kobaz** [comment]
I figured out some more elements of this flow and more functionally to explain why the fix isn't the proper fix.

This hook in question: session_outgoing_nat_hook() in res_pjsip_session.c looks like it only executes if the endpoint you're talking to does not match a local_net, so by this point the local_net handling has been already done.

So the comment I wrote 'any and all traffic' would actually only apply to traffic that's already been vetted through the first round of local_net checks.

**Comment by intellasoft** [comment]
In regards to:
: As well, in your original issue you did not state that even with local_net being set it still sometimes was incorrect. You made it sound as if doing that fixed the problem always.

In regards to:
> As well, in your original issue you did not state that even with local_net being set it still sometimes was incorrect. You made it sound as if doing that fixed the problem always.

This is also a moving-target, still investigating this issue.  Originally it looked like it fixed the issue but there's more going on I'm finding out.

New findings:
- Lockup or race condition issue
- I've now been able to reproduce this 3 times on demand
- Add server's own ip to local_net
- Have a transport that fails to load

Result:
- Wrong media address is used
- Transports in general seem to be broken? One example I find so far is that outgoing media is not working if this situation arises

I'll update the entire ticket/issue with details and reproduction as soon as I can.

So far the steps are:
- Have a working config/environment with three pjsip transports, udp, tcp, tls (in this order)
- /etc/init.d/asterisk start
- Edit /etc/asterisk/pjsip.conf, cause a transport to fail, like for example 'tls' by specifying a cert/key that doesn't exist
- /etc/init.d/asterisk restart
- Now pjsip  behaves in a very broken way, including not respecting any nat or local_net settings on the two remaining transports that do work

**Comment by Tinet-mucw** [comment]
The definition of "localnet" should include the network interface IP address 10.200.6.250; otherwise, the media address in the SDP won't be replaced with the public IP address.

code in res/res_pjsip_sdp_rtp.c
	/* Reversed check here. We don't check the remote endpoint being
	 * in our local net, but whether our outgoing session IP is
	 * local. If it is not, we won't do rewriting. No localnet
	 * configured? Always rewrite. */
	if (ast_sip_transport_is_nonlocal(transport_state, &our_sdp_addr) && transport_state->localnet) {
		return;
	}
	ast_debug(5, "Setting media address to %s\n", ast_sockaddr_stringify_addr_remote(&transport_state->external_media_address));
	pj_strdup2(tdata->pool, &stream->conn->addr, ast_sockaddr_stringify_addr_remote(&transport_state->external_media_address));

**Comment by jcolp** [comment]
@kobaz Is this still in a state of flux/investigation?

**Comment by kobaz** [comment]
All set.  Confirmed issue.

**Comment by jcolp** [comment]
Well, I can say that using the given instructions I'm unable to reproduce the issue.

**Comment by jcolp** [comment]
Correct.

**Comment by kobaz** [comment]
Okay I'll dig some more.  Thanks.   I'll work on getting an every-single-time reproduction.  From my notes it happens randomly.
