### ISSUE TITLE
[bug]: Impossible to use both analogue phones and softphones

### ISSUE THREAD

**Issue by joergent** [asterisk/asterisk#296]
### Severity

Major

### Versions

unknown

### Components/Modules

unknown

### Operating Environment

IOPSYS for Genexis ED500 router

### Frequency of Occurrence

Constant

### Issue Description

Apparently the version used in the Genexis ED500 router
PURE-ED500-KVIKNET-4.3.6.132-R has a problem with VoIP preventing the use of softphones eg. Zoiper or MizuDROID because a bad algorithm is used.

The case is the following:
The VoIP module will ACCEPT a call from the SIP server BEFORE any analogue phone is picked up, and not when there actually is somebody answering the call. After a timeout, the caller will get a not answered response.
This has as a consequence, that the subscriber will not be able to answer a call by using a mobile phone app, e.g. when on the road away from the analogue phones.
This is not the behaviour found in e.g. CISCO VoIP products which are working seamlessly with phone apps and analogue phones. 
The ED500 is effectively preventing the use of softphone apps togther with analogue phones.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
I'm not sure what this has to do with the Asterisk project?

**Comment by joergent** [comment]
I am not sure either, but I understand Asterisk to be the VoIP engine of IOPSYS used in the ED500

**Comment by jcolp** [comment]
The Asterisk project has no involvement in such a thing and does not control/configure/implement it. Asterisk is a toolkit that can be used to do many things, but ultimately it is not up to the project how it is used/configured. There's nothing we can do regarding it.
