### ISSUE TITLE
[bug]: When the wstransport has already been destroyed, calling ws_send_msg results in a crash.

### ISSUE THREAD

**Issue by Tinet-mucw** [asterisk/asterisk#299]
### Severity

Trivial

### Versions

18.10

### Components/Modules

res_pjsip

### Operating Environment

Linux iZuf67kmhbx3ciojdopm9lZ 4.19.43-13.2.al7.x86_64 #1 SMP Tue Jun 18 23:05:54 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

### Frequency of Occurrence

Occasional

### Issue Description

I have established a WebSocket connection where no SIP messages are sent for the first 32 seconds. Then, the idle_sched_cb validation finds monitored->sip_received to be 0, and consequently, it calls pjsip_transport_shutdown(monitored->transport);. Before the transport is destroyed, my WebSocket connection sends a registration request, or rather, it has already sent the request but hasn't yet executed idle_monitor_on_rx_request to set idle_trans->sip_received = 1. In either scenario, the transport gets destroyed before the platform can respond with a 401, which leads to a crash when trying to send the 401 response. The relevant log information is as follows:

```shell
[Aug 30 09:03:16] VERBOSE[16606] res_http_websocket.c: WebSocket connection from '140.205.117.91:62523' for protocol 'sip' accepted using version '13'   
[Aug 30 09:03:48] NOTICE[14368] res_pjsip/pjsip_transport_management.c: Shutting down transport 'WSS to 140.205.117.91:62523' since no request was received in 32 seconds   
[Aug 30 09:03:48 ERROR[29140] res_http_websocket.c: Error reading from web socket: Success   
[Aug 30 09:03:48] VERBOSE[16606] res_http_websocket.c: WebSocket connection from '140.205.117.91:62523' closed   
```

The stack trace is as follows, and I believe that wstransport has already been destroyed:

```shell
(gdb) f 1   
#1  0x00007f77fd110e5a in ws_send_msg (transport=0x7f77d424ea48, tdata=0x7f775c27a648, rem_addr=0x7f773a1b8b58, addr_len=28,    
    token=0x7f775c27a648, callback=0x7f786fbe962f <transport_send_callback>) at res_pjsip_transport_websocket.c:73   

73      res_pjsip_transport_websocket.c: No such file or directory.   
(gdb) p *transport   
$3 = {obj_name = "\240/\206\324w\177\000\000d424ea48-487", '\000' <repeats 11 times>, pool = 0x7f77c4725ff0, 
  ref_cnt = 0x7f77c4726098, lock = 0x7f77c47260f0, grp_lock = 0x0, tracing = 0, is_shutdown = 1, is_destroying = 1, key = {
    type = 12, rem_addr = {addr = {sa_family = 2}, ipv4 = {sin_family = 2, sin_port = 15348, sin_addr = {s_addr = 1534446988}, 
        sin_zero = "\000\000\000\000\000\000\000"}, ipv6 = {sin6_family = 2, sin6_port = 15348, sin6_flowinfo = 1534446988, 
        sin6_addr = {s6_addr = '\000' <repeats 15 times>, u6_addr32 = {0, 0, 0, 0}}, sin6_scope_id = 0}}}, 
  type_name = 0x7f77fd1125c5 "WSS", flag = 3, info = 0x7f77c4726160 "WSS to 140.205.117.91:62523", addr_len = 16, local_addr = {
    addr = {sa_family = 2}, ipv4 = {sin_family = 2, sin_port = 47873, sin_addr = {s_addr = 2819628972}, 
      sin_zero = "\000\000\000\000\000\000\000"}, ipv6 = {sin6_family = 2, sin6_port = 47873, sin6_flowinfo = 2819628972, 
      sin6_addr = {s6_addr = '\000' <repeats 15 times>, u6_addr32 = {0, 0, 0, 0}}, sin6_scope_id = 0}}, local_name = {host = {
      ptr = 0x7f77c4726180 "172.31.16.168\177", slen = 13}, port = 443}, remote_name = {host = {ptr = 0x0, slen = 0}, port = 0}, 
  dir = PJSIP_TP_DIR_INCOMING, endpt = 0x3388738, tpmgr = 0x35b2688, factory = 0x0, idle_timer = {user_data = 0x7f77d424ea48, 
    id = 0, cb = 0x7f786fbe9b35 <transport_idle_callback>, _timer_id = -1}, last_recv_ts = {u32 = {lo = 3241428826, 
      hi = 18179020}, u64 = 78078299614758746}, last_recv_len = 928, data = 0x0, send_msg = 0x7f77fd110deb <ws_send_msg>, 
  do_shutdown = 0x0, destroy = 0x7f77fd110e6c <ws_destroy>}
(gdb) p *((struct astobj2 *) ((char *) transport - sizeof(struct astobj2)))   
$4 = {priv_data = {destructor_fn = 0x7f77d4000800, weakptr = 0x7f77d4617e80, ref_counter = -731604080, options = 7, lockused = 0, 
    magic = 2039}, user_data = 0x7f77d424ea48}
(gdb) p *transport->ref_cnt
$7 = {mutex = 0x0, value = 3}
 ```
    
When calling ws_send_msg, how can I determine if the wstransport has already been destroyed? I think that accessing wstransport->is_shutdown is not advisable if the wstransport has already been destroyed.
    
    
    
[core-asterisk-2023-08-30T01-03-48Z-info.txt](https://github.com/asterisk/asterisk/files/12520825/core-asterisk-2023-08-30T01-03-48Z-info.txt)
[core-asterisk-2023-08-30T01-03-48Z-locks.txt](https://github.com/asterisk/asterisk/files/12520826/core-asterisk-2023-08-30T01-03-48Z-locks.txt)
[core-asterisk-2023-08-30T01-03-48Z-full.txt](https://github.com/asterisk/asterisk/files/12520829/core-asterisk-2023-08-30T01-03-48Z-full.txt)

[core-asterisk-2023-08-30T01-03-48Z-brief.txt](https://github.com/asterisk/asterisk/files/12520830/core-asterisk-2023-08-30T01-03-48Z-brief.txt)
[core-asterisk-2023-08-30T01-03-48Z-thread1.txt](https://github.com/asterisk/asterisk/files/12520832/core-asterisk-2023-08-30T01-03-48Z-thread1.txt)

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
It appears the bug you have submitted is against a rather old version of a supported branch of Asterisk. There have been many issues fixed between the version you are using and the current version of your branch. Please test with the latest version in your Asterisk branch and report whether the issue persists.

**Comment by Tinet-AaronAn** [comment]
@Tinet-mucw You can try the lastest asterisk version and replicate this problem.

**Comment by Tinet-mucw** [comment]
When establishing a WebSocket connection, the transport's ao2 reference count and the transport's pjsip reference count are both equal to 2. After establishing the WebSocket connection, if no messages are sent within 32 seconds, it triggers the idle_sched_cb, and then executes pjsip_transport_shutdown. After this is executed, both the transport's pjsip reference count and ao2 reference count become 0.

However, if any SIP messages are received during the execution of pjsip_transport_shutdown, it leads to a crash.

The provided PJSIP patch seems to be related to the issue, and it includes the following code changes:

```shell
diff --git a/pjsip/src/pjsip/sip_transport.c b/pjsip/src/pjsip/sip_transport.c
index fb4e1c9..f23df65 100644
--- a/pjsip/src/pjsip/sip_transport.c
+++ b/pjsip/src/pjsip/sip_transport.c
@@ -2142,6 +2142,7 @@ PJ_DEF(pj_ssize_t) pjsip_tpmgr_receive_packet( pjsip_tpmgr *mgr,
            goto finish_process_fragment;
        }
 
+       pjsip_transport_shutdown(rdata->tp_info.transport);
        /* For request: */
        if (rdata->msg_info.msg->type == PJSIP_REQUEST_MSG) {
            /* always add received parameter to the via. */
```

The difference between this situation and the actual situation appears to be related to the placement of the pjsip_transport_shutdown function call.

I have checked the 18.10 and master versions of the Asterisk code and found no changes related to this issue. Additionally, you noted that WebSocket's SIP message reading do not verify the transport state.
