### ISSUE TITLE
[bug]: hangup after beep to avoid waiting for timeout

### ISSUE THREAD

**Issue by mbradeen** [asterisk/asterisk#325]
### Severity

Trivial

### Versions

18,20,21,master,certified/18.9

### Components/Modules

func_periodic_hook

### Operating Environment

all

### Frequency of Occurrence

None

### Issue Description

CY Submission - hangup after beep to avoid waiting for timeout

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by gtjoseph** [comment]
@mbradeen Might want to add a title to this issue :)
