### ISSUE TITLE
[improvement]: Add libjwt to third-party

### ISSUE THREAD

**Issue by gtjoseph** [asterisk/asterisk#349]
### Improvement Description

The current STIR/SHAKEN implementation is not currently usable due to encryption issues.  Rather than trying to futz with OpenSSL and the the current code, we can take advantage of the existing capabilities of libjwt but we first need to add it to the third-party infrastructure already in place for jansson and pjproject.

**Comment by seanbright** [comment]
Please describe the “encryption issues.”

**Comment by gtjoseph** [comment]
> Please describe the “encryption issues.”

I'm not going to get this exactly right but here goes...

STIR/SHAKEN depends JSON Web Tokens for encapsulation and on EC/ecdsa for signatures.  Normally a EC signature produced by OpenSSL has the (R,S) values prepended to the signature but S/S requires a "raw" signature.  Stripping the (R,S) from the signature is not a simple matter of chopping the first 8 bytes off though. To get it right, we'd have to implement the same code that's already in [benmcollins/libjwt](https://github.com/benmcollins/libjwt).  We also did our own implementation of JWT for res_stir_shaken which is somewhat fragile so moving to libjwt kills two birds with one stone.  libjwt is also used by [libstirshaken](https://github.com/signalwire/libstirshaken) which is used by freeswitch.  libstirshaken is basically a plumbing layer a UA can use but since we already have the plumbing in place, we don't need that layer.


References:
https://stackoverflow.com/questions/44807170/openssl-ecdsa-signatures-longer-than-expected
https://www.google.com/search?q=ecdsa+signatue+64+vs+71+bytes&sourceid=chrome&ie=UTF-8
