### ISSUE TITLE
[improvement]: Refactor res_stir_shaken to use libjwt

### ISSUE THREAD

**Issue by gtjoseph** [asterisk/asterisk#351]
### Improvement Description

res_stir_shaken has encryption issues that can be fixes more easily by using libjwt than by futzing with the code and OpenSSL. 

See also: #349

**Comment by seanbright** [comment]
Please describe the “encryption issues.”

**Comment by gtjoseph** [comment]
> Please describe the “encryption issues.”

Answered in https://github.com/asterisk/asterisk/issues/349#issuecomment-1734316804
