### ISSUE TITLE
[improvement]: Update documentation for CHANGES/UPGRADE files

### ISSUE THREAD

**Issue by kobaz** [asterisk/asterisk#360]
### Improvement Description

Problem: Traditionally modifications to CHANGES or UPGRADE would each go into their respective directories as an individual text file.  Current CHANGES/UPGRADE files include old instructions on how to modify said files.

Solution:
Update the documentation header in these two files to point to the wiki

**Comment by jcolp** [comment]
> FYI this change broke the link referenced in the following wiki page: https://docs.asterisk.org/Asterisk_20_Documentation/WhatsNew/

For documentation things, please open an issue in the documentation repo referencing this.
