### ISSUE TITLE
[bug]: pjproject download link during installation is getting stuck

### ISSUE THREAD

**Issue by sandeepshindeit** [asterisk/asterisk#367]
### Severity

Blocker

### Versions

20

### Components/Modules

prproject

### Operating Environment

linux ubuntu

### Frequency of Occurrence

None

### Issue Description

This pjproject 2.13.1 is the link is down or not getting downloaded and hence the instllation of asterisk is not working

**https://raw.githubusercontent.com/asterisk/third-party/master/pjproject/2.13.1/pjproject-2.13.1.tar.bz2**, below is the log where the installation is getting stuck

configure: checking OPENSSL with pkg-config
configure: checking whether system openssl > 1.1.0
checking for OPENSSL... yes
checking for embedded pjproject (may have to download)... configuring
[pjproject] Downloading https://raw.githubusercontent.com/asterisk/third-party/master/pjproject/2.13.1/pjproject-2.13.1.tar.bz2 to /tmp/pjproject-2.13.1.tar.bz2

tried other methods by download offline and giving path, we tried
$ mkdir /tmp/downloads
$ wget -O /tmp/downloads/pjproject-2.6.tar.bz2 http://www.pjsip.org/release/2.6/pjproject-2.6.tar.bz2
$ wget -O /tmp/downloads/pjproject-2.6.md5 http://www.pjsip.org/release/2.6/MD5SUM.txt

we also tried below
Run ./configure with the --with-externals-cache=/tmp/downloads option. ./configure will check there first and only download if the files aren't already there or the tarball checksum doesn't match what's in the md5 file. This is similar to the --with-sounds-cache option. BTW, the --with-externals-cache mechanism works for the precompiled codecs and the Digium Phone Module for Asterisk as well. As of Asterisk 13.18, 14.7 and 15.0, the --with-download-cache option can be used to specify both the externals and sounds cache directory.
Set the PJPROJECT_URL environment variable to any valid URL (including file:// URLs) where ./configure can find the tarball and checksum files. The variable can be set in your environment and exported or specified directly on the ./configure command line. As of Asterisk 13.18, 14.7 and 15.0, the AST_DOWNLOAD_CACHE environment variable can be used to specify both the externals and sounds cache directory.

but nothing seems to be working and stop and download only

### Relevant log output

```shell
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for RAII support... checking for gcc -fnested-functions... no
checking for clang strsep/strcmp optimization... no
configure: checking OPENSSL with pkg-config
configure: checking whether system openssl > 1.1.0
checking for OPENSSL... yes
checking for embedded pjproject (may have to download)... configuring
[pjproject]  Downloading https://raw.githubusercontent.com/asterisk/third-party/master/pjproject/2.13.1/pjproject-2.13.1.tar.bz2 to /tmp/pjproject-2.13.1.tar.bz2
[pjproject]  Retrying download
[pjproject]  Downloading https://raw.githubusercontent.com/asterisk/third-party/master/pjproject/2.13.1/pjproject-2.13.1.tar.bz2 to /tmp/pjproject-2.13.1.tar.bz2
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
We appreciate the difficulties you are facing, however this does not appear to be a bug report and your request or comments would be better served in a different forum.

The Asterisk community provides support over IRC, mailing lists, and forums as described at http://asterisk.org/community. The Asterisk issue tracker is used specifically to track issues concerning bugs and documentation errors.
