### ISSUE TITLE
[Bug]: contrib/scripts/install_prereq tries to install armhf packages on aarch64 Debian platforms

### ISSUE THREAD

**Issue by jxmx** [asterisk/asterisk#37]
### Severity

Trivial

### Versions

20

### Components/Modules

contrib

### Operating Environment

Debian 11 on aarch64/arm64 platforms. 'uname -m' = aarch64

### Frequency of Occurrence

Constant

### Issue Description

When looking to install prerequisites and their dependencies, the current logic attempts to force-install 32-bit armhf binaries on 64-bit aarch/arm64 platforms. This is a result of using aptitude in `contrib/scripts/install_prereq`.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
The actions config is mistakenly marking open stuff as stale, so I've removed the label.
