### ISSUE TITLE
[bug]: Asterisk stops responding to SIP INVITES

### ISSUE THREAD

**Issue by dovi5988** [asterisk/asterisk#373]
### Severity

Trivial

### Versions

20.2.0

### Components/Modules

musiconhold

### Operating Environment

Using Debian 12 on an ESXI box. We are using Asterisk 20.2.0 with DEBUG_THREADS enabled on the Asterisk build. Asterisk was built from source. We are using PJSIP.

### Frequency of Occurrence

Frequent - Every few days.

### Issue Description

The boxes are mainly used to play audio streams with musicnold (with ffmpeg) as well as playing audio files via http. Every few days the boxes simply stop responding to SIP INVITES. It seems there may be a fd leak somewhere. 

### Relevant log output

```shell
I compressed the the dump file as I believe it was a few gigs.
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by dovi5988** [comment]
[core-asterisk-running-2023-10-09T05-12-49Z-brief.txt](https://github.com/asterisk/asterisk/files/12860628/core-asterisk-running-2023-10-09T05-12-49Z-brief.txt)
[core-asterisk-running-2023-10-09T05-12-49Z-full.txt](https://github.com/asterisk/asterisk/files/12860629/core-asterisk-running-2023-10-09T05-12-49Z-full.txt)
[core-asterisk-running-2023-10-09T05-12-49Z-info.txt](https://github.com/asterisk/asterisk/files/12860630/core-asterisk-running-2023-10-09T05-12-49Z-info.txt)
[core-asterisk-running-2023-10-09T05-12-49Z-locks.txt](https://github.com/asterisk/asterisk/files/12860631/core-asterisk-running-2023-10-09T05-12-49Z-locks.txt)
[core-asterisk-running-2023-10-09T05-12-49Z-thread1.txt](https://github.com/asterisk/asterisk/files/12860632/core-asterisk-running-2023-10-09T05-12-49Z-thread1.txt)

**Comment by jcolp** [comment]
According to the provided information, nothing is deadlocked or blocking. The system shows to be idle. Does a packet capture on the system confirm the traffic is being received on the system itself? What behavior do you see that made you say it was an fd leak? Is there console output?

**Comment by dovi5988** [comment]
I was using sngrep. It showed packets coming in and asterisk not responding. In the Asterisk logs there was nothing other than the ongoing calls. One more item that may be noteworthy. There were two calls that were long over (my carriers limit me on max time) and the calls were going for 24+ hours.

My thoughts for thinking there was a fd leak was based on the output of ``` lsof | egrep 'asterisk.*STREAM \(CONNECTED' | wc -l ``` and the output of ```cat /proc/$(pidof asterisk)/limits```. Currently on these two boxes I am seeing
```
dovid@a15-c3:~# lsof | egrep 'asterisk.*STREAM \(CONNECTED' | wc -l
600
dovid@a15-c3:~# 
```
and
```
dovid@a14-c3:~# lsof | egrep 'asterisk.*STREAM \(CONNECTED' | wc -l
194
root@a14-c3:~# 
```

so it looks OK now. I have also upgraded one of the boxes from 20.2.0 to 20.4.0 and I have built it with DONT_OPTIMIZE and DEBUG_FD_LEAKS so maybe we will have more. I also open to leaving the box up once it breaks and give you ssh access if you would like to poke around.

**Comment by jcolp** [comment]
What ongoing calls and how did you determine them? A file descriptor leak would not stop Asterisk from responding to SIP INVITE requests. It's unlikely to be the cause.

**Comment by jcolp** [comment]
Well, assuming UDP is in use. What transport is in use for the SIP traffic? Does the traffic appear in "pjsip set logger on"?

**Comment by dovi5988** [comment]
@jcolp Using USP with PJSIP. I have never checked with "pjsip set logger on". I have it enabled now and I will report back the next time it happens.

**Comment by dovi5988** [comment]
I updated from 20.2.0 to 20.4.0 and so far I have not been able to re-produce. I am going to wait a few more days if it does not happen I will close this out.

**Comment by dovi5988** [comment]
@jcolp It just happened again. In the logs I am seeing:

```
[2023-10-22 21:09:27] DEBUG[3631036] res_pjsip/pjsip_distributor.c: Could not find matching transaction for Request msg OPTIONS/cseq=10 (rdata0x14609df50dc8)
[2023-10-22 21:09:27] DEBUG[3631036] res_pjsip/pjsip_distributor.c: Taskprocessor overload alert: Ignoring 'Request msg OPTIONS/cseq=10 (rdata0x14609df50dc8)'.
```
Is this a config issue and not a bug?

**Comment by jcolp** [comment]
Generally taskprocessor overloads are not a bug. You can do "core show taskprocessors" to see the current state of taskprocessors and which one overloaded, which can then provide insight into what exactly happened. PJSIP can also be configured[1] to only respect overloads regarding its own taskprocessors, or disabled entirely.

[1] https://docs.asterisk.org/Asterisk_20_Documentation/API_Documentation/Module_Configuration/res_pjsip/#taskprocessor_overload_trigger

**Comment by dovi5988** [comment]
@jcolp Considering that this is not a bug I am going to close it here and follow up on the Asterisk forums.
