### ISSUE TITLE
[bug]: INFO required in SIP allow for out of band DTMF with Polycom

### ISSUE THREAD

**Issue by elihunter** [asterisk/asterisk#376]
### Severity

Trivial

### Versions

18.19.0

### Components/Modules

chan_pjsip

### Operating Environment

Debian 11

### Frequency of Occurrence

None

### Issue Description

Trying to get direct media working with Polycom phones but when setting a PJSIP endpoint to info for DTMF the Polycom does not send SIP INFO packets.  

Each time a button is pressed on the Polycom during a call the following is logged on the Polycom "MsgPpsDtmfViaInfo Rejected” and no dtmf info packet is sent from the phone.  I confirmed a Yealink phone and Microsip softphone both work with DTMF set to info.

It looks like INFO needs to be added to the allow field in order for this to work with Polycoms.

### Relevant log output

```shell
Blockquote │SIP/2.0 200 OK
76.103.166.166:1030 xxx.xxx.x.xxx:5060│Via: SIP/2.0/UDP 192.168.1.23;rport=1030;received=76.103.166.166;branch=z9hG4bK5afdd480D69E6673
──────────┬───────── ──────────┬─────────│Call-ID: c9cbd6015dc47176667e92ddbf7461ef
12:41:25.352059 │ INVITE (SDP) │ │From: “101” sip:101@xxx.xxx.x.xxx;tag=904B6CF4-83A17067
+0.002049 │ ──────────────────────────> │ │To: sip:*97@xxx.xxx.x.xxx;user=phone;tag=3a497ad2-e0a3-41cc-83bf-34cec7fb3e52
12:41:25.354108 │ 401 Unauthorized │ │CSeq: 2 INVITE
+0.030803 │ <────────────────────────── │ │Server: PBX
12:41:25.384911 │ ACK │ │Contact: sip:xxx.xxx.x.xxx:5060
+0.006061 │ ──────────────────────────> │ │Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE,
12:41:25.390972 │ INVITE (SDP) │ │EFER
+0.001628 │ ──────────────────────────> │ │Supported: 100rel, timer, replaces, norefersub
12:41:25.392600 │ 100 Trying │ │Content-Type: application/sdp
+0.014570 │ <────────────────────────── │ │Content-Length: 238
12:41:25.407170 │ 200 OK (SDP) │ │
+0.027980 │ <────────────────────────── │ │v=0
12:41:25.435150 │ ACK │ │o=- 1697143284 1697143286 IN IP4 xxx.xxx.x.xxx
+3.508595 │ ──────────────────────────> │ │s=Asterisk
12:41:28.943745 │ BYE │ │c=IN IP4 xxx.xxx.x.xxx
+0.001586 │ ──────────────────────────> │ │t=0 0
12:41:28.945331 │ 200 OK │ │m=audio 11014 RTP/AVP 102 0
│ <────────────────────────── │ │a=rtpmap:102 G7221/16000
│ │ │a=fmtp:102 bitrate=32000
│ │ │a=rtpmap:0 PCMU/8000
│ │ │a=ptime:20
│ │ │a=maxptime:80
│ │ │a=sendrecv
│ │ │
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by nwf** [comment]
See also https://community.asterisk.org/t/asterisk-pjsip-using-sip-info/88422/6 ; this is long-standing defect.

**Comment by seanbright** [comment]
You could try https://github.com/asterisk/asterisk/compare/master...seanbright:asterisk:issue-376

It feels too trivial to be correct which is why I am hesitant to create a PR for it.

**Comment by elihunter** [comment]
> You could try applying [master...seanbright:asterisk:issue-376](https://github.com/asterisk/asterisk/compare/master...seanbright:asterisk:issue-376)
> 
> It feels too trivial to be correct which is why I am hesitant to create a PR for it.

Well I just gave it a try with 18.19.0 and have it working with a Polycom now.  Thank you!
