### ISSUE TITLE
[bug]: lost connection with chrome if dtls_rekey is used

### ISSUE THREAD

**Issue by burmancomp** [asterisk/asterisk#378]
### Severity

Trivial

### Versions

20.5.0

### Components/Modules

pjsip

### Operating Environment

asterisk is running on debian 11, workstation windows 10 22h2, chrome windows version is 119 beta.

### Frequency of Occurrence

Constant

### Issue Description

If dtls_rekey is for example 10, connection hangs up approximately after that time. With firefox issue does not occur.  Bug is quite long-standing.

### Relevant log output

```shell
[Oct 18 23:21:13] ERROR[222037][C-00000001] res_rtp_asterisk.c: DTLS failure occurred on RTP instance '0x7f4d3407ee80' due to reason 'sslv3 alert unexpected message', terminating
[Oct 18 23:21:13] WARNING[222037][C-00000001] res_rtp_asterisk.c: RTP Read error: Unspecified.  Hanging up.
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Please attach a packet capture of the renegotiation attempt so the actual DTLS messages can be seen, including the alert that is likely coming from Chrome.

**Comment by burmancomp** [comment]
I am not familiar with capturing network traffic so let me know if this is not what you need. 
[dtlscapture.txt](https://github.com/asterisk/asterisk/files/13043060/dtlscapture.txt)

**Comment by seanbright** [comment]
> let me know if this is not what you need

It's not. However you generated that file, do it again but this time save the result to a `.pcap` file instead of a text file.

**Comment by burmancomp** [comment]
Hopefully it is appropriate now.

[dtlscapture.dmp](https://github.com/asterisk/asterisk/files/13046134/dtlscapture.dmp)

**Comment by jcolp** [comment]
You've stated that this bug is "quite long-standing". Are you referring to it occurring across multiple versions of Chrome as well? From an Asterisk side there isn't much we do, except ask OpenSSL to renegotiate, and I'm not sure if I've ever heard of other platforms doing this with Chrome (searching didn't present anything including issue reports) so I'm wondering if this is not supported on the Chrome side, and since rekey is not enabled for our WebRTC functionality by default, noone has really encountered it.

**Comment by burmancomp** [comment]
I suppose that problem has been there at least from version 53 beta 64-bit. I emailed about it to asterisk users mailing list in 28th of august 2016 referring to version 53 beta. Setting dtls_rekey=60 was not problem with firefox 50 a2 32-bit.

I have just updated to debian 12 but likely result is same. Likely this applies to edge as well, and maybe problem is also with linux versions of chromium based browsers. Do you agree?

**Comment by jcolp** [comment]
They all generally use the same base so yes, it is entirely possible.

**Comment by burmancomp** [comment]
Is conclusion that this is issue of chromium based browsers (at least edge seems to have same problem in windows 10)?

**Comment by jcolp** [comment]
This issue is still in triage so there is no conclusion. Based on the information presented, some searching, and a gut feeling that's just my opinion, whether it's true or not I don't know. I'm not familiar with the implementation details of the Chrome side.

**Comment by jcolp** [comment]
This is correct behavior of Chrome according to RFC8827[1]:

Implementations MUST NOT implement DTLS renegotiation and MUST reject it with a "no_renegotiation" alert if offered.

That is what I suspect is happening. DTLS support in Asterisk predates WebRTC, and our own webrtc option doesn't enable it.

[1] https://datatracker.ietf.org/doc/html/rfc8827

**Comment by burmancomp** [comment]
Thank you for this information.
