### ISSUE TITLE
[bug]: Unnecessary re-INVITE after answer

### ISSUE THREAD

**Issue by berjon9** [asterisk/asterisk#384]
### Severity

Minor

### Versions

20.5.0, 20.4.0, 20.0.1, 18.20.0, 18.17.0, 18.16.0

### Components/Modules

res_pjsip

### Operating Environment

The software is run on a container image based on Debian 11.6 using Docker.

### Frequency of Occurrence

Constant

### Issue Description

I've been trying to simulate a call using `SIPp` for both server and client on a very simple scenario: 
```
A        Asterisk    B
  ----> Invite ---->
  <---- 100   <----
  <---- 180   <----
  <---- 200   <----
   Pause
  -----> Bye ----->
  <----- 200 <-----
```

This has been working for a long time using vesion `18.15.0`, however after an upgrade to version `20.4.0` I started noticing that B wasn't properly managing the BYE message, even if the scenario seemed to be successful on A.
After picking up some traces I realized that B was reciving the BYE message okay, just like it did on the previous version. 

However, right after the call establishment, Asterisk would be sending towards B a re-INVITE, which apparently was just like the original invite:
  - There is no change on the SDP except for the session version on the `o=` line
  - The timer has not expired yet

Given that the extra message is not covered in the simulation (it shouldn't be there), the call would fail.

I could also appreciate that this wouldn't happen if the call had media flowing on it, (on the simulation I cannot inject media). This kind of reminded me of this issue on `Asterisk 16` where an unnecessary re-INVITE was generated: [issue #28871](https://issues-archive.asterisk.org/ASTERISK-28871)

I run the test on several versions, being the most recent one in which it worked `Asterisk 18.15.0`. This situation took place in all other versions mentioned on the issue.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
You need to show the actual configuration, as well as the SIP trace. The re-INVITE can also occur for other reasons, such as connected line updates.

**Comment by berjon9** [comment]
Sure. 

Here are the traces. I suggest using a `sip || http` filter to get all valuable information.
[traces.zip](https://github.com/asterisk/asterisk/files/13163763/traces.zip)

About the config:

Here is the `pjsip.conf`:
```
[simpletrans]
type=transport
protocol=udp
bind=0.0.0.0:port_sip
external_signaling_address=signal_IP
external_media_address=media_IP

[to_b]
type=aor
contact=sip:A1352472@192.168.0.8:4090

[to_b]
type=endpoint
context=testing_env
100rel=yes
disallow=all
allow=ulaw
allow=alaw
aors=to_b
from_domain=sip.domain.org
direct_media=no

[from_a]
type=endpoint
context=testing_env
100rel=yes
disallow=all
allow=ulaw
allow=alaw
aors=entrada
from_domain=sip.domain.org
direct_media=no

[from_a]
type=aor
remove_existing=yes

[from_a]
type=identify
endpoint=from_a
match=192.168.0.8
```

However I'd like to point out that I use exactly the same config when executing in all the different versions.   
This includes the `pjsip.conf`, `extensions.conf` and ARI processes involved. This process is further described below. The `extensions.conf` basically gets header values and passes them towards the ARI as arguments, therefore I consider that it wouldn't be super relevant for this case.

The ARI then follows the following process:
  - Manages the arguments
  - Creates an outgoing channel
  - Puts both channels into a bridge
  - When the terminating is answered, answers the originating
  - "here happens the reinvite"
  - Starts recording bridge
  - Plays announcement

The code hasn't been included given that all requests sent are shown on the traces, but in case you needed anything else, please, just let me know.

**Comment by jcolp** [comment]
Okay, so now ARI is involved as well. It's extremely important to be specific in all aspects of what is being done and used, because things can operate differently between them and not doing so can result in people chasing completely unrelated things wasting time. Your original reporting made it seem as though you were using Dial() which is completely separate code.

As connected lines have been eliminated an actual core debug log[1] should provide more insight into what is going on, and the decisions made. As well the easier you make it to reproduce the issue, the more likelihood someone will more quickly take a look - such as providing an example ARI application.

[1] https://docs.asterisk.org/Operation/Logging/Collecting-Debug-Information/?h=collecting

**Comment by berjon9** [comment]
You're right, sorry for not having mentioned ARI from the beginning.

I'm attaching both the log and an ARI example. It is a simplified scenario with the basic stuff to establish a call. In case you needed the SIPp scenarios or something similar, please let me know.

[ari.zip](https://github.com/asterisk/asterisk/files/13177240/ari.zip)
[debug_log_384.txt](https://github.com/asterisk/asterisk/files/13177242/debug_log_384.txt)

**Comment by gtjoseph** [comment]
@berjon9 Can you try reverting the commit @jcolp referenced and see if it solves your issue?
In the 20 branch, the commit SHA is 60b81eabe080af842d81b9d84d1dcedb24b87398

**Comment by berjon9** [comment]
It didn't. The main difference is that the invite re invite appears to be sent before receiving the 200.
Find attached the trace in case it is of any use (I'm compressing it since github doesn't support `pcap` files)

[GIT-20-60b81eabe0.zip](https://github.com/asterisk/asterisk/files/13203467/GIT-20-60b81eabe0.zip)

**Comment by gtjoseph** [comment]
Can you give the following a try?

* Go back to stock 20.4.0, compile and install.
* Add `trace = trace` to the `[logfiles]` section in logger.conf.
* Add the following to the `[startup_commands]` section of cli.conf:
`core set trace 5 res_pjsip_session.so = yes`
`core set trace 5 chan_pjsip.so = yes`
* Start asterisk and reproduce the issue.
* Save /var/log/asterisk/trace as trace.before and delete /var/log/asterisk/trace
* Apply the attached patch, then repeat the steps above.
* Saving the trace file as trace.after.
* Does the patch fix your issue?


[bridge_simple.patch.txt](https://github.com/asterisk/asterisk/files/13208573/bridge_simple.patch.txt)

**Comment by gtjoseph** [comment]
Oh yeah,attach the two trace files if the patch doesn't fix the issue.

**Comment by berjon9** [comment]
It worked!! I presume you don't need the traces, but let me know if they're of any use.

Could you please let me know if this is going to be pushed to any branch? Implementing it is way easier for me if I can directly pull it instead of manually modifying the code.

Thank you 😄

**Comment by gtjoseph** [comment]
Pull request is up for review. The patch will go into all active branches.

**Comment by berjon9** [comment]
Hello @gtjoseph,

I saw there was a new official release on Thu 14th. However, this issue wasn't resolved in it and after a quick research, I realized that the commit `ed4978ae8b6ff9231573d25e010929a0854e9145`  that solved this issue was only merged to Master.
Is it expected to be included in any official release?

Regards

**Comment by gtjoseph** [comment]
> Hello @gtjoseph,
> 
> I saw there was a new official release on Thu 14th. However, this issue wasn't resolved in it and after a quick research, I realized that the commit `ed4978ae8b6ff9231573d25e010929a0854e9145` that solved this issue was only merged to Master. Is it expected to be included in any official release?
> 
> Regards

It was merged into all the branches but last week's release was a "Security" release and only contained fixes for the 4 security related issues.  The next regular release will be just after new year and will contain the commit you're looking for.
