### ISSUE TITLE
[Bug]: Remove .gitreview from repository.

### ISSUE THREAD

**Issue by seanbright** [asterisk/asterisk#39]
### Severity

Trivial

### Versions

GIT

### Components/Modules

Core

### Operating Environment

N/A

### Frequency of Occurrence

None

### Issue Description

Remove the, now obsolete, `.gitreview` file from the root of the project.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
I wonder if alongside this we should prune any Jenkins stuff that isn't relevant any longer, too.

**Comment by seanbright** [comment]
Make sense. I’ll take a look.
