### ISSUE TITLE
[improvement]: possibility to access history log of instant messages

### ISSUE THREAD

**Issue by dberardo-com** [asterisk/asterisk#390]
### Improvement Description

i dont know if this feature is already available, but when using instant messaging i would expect the following features to be supports:

* if one user sends messages to another user which is currently not registered, then those messages are not discarded, but delivered on the next reconnect of that user
* delivered messages should be stored on server so that users can access older instant messages in a sort of IM log

are those 2 features already available in asterisk ? and are those also SIP-compliant ?

**Comment by jcolp** [comment]
There is nothing built in. Any such functionality has generally been implemented outside of Asterisk by people. 

For feature requests there is a separate repository at https://github.com/asterisk/asterisk-feature-requests
