### ISSUE TITLE
[bug]: AgentComplete event not emitted when '*' is used

### ISSUE THREAD

**Issue by aeinstein** [asterisk/asterisk#393]
### Severity

Minor

### Versions

16.30, 20.5

### Components/Modules

agent_pool

### Operating Environment

Debian

### Frequency of Occurrence

Constant

### Issue Description

When an agent disconnect a call by hitting '*' and the call is proceeding to the next dialplan extension (Queue option 'c'), 
the agent is 'not in use' again but the 'AgentComplete' AMI Event is not emmitted until the original call is ended or the agent disconnect from queue (AgentLogoff). 
Also the reason is 'caller' not 'agent'.
You can see in the AMI Console 2 Events on hangup with different talktime which came at the same time.
Agent 300001 has disconnected the call after 4 secs not 11.
Agent 300003 has 7 secs, this is correct.

BTW: The link 'Asterisk Issue Guidelines' below is not pointing to the guidelines

### Relevant log output

```shell
Event: AgentComplete
Privilege: agent,all
DestChannel: PJSIP/1-00000027
DestChannelState: 6
DestChannelStateDesc: Up
DestCallerIDNum: 300001
DestCallerIDName: MBalen
DestConnectedLineNum: <unknown>
DestConnectedLineName: <unknown>
DestLanguage: en
DestAccountCode: TEST_TR
DestContext: agents
DestExten: 902
DestPriority: 5
DestUniqueid: 1698408952.123
DestLinkedid: 1698408952.123
Queue: alles_neu
Interface: Local/300001@dialer
MemberName: 300001
HoldTime: 0
TalkTime: 11
Reason: caller



Event: AgentComplete
Privilege: agent,all
DestChannel: PJSIP/3-00000029
DestChannelState: 6
DestChannelStateDesc: Up
DestCallerIDNum: 300003
DestCallerIDName: KBalen
DestConnectedLineNum: 0049941993248
DestConnectedLineName: <unknown>
DestLanguage: en
DestAccountCode: TEST_TR
DestContext: agents
DestExten: 902
DestPriority: 5
DestUniqueid: 1698408957.127
DestLinkedid: 1698408952.123
Queue: Checkers
Interface: Local/300003@dialer
MemberName: 300003
HoldTime: 0
TalkTime: 7
Reason: caller
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Please provide complete reproduction instructions including configuration.

**Comment by aeinstein** [comment]
First I use static configuration in Database via ODBC

dialplan for AgentLogin:
'902' =>          
                    1. Set(AGENTWRAPUPTIME=0)                     [extensions.conf:0]
                    2. Set(CHANNEL(dtmf_features)=H)              [extensions.conf:0]
                    3. Answer()                                                     [extensions.conf:0]
                    4. AgentLogin(${CALLERID(number)},s)         [extensions.conf:0]

dialplan for agents:
'_3XXXXX' =>      1. Set(__AGENTID=${EXTEN})                    [extensions.conf:0]
                            2. AgentRequest(${EXTEN})                       [extensions.conf:0]

diaplan for incoming:
'_X.' =>        1. Answer()
                    2. Queue(alles_neu,rwchH,,,10)                 [extensions.conf:0]
                    3. Queue(Checkers,rw,,,10)                    [extensions.conf:0]

queue alles_neu:
alles_neu has 0 calls (max 1) in 'leastrecent' strategy
Members:
   300001 (Local/300001@agents from Agent:300001) (ringinuse disabled) (paused was 2520 secs ago) (Not in use)

queue Checkers:
Checkers has 0 calls (max 10) in 'leastrecent' strategy
   Members:
      300003 (Local/300003@agents from Agent:300003) (ringinuse disabled) (Not in use) 
     
Reproduction:
- Login the agents by dialing 902
- do an inbound call
- agent 300001 gets the call
- disconnect the call by sending '*' via dtmf
- "look for AMI Events", no AgentComplete Event
- now agent 300003 gets the call
- disconnect the call at 300003, the dialplan finished and hangup the call, AgentComplete is emmited for both agents.

I hope this is enough, 
or should I build a simple config only for this case (I have to install a complete new maschine, I cant change my testsetup)??

**Comment by jcolp** [comment]
It is ideal to provide complete configuration, to ensure that during investigation and potentially resolution it can be reproduced. Providing only specific parts can leave it open to interpretation by people what is needed, resulting in potentially wasted time or repeated back and forth trying to isolate a difference. The easier it is for someone to reproduce the issue, the more possibility there is for someone to take a look.

**Comment by aeinstein** [comment]
I will do a clean simplfied install/config this weekend
