### ISSUE TITLE
[bug]: chan_rtp does not support slin @ 8kHz

### ISSUE THREAD

**Issue by anydict** [asterisk/asterisk#394]
### Severity

Trivial

### Versions

20.2.0, 20.5.0

### Components/Modules

res_ari_channels, resource_channels

### Operating Environment

Ubuntu 22.04

### Frequency of Occurrence

Constant

### Issue Description

When creating an External Media channel with a codec format "slin":
```
{
"channelId": "EM123",
"app": "TEST_APP",
"external_host": "127.0.0.1:1234",
"encapsulation": "rtp",
"transport": "udp",
"connection_type": "client",
"format": "slin",
"direction": "both"
}
```
The stream received from this channel will be in ulaw codec. But 8kHz PCM was expected (slin8)
If i set "slin8", then i get an error: `Provided format (slin8) was not found`

When "slin16" is set, then everything is fine: 16kHz PCM stream
Now I have changed my code to convert 16kHz PCM to 8kHz PCM

Below is more detailed information about the ExternalMedia channel inside asterisk if I use “slin” and "slin16"
`asterisk -x 'core show channel UnicastRTP/127.0.0.1:1234-0x7f48b401b760`

### Relevant log output

```shell
-- General --
           Name: UnicastRTP/127.0.0.1:1234-0x7f48b401b760
           Type: UnicastRTP
       UniqueID: emedia_123
       LinkedID: snoop_123
      Caller ID: (N/A)
 Caller ID Name: (N/A)
Connected Line ID: (N/A)
Connected Line ID Name: (N/A)
Eff. Connected Line ID: (N/A)
Eff. Connected Line ID Name: (N/A)
    DNID Digits: (N/A)
       Language: en
          State: Up (6)
  NativeFormats: (ulaw)
    WriteFormat: slin
     ReadFormat: slin
 WriteTranscode: Yes (slin@8000)->(ulaw@8000)
  ReadTranscode: Yes (ulaw@8000)->(slin@8000)
 Time to Hangup: 0
   Elapsed Time: 0h0m8s
      Bridge ID: bridge_123
 --   PBX   --
        Context: default
      Extension: s
       Priority: 1
     Call Group: 0
   Pickup Group: 0
    Application: Stasis
           Data: callpy
 Call Identifer: (None)
      Variables:
BRIDGEPEER=Snoop/123
STASISSTATUS=
UNICASTRTP_LOCAL_PORT=10660
UNICASTRTP_LOCAL_ADDRESS=127.0.0.1
 -- Streams --
Name: audio-0
    Type: audio
    State: sendrecv
    Group: -1
    Formats: (ulaw)
    Metadata:



 -- General --
           Name: UnicastRTP/127.0.0.1:1234-0x7f494c02f4e0
           Type: UnicastRTP
       UniqueID: emedia_123
       LinkedID: snoop_123
      Caller ID: (N/A)
 Caller ID Name: (N/A)
Connected Line ID: (N/A)
Connected Line ID Name: (N/A)
Eff. Connected Line ID: (N/A)
Eff. Connected Line ID Name: (N/A)
    DNID Digits: (N/A)
       Language: en
          State: Up (6)
  NativeFormats: (slin16)
    WriteFormat: slin16
     ReadFormat: slin16
 WriteTranscode: No 
  ReadTranscode: No 
 Time to Hangup: 0
   Elapsed Time: 0h0m7s
      Bridge ID: bridge_snoop_123
 --   PBX   --
        Context: default
      Extension: s
       Priority: 1
     Call Group: 0
   Pickup Group: 0
    Application: Stasis
           Data: callpy
 Call Identifer: (None)
      Variables:
BRIDGEPEER=Snoop/123-00000010
STASISSTATUS=
UNICASTRTP_LOCAL_PORT=10614
UNICASTRTP_LOCAL_ADDRESS=127.0.0.1
 -- Streams --
Name: audio-0
    Type: audio
    State: sendrecv
    Group: -1
    Formats: (slin16)
    Metadata:
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
The code in chan_rtp explicitly doesn't allow "slin" due to confusion it seems over which RTP payload to use, as it has two (2 channels or 1 channel). Since the code doesn't allow you to specify an RTP payload yourself, it then falls back to using ulaw instead.

**Comment by jcolp** [comment]
Original issue that caused that change being here: https://issues-archive.asterisk.org/ASTERISK-21399

**Comment by jcolp** [comment]
I think ultimately this should allow RTP payload selection to also allow dynamic ones, so I'll leave this open.

**Comment by seanbright** [comment]
https://github.com/asterisk/asterisk/commit/eec03963951138ad1ceb24ad3b57f0867e3ffb1f

**Comment by anydict** [comment]
I started accepting slin PCM 8kHz after rolling back changes from this patch. I am building asterisk in docker and added replace ulaw to slin, which completely solves my problem. It would be more convenient to be able to change this behavior through a configuration file.

**Comment by seanbright** [comment]
And what is the RTP payload code in the packets you are receiving?

**Comment by seanbright** [comment]
@anydict any chance you would be willing to test [this PR](https://github.com/asterisk/asterisk/pull/416) instead of reverting https://github.com/asterisk/asterisk/commit/eec03963951138ad1ceb24ad3b57f0867e3ffb1f ?

**Comment by anydict** [comment]
@seanbright Yes, of course, but I can in 20 hours. After undoing the fix, I was getting a value of 10 in payload code when using slin.

**Comment by anydict** [comment]
@seanbright I have tested working with [this PR](https://github.com/asterisk/asterisk/pull/416) and the audio stream went with the correct codec 8kHz PCM (slin). I didn't quite understand how these changes fixed the problem, but it works.
``` 
-- General --
           Name: UnicastRTP/127.0.0.1:1234-0x7f2ae4006310
           Type: UnicastRTP
       UniqueID: emedia_oper-call_id-X123
       LinkedID: emedia_oper-call_id-X123
      Caller ID: (N/A)
 Caller ID Name: (N/A)
Connected Line ID: (N/A)
Connected Line ID Name: (N/A)
Eff. Connected Line ID: (N/A)
Eff. Connected Line ID Name: (N/A)
    DNID Digits: (N/A)
       Language: en
          State: Up (6)
  NativeFormats: (slin)
    WriteFormat: slin
     ReadFormat: slin
 WriteTranscode: No 
  ReadTranscode: No 
 Time to Hangup: 0
   Elapsed Time: 0h0m23s
      Bridge ID: bridge_snoop_oper-call_id-X123
 --   PBX   --
        Context: default
      Extension: s
       Priority: 1
     Call Group: 0
   Pickup Group: 0
    Application: Stasis
           Data: callpy
 Call Identifer: (None)
      Variables:
BRIDGEPEER=Snoop/oper-call_id-X123-00000001
STASISSTATUS=
UNICASTRTP_LOCAL_PORT=10478
UNICASTRTP_LOCAL_ADDRESS=127.0.0.1
 -- Streams --
Name: audio-0
    Type: audio
    State: sendrecv
    Group: -1
    Formats: (slin)
    Metadata:
```

**Comment by seanbright** [comment]
@anydict thank you for testing!
