### ISSUE TITLE
[bug]: Inconsistent reason behavior when unpausing member in app_queue

### ISSUE THREAD

**Issue by KKeXX** [asterisk/asterisk#395]
### Severity

Minor

### Versions

20.5.0

### Components/Modules

Applications/app_queue 

### Operating Environment

Red Hat Enterprise Linux 9.2, kernel 5.14.0-284.30.1.el9_2.x86_64

### Frequency of Occurrence

None

### Issue Description

PausedReason is not set in  QueueMemberPause AMI Event when unpaused. Reason is set when paused.

### Relevant log output

```shell
Set pause works as expected: 
Action: QueuePause
ActionID: 129
Paused: 1
Reason: Pause1
Interface: Local/129@intern

Event: QueueMemberPause
Privilege: agent,all
Queue: main
MemberName: Local/129@intern
Interface: Local/129@intern
StateInterface: PJSIP/129
Membership: static
Penalty: 0
CallsTaken: 0
LastCall: 0
LastPause: 1698660614
LoginTime: 1698658694
InCall: 0
Status: 1
Paused: 1
PausedReason: Pause1
Ringinuse: 0
Wrapuptime: 0

But unpause does not set the PausedReason:

Action: QueuePause
ActionID: 129
Paused: 0
Reason: Pause1
Interface: Local/129@intern

Event: QueueMemberPause
Privilege: agent,all
Queue: main
MemberName: Local/129@intern
Interface: Local/129@intern
StateInterface: PJSIP/129
Membership: static
Penalty: 0
CallsTaken: 0
LastCall: 0
LastPause: 1698660614
LoginTime: 1698658694
InCall: 0
Status: 1
Paused: 0
PausedReason: 
Ringinuse: 0
Wrapuptime: 0
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Since it is unpaused, I would not expect a paused reason to be present. The value is only meant to be present when paused.

**Comment by KKeXX** [comment]
The unpause reason is written into the queue_log. And the UnpauseQueueMember function accepts a reasen too. Therefore setting pausedReason in QueueMemberPause would be consistent?

**Comment by seanbright** [comment]
> And the UnpauseQueueMember function accepts a reasen too.

Then that is the bug. The `UnpauseQueueMember` action does not use the reason parameter and it is not stored anywhere.

**Comment by KKeXX** [comment]
But the reason parameter from UnpauseQueueMember is written into queue_log (PgSQL in my case)

**Comment by seanbright** [comment]
Feel free to give #400 a try and let us know your findings.

**Comment by KKeXX** [comment]
Great! Works as expected! :-)

Action: QueuePause
ActionID: 129
Paused: 0
Reason: Pause1
Interface: Local/129@intern

Event: QueueMemberPause
Privilege: agent,all
Queue: main
MemberName: Local/129@intern
Interface: Local/129@intern
StateInterface: PJSIP/129
Membership: static
Penalty: 0
CallsTaken: 0
LastCall: 0
LastPause: 1698695141
LoginTime: 1698694929
InCall: 0
Status: 1
Paused: 0
PausedReason: Pause1
Ringinuse: 0
Wrapuptime: 0
Thanks! :+1:
