### ISSUE TITLE
[Bug]: Link to trademark policy is no longer correct

### ISSUE THREAD

**Issue by jcolp** [asterisk/asterisk#43]
### Severity

Trivial

### Versions

18, 20, master

### Components/Modules

LICENSE

### Operating Environment

All

### Frequency of Occurrence

Constant

### Issue Description

The link in the LICENSE file to the trademark policy should be https://www.sangoma.com/wp-content/uploads/Sangoma-Trademark-Policy-1.pdf

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by gtjoseph** [comment]
Testing the gh2jira function.
