### ISSUE TITLE
[bug]: media cache delete doesn't completely delete in certain cases

### ISSUE THREAD

**Issue by dovi5988** [asterisk/asterisk#439]
### Severity

Trivial

### Versions

20.4.0

### Components/Modules

res_http_media_cache

### Operating Environment

Debian 12
Asterisk 20.4.0
Asterisk built from source

### Frequency of Occurrence

Constant

### Issue Description

In some cases "media cache delete" does not successfully delete the astdb entry, the specific circumstances, steps, are not yet known.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
That's not unlinking a file. That's finding the media cache entry object in a local container and removing it from the container. The subsequent API calls actually do deletion from disk, and then deletion from astdb.

What is the specific step by step scenario, and what is output?

**Comment by dovi5988** [comment]
@jcolp Here is an example I have a URL of ```https://tc-podcasts.s3.amazonaws.com/titles/302/title.wav```. If I do database show I see the file in there:
```
root@a15-c3:~# asterisk -rx'database show' | grep https://tc.s3.amazonaws.com/titles/302
/MediaCache/https://tc.s3.amazonaws.com/titles/302/title.wav: 7e33222589da07d19e2f3e2721375cc392efe801
root@a15-c3:~#
```
However if I look for the file via the media cache it does not see it:
```
a15-c3-*CLI> media cache show https://tc.s3.amazonaws.com/titles/302/title.wav
Unable to find 'https://tc.s3.amazonaws.com/titles/302/title.wav' in the media cache
a15-c3*CLI> 
```

**Comment by jcolp** [comment]
And what is the specific step by step scenario?

**Comment by dovi5988** [comment]
I am not able to re-produce on demand and I am trying to figure out why. This started when I wrote a script to look at ```/var/lib/asterisk/astdb.sqlite3``` and get any file where the expires > 7 days and do a media cache delete on it. It seems that sometimes the entry is not removed. For instance the file ```/var/cache/asterisk/bucket-cxnWzg.wav``` does not exist
```
 root@a15-c3:~# ll /var/cache/asterisk/bucket-cxnWzg.wav
ls: cannot access '/var/cache/asterisk/bucket-cxnWzg.wav': No such file or directory
root@a15-c3:~# 
```

If I do:
```
root@a15-c3:~# asterisk -rx'database show' | grep tc.s3.amazonaws.com/titles/302/title
/MediaCache/https://tc-podcasts.s3.amazonaws.com/titles/302/title.wav: 7e33222589da07d19e2f3e2721375cc392efe801
root@a15-c3:~# asterisk -rx'database show' | grep 7e33222589da07d19e2f3e2721375cc392efe801
/7e33222589da07d19e2f3e2721375cc392efe801/__actual_expires:                     1698700362
/7e33222589da07d19e2f3e2721375cc392efe801/content-type: audio/wav                
/7e33222589da07d19e2f3e2721375cc392efe801/etag    : "02dd28717a37f6887934634db1c7b803"
/7e33222589da07d19e2f3e2721375cc392efe801/ext     : .wav                     
/7e33222589da07d19e2f3e2721375cc392efe801/last-modified: Mon, 04 Sep 2023 20:08:17 GMT
/7e33222589da07d19e2f3e2721375cc392efe801/path    : /var/cache/asterisk/bucket-cxnWzg.wav
/MediaCache/https://tc.s3.amazonaws.com/titles/302/title.wav: 7e33222589da07d19e2f3e2721375cc392efe801
root@a15-c3:~# 
```
So the entry does seem to be there but it's NOT in the media cache
```
a15-c3*CLI> media cache show https://tc.s3.amazonaws.com/titles/302/title.wav
Unable to find 'https://tc.s3.amazonaws.com/titles/302/title.wav' in the media cache
a15-c3*CLI> 
```

So in summary it shows in database show and in the sqlite file but not in asterisk.

**Comment by jcolp** [comment]
Okay, so the specific scenario is not known and it doesn't happen all the time.

**Comment by dovi5988** [comment]
Correct. When I manually delete the file then do a media cache delete and then check the entry is gone from astdb. It seems in certain scenario's when the file is deleted it wont show in media cache but it will be in the sqlite file and database cache.

**Comment by jcolp** [comment]
Without knowing the scenario that causes it, it's likely to be extremely difficult to isolate and resolve.

**Comment by dovi5988** [comment]
@jcolp OK. I am going to try to "mess around" and see if I can figure out what combination causes the issue. Please leave open for a week and if I can't find it by then I will close it.

**Comment by dovi5988** [comment]
I can't seem to re-produce reliably. Closing for now.
