### ISSUE TITLE
[bug]: Stir/Shaken: Wrong CID used when looking up certificates

### ISSUE THREAD

**Issue by lukeescude** [asterisk/asterisk#46]
### Severity

Trivial

### Versions

16, 18, 20

### Components/Modules

STIR/SHAKEN

### Operating Environment

CentOS 7 x64

### Frequency of Occurrence

Constant

### Issue Description

When signing outbound calls, Asterisk is using the wrong callerID to look up certificates.

There is a patch available in progress, I just wanted to get it into the Github issue system: 

https://gerrit.asterisk.org/c/asterisk/+/16174

Dial plan example:
exten => 507,1,Set(CALLERID(num)=442081254195)

507 is the extension, 442081254195 is the Caller ID number (network number) which should be utilized for cert check

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by gtjoseph** [comment]
@seanbright @bkford I'm lost in the history here.  The gerrit review comments make my head ache.  Does that review need to be recreated here as a PR?

**Comment by seanbright** [comment]
Probably. The review on gerrit is -2 because the tests are failing and needed to be reworked.

**Comment by seanbright** [comment]
I suggest reading the comments on [the abandoned 16 review](https://gerrit.asterisk.org/c/asterisk/+/16153).

**Comment by lukeescude** [comment]
Just to confirm, this fix has not made it into Asterisk yet, correct? I'm surprised this isn't bothering more people, since stir/shaken is pretty much a requirement now.

**Comment by jcolp** [comment]
This issue remains open, no fix has been merged. It will automatically close upon merging in a fix.
