### ISSUE TITLE
[bug]: Bundled PJPROJECT failing

### ISSUE THREAD

**Issue by thisis-akash** [asterisk/asterisk#484]
### Severity

Major

### Versions

18.4.0, 20.5.0

### Components/Modules

configure

### Operating Environment

Ubuntu 22.04 LTS

### Frequency of Occurrence

Constant

### Issue Description

Configure script fails when running with --with-pjproject-bundled option. 
It gets stuck downloading pjproject from "https://raw.githubusercontent.com/asterisk/third-party/master/pjproject/2.13.1/pjproject-2.13.1.tar.bz2". 
The file is inaccessible even when hit directly from the browser. 

**My Investigation:**
1. Manually navigating to the asterisk master branch, there is no folder inside pjproject named 2.13.1 and this file seems to be non-existent. There is not even a branch by the name 2.13.1, there is a support-2.13.1 I recall.
2. I tried installing the tarball of the version Asterisk script was trying to install from https://www.pjsip.org/download.htm and storing it in /tmp/downloads as instructed [here](https://docs.asterisk.org/Getting-Started/Installing-Asterisk/Installing-Asterisk-From-Source/Prerequisites/PJSIP-pjproject/#usage) but the md5 hash is not available there and moreover, running configure with '--with-externals-cache=/tmp/downloads' still tries to download pjproject from the link I mentioned above in the first go itself, seemingly ignoring the option.
3. I tried installing asterisk from version 18.4.0 archive, the archive that was working, but it faced the same issue, things stop at downloading from that link and the installation fails. 
4. I looked at community forums, but no fruitful conclusion.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
We appreciate the difficulties you are facing, however this does not appear to be a bug report and your request or comments would be better served in a different forum.

The Asterisk community provides support over IRC, mailing lists, and forums as described at http://asterisk.org/community. The Asterisk issue tracker is used specifically to track issues concerning bugs and documentation errors.

Thanks!
