### ISSUE TITLE
[bug regression]: res_rtp_asterisk doesn't build if pjproject isn't used

### ISSUE THREAD

**Issue by walter59** [asterisk/asterisk#500]
### Severity

Blocker

### Versions

20.5.1 / 21.0.1

### Components/Modules

compile

### Operating Environment

linux 6.5.12 / pjproject 2.13.1 oor pjproject-2.14

### Frequency of Occurrence

None

### Issue Description

res_rtp_asterisk.c:3218:83: error: âPJ_ICE_MAX_CANDâ undeclared (first use in this function)
 3218 |                         while ((candidate = ao2_iterator_next(&i)) && (cand_cnt < PJ_ICE_MAX_CAND)) {
      |                                                                                   ^~~~~~~~~~~~~~~
res_rtp_aster

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Is this with unbundled PJSIP?

**Comment by gtjoseph** [comment]
@walter59 Was the error message in the issue description the only error, or were there others preceding it?  Since you mention pjproject versions, we're trying to confirm whether you're not using pjproject at all or using an externally built version.

If you weren't using it at all, you'd see the following...
```
   [CC] res_rtp_asterisk.c -> res_rtp_asterisk.o
res_rtp_asterisk.c: In function ‘__rtp_recvfrom’:
res_rtp_asterisk.c:3217:24: error: ‘struct ast_rtp’ has no member named ‘ice’
 3217 |                 if (rtp->ice) {
      |                        ^~
res_rtp_asterisk.c:3234:33: error: ‘struct ast_rtp’ has no member named ‘ice_media_started’
 3234 |                         if (!rtp->ice_media_started) {
      |                                 ^~
res_rtp_asterisk.c:3245:50: error: ‘struct ast_rtp’ has no member named ‘ice_active_remote_candidates’
 3245 |                         i = ao2_iterator_init(rtp->ice_active_remote_candidates, 0);
      |                                                  ^~
res_rtp_asterisk.c:3246:83: error: ‘PJ_ICE_MAX_CAND’ undeclared (first use in this function)
 3246 |                         while ((candidate = ao2_iterator_next(&i)) && (cand_cnt < PJ_ICE_MAX_CAND)) {
      |                                                                                   ^~~~~~~~~~~~~~~
```

Can you confirm?
