### ISSUE TITLE
[bug]: res_pjproject: ast_sockaddr_cmp() always fails on sockaddrs created by ast_sockaddr_from_pj_sockaddr()

### ISSUE THREAD

**Issue by gtjoseph** [asterisk/asterisk#505]
### Severity

Trivial

### Versions

18,20,21,master

### Components/Modules

res_pjproject

### Operating Environment

any

### Frequency of Occurrence

Constant

### Issue Description

If using ast_sockaddr_cmp() and either or both of the input sockaddrs were created with ast_sockaddr_from_pj_sockaddr(), the comparison will always be non-zero (not equal) even if both inputs have the exactly same family, address and port.  This is caused by ast_sockaddr_from_pj_sockaddr() not zeroing out the sin->sin_zero array in the destination socket.  With possible garbage in there, ast_sockaddr_cmp's memcmp of the entire sin structure will most likely return not-equal even if all other structure members are in fact equal.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by A1bi** [comment]
The issue persists on BSD platforms. For the past few days I have been struggling with Asterisk on FreeBSD dropping all DTLS packets. This is the first time I tried out connecting from a browser via WebRTC and I was surprised I couldn’t successfully make single call while all other kinds of connections to my server have been working flawlessly for years.

After some debugging I found the culprit to be another field only present on some platforms (mainly BSD derivatives) in `sockaddr_in6` / `sockaddr_in` not set by `ast_sockaddr_from_pj_sockaddr()`.

I have created a fix and will post a PR shortly.
