### ISSUE TITLE
[bug]: MixMonitor doesn't record after Blind Transfer

### ISSUE THREAD

**Issue by umerov1999** [asterisk/asterisk#507]
### Severity

Trivial

### Versions

18.20.1

### Components/Modules

MixMonitor

### Operating Environment

Debian 12, Freepbx 16

### Frequency of Occurrence

None

### Issue Description

After a blind transfer on the call recording, I only hear the voice from the call initiator on PJSIP.  There are no errors in the logs.  Sometimes it happens that both voices are recorded.  Codec alaw, recording format wav

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
We require additional debug to continue with triage of your issue. Please follow the instructions on the wiki [1] for how to collect debugging information from Asterisk. For expediency, where possible, attach the debug with a '.txt' file extension so that the debug will be usable for further analysis.

Thanks!

[1] https://docs.asterisk.org/Operation/Logging/Collecting-Debug-Information/?h=collecting+debug

**Comment by umerov1999** [comment]
> We require additional debug to continue with triage of your issue. Please follow the instructions on the wiki [1] for how to collect debugging information from Asterisk. For expediency, where possible, attach the debug with a '.txt' file extension so that the debug will be usable for further analysis.
> 
> Thanks!
> 
> [1] https://docs.asterisk.org/Operation/Logging/Collecting-Debug-Information/?h=collecting+debug

[log.txt](https://github.com/asterisk/asterisk/files/13745926/log.txt)
[Call Recoed_1703189518.65_From_79859844541.zip](https://github.com/asterisk/asterisk/files/13745936/Call.Recoed_1703189518.65_From_79859844541.zip)

I am sending you the logs and recording. On the 2nd blind transfer, the voice of the extension disappears
External caller says "Odin" "Dva" "Tri" Chetyre". Internal caller - playing music And Transfering from 101 to 102, and 102 Transfer 101

**Comment by jcolp** [comment]
And audio flows as expected between them despite the recording? The debug makes it seem as though it is not getting audio from one side at the expected interval to satisfy recording.

**Comment by umerov1999** [comment]
> And audio flows as expected between them despite the recording? The debug makes it seem as though it is not getting audio from one side at the expected interval to satisfy recording.

The sound on phones works fine, but disappears on recordings.

**Comment by jcolp** [comment]
What type of device or endpoint is on each side? Are they encrypted? Can you do a packet capture of both streams?

**Comment by umerov1999** [comment]
> What type of device or endpoint is on each side? Are they encrypted? Can you do a packet capture of both streams?

Good evening.  We used a mobile phone on one side and a Fanvil X303w on the other.  At the time of taking the logs, I was using the MicroSip application instead of Fanvil.  Traffic is not encrypted.

I can only record packet traces on weekends.

**Comment by jcolp** [comment]
Does it happen with only those involved, or with other types of endpoints?

**Comment by umerov1999** [comment]
> Does it happen with only those involved, or with other types of endpoints?

The type of endpoints is not important.  We tried different devices, and even tried an E1 DAHDI trunk with pjsip endpoints, also pure calls between endpoints - the result was the same

**Comment by umerov1999** [comment]
> Does it happen with only those involved, or with other types of endpoints?

There is an assumption that this is a problem with codecs. If a-law was selected for the endpoints, then there were problems, but if gsm was selected, then it seems to work

**Comment by seanbright** [comment]
I might be experiencing this too. Can we re-open?

**Comment by jcolp** [comment]
Request completed successfully.

**Comment by umerov1999** [comment]
I dropped debian patch "opus codec", and recording work fine with codec alaw/ulaw
