### ISSUE TITLE
[bug]: pjsip outbound-publish cannot change custom hint state from inuse to idle on secondary instance

### ISSUE THREAD

**Issue by pc-m** [asterisk/asterisk#508]
### Severity

Trivial

### Versions

20.5.2

### Components/Modules

res_pjsip_outbound_publish.so

### Operating Environment

Debian 11.8
Linux asterisk-1 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux

### Frequency of Occurrence

Constant

### Issue Description

Given two instances instance-1 and instance-2
instance-1 is at 192.168.56.102
instance-2 is at 192.168.56.101
Given the following pjsip configuration on instance-1
```
[instance2]
type=endpoint
 
[instance2-devicestate]
type=outbound-publish
server_uri=sip:instance1@192.168.56.101
event=asterisk-devicestate
 
[instance2]
type=inbound-publication
event_asterisk-devicestate=instance2
 
[instance2]
type=asterisk-publication
devicestate_publish=instance2-devicestate
device_state=yes
```
And the following configuration on instance-2
```
[instance1]
type=endpoint
 
[instance1-devicestate]
type=outbound-publish
server_uri=sip:instance2@192.168.56.102
event=asterisk-devicestate
 
[instance1]
type=inbound-publication
event_asterisk-devicestate=instance1
 
[instance1]
type=asterisk-publication
devicestate_publish=instance1-devicestate
device_state=yes
```
Given the following extensions.conf on both instances
```
[default]

exten = *42,hint,Custom:*42
```
At this point I can change the state of the hint using the following command
`devstate change Custom:*42 <new state>`
and I can monitor the current state with the following command
`core show hint *42`

When switching from `NOT_INUSE` to `INUSE` on any of the instances change the state on both. OK
Switching back from `INUSE` to `NOT_INUSE` from the same instance as the first change works
Switching back from `INUSE` to `NOT_INUSE` from the other instance does not work.

To get back to a working state you have to manually set the devicestate to `NOT_INUSE` on all instances.

This is especially painful in active active mode, when a device state gets set to `INUSE` from instance-1 then it cannot be set back to `NOT_INUSE` by the second instance if the first one is down for any reason.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
We require additional debug to continue with triage of your issue. Please follow the instructions on the wiki [1] for how to collect debugging information from Asterisk. For expediency, where possible, attach the debug with a '.txt' file extension so that the debug will be usable for further analysis.

Thanks!

[1] https://docs.asterisk.org/Operation/Logging/Collecting-Debug-Information/?h=collecting+debug

**Comment by pc-m** [comment]
I've reproduced the issue and added the cli sessions for both asterisk and the loggers.

[cli_508-asterisk-1.txt](https://github.com/asterisk/asterisk/files/13779574/cli_508-asterisk-1.txt)
[cli_508-asterisk-2.txt](https://github.com/asterisk/asterisk/files/13779573/cli_508-asterisk-2.txt)
[debug_log_508-asterisk-1.txt](https://github.com/asterisk/asterisk/files/13779585/debug_log_508-asterisk-1.txt)
[debug_log_508-asterisk-2.txt](https://github.com/asterisk/asterisk/files/13779586/debug_log_508-asterisk-2.txt)

**Comment by jcolp** [comment]
Ah, after rereading your description I believe this fundamentally doesn't work the way you want. This isn't made for replication of state. It's made for a combined view of independent state from multiple concurrent instances. That is:

System '1' has a device state of in use
System '2' has a device state of not in use
Combined view is in use
System '2' changes device state to in use
Combined view is in use
System '2' changes device state to not in use
Combined view remains in use
System '1' changes device state to not in use
Combined view is not in use

It was made for endpoints, though doesn't differentiate between them and custom device states. To support your use case would require new feature development and additional functionality.
