### ISSUE TITLE
[bug]: func_odbc: Large octet length results in crash

### ISSUE THREAD

**Issue by dovi5988** [asterisk/asterisk#510]
### Severity

Minor

### Versions

20.5.2

### Components/Modules

func_odbc

### Operating Environment

Rocky Linux 8
Astrerisk 20.5.2 from source
mariadb-connector-odbc-3.1.12-1.el8.x86_64

### Frequency of Occurrence

Constant

### Issue Description

I am not sure exactly what is causing the crash I can only specify what steps I am talking to cause it. Before following the guide at https://docs.asterisk.org/Development/Debugging/Getting-a-Backtrace/ if I started asterisk with `asterisk -g -cvvvvvvvvv` then I saw an error about a double free and then a message that asterisk crashed. After I build with DONT_OPTIMIZE,DEBUG_THREADS,DEBUG_FD_LEAKS,MALLOC_DEBUG all I saw on the console was
*CLI>  Asterisk Malloc Debugger Started (see /var/log/asterisk/mmlog))
Asterisk Ready.
    -- Executing [test@from-external:1] NoOp("PJSIP/endpoint-external-00000000", "") in new stack
    -- Executing [test@from-external:2] Answer("PJSIP/endpoint-external-00000000", "") in new stack
Segmentation fault (core dumped)
bash-4.4$

Again I am not sure what I am doing that is causing the issue I can only write what I am doing.

in func_odbc.conf
```
[CHARIDY_GET_TEAM_RAISED_BY_ID]
writehandle=charidy
synopsis=Get amount raised by actual team ID
readsql=SELECT * FROM teams where campaign_id = '${SQL_ESC(${ARG1})}' and team_id = '${SQL_ESC(${ARG2})}' limit 1;
```
In the dial plan
`Set(RESULT=${ODBC_CHARIDY_GET_TEAM_RAISED_BY_ID(23277,749616,eur)})`

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by dovi5988** [comment]
[bt.log](https://github.com/asterisk/asterisk/files/13753384/bt.log)
[core.asterisk.993.b1950b1977a94d27b717ca2d7cb59d8c.62007.1703255114000000.gz](https://github.com/asterisk/asterisk/files/13753406/core.asterisk.993.b1950b1977a94d27b717ca2d7cb59d8c.62007.1703255114000000.gz)

Attached is the backtrace and core dump.

**Comment by jcolp** [comment]
According to the backtrace the octet length appears to be huge:

18446744073709551613

So what is the actual contents of the table? Does a field have a huge value?

**Comment by dovi5988** [comment]
Josh,

```
mysql> show create table teams\G
*************************** 1. row ***************************
       Table: teams
Create Table: CREATE TABLE `teams` (
  `campaign_id` int NOT NULL,
  `team_id` int NOT NULL,
  `extension` varchar(10) DEFAULT NULL,
  `name` varchar(64) NOT NULL,
  `tts_name` varchar(45) DEFAULT NULL,
  `team_data` json NOT NULL,
  PRIMARY KEY (`campaign_id`,`team_id`),
  KEY `campaign_extension` (`campaign_id`,`extension`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
1 row in set (0.02 sec)

mysql> SELECT * FROM teams where campaign_id = '23277' and team_id = '749616' limit 1\G
*************************** 1. row ***************************
campaign_id: 23277
    team_id: 749616
  extension: NULL
       name: 
   tts_name: NULL
  team_data: {"eur": {"goal": 583, "raised": 33}, "gbp": {"goal": 500, "raised": 28}, "ils": {"goal": 2361, "raised": 132}, "usd": {"goal": 635, "raised": 36}, "goal": 500, "raised": 28}
1 row in set (0.02 sec)
```
What's interesting is if I replace * with all the columns for example
```
readsql=SELECT campaign_id, team_id, team_data, extension, name, tts_name FROM teams where campaign_id = '${SQL_ESC(${ARG1})}' and team_id = '${SQL_ESC(${ARG2})}' limit 1;
```

Then there is no crash. I do however get the error that I am facing at https://community.asterisk.org/t/issues-with-using-odbc-to-query-json-response-from-mysql/100193 (I am not sure if it's related or two separate issues). I actually found this problem accidentally as I was trying to find a work around for the issue that I have listed on the forum.

**Comment by jcolp** [comment]
There is no specific or explicit logic in Asterisk for the json type, so it is entirely possible that is the source of it in both cases.

**Comment by dovi5988** [comment]
@jcolp Would this be considered a bug and can it be fixed in Asterisk? (I am asking as I would put out a bounty for it).

**Comment by jcolp** [comment]
I'm not actively working on this or triaging it further currently. I have no additional information to add and don't know. All I did was look at the backtrace, see the absurdly large length, and then once you gave a schema I looked at the code to see if there was anything JSON specific. Someone else could dig into it if they wanted.

**Comment by dovi5988** [comment]
@jcolp I found a work around which was to use a stored procedure. Closing for now and I will see if I can find someone to work this.
