### ISSUE TITLE
[bug]: Crash when freeing frame

### ISSUE THREAD

**Issue by jiangxc** [asterisk/asterisk#517]
### Severity

Trivial

### Versions

20.0.1

### Components/Modules

N/A

### Operating Environment

Asterisk 20.0.1 on a x86_64 running CentOS Linux release 7.9.2009

### Frequency of Occurrence

Frequent

### Issue Description

I am using AGI to make calls and have implemented a speech recognition module. However, the system crashes every day. I have uploaded the log files for your reference. Could you please take a look and let me know if you can identify the issue? Thank you!

[core-asterisk-2024-01-02T02-03-19Z-brief.txt](https://github.com/asterisk/asterisk/files/13806731/core-asterisk-2024-01-02T02-03-19Z-brief.txt)
[core-asterisk-2024-01-02T02-03-19Z-full.txt](https://github.com/asterisk/asterisk/files/13806732/core-asterisk-2024-01-02T02-03-19Z-full.txt)
[core-asterisk-2024-01-02T02-03-19Z-info.txt](https://github.com/asterisk/asterisk/files/13806733/core-asterisk-2024-01-02T02-03-19Z-info.txt)
[core-asterisk-2024-01-02T02-03-19Z-locks.txt](https://github.com/asterisk/asterisk/files/13806734/core-asterisk-2024-01-02T02-03-19Z-locks.txt)
[core-asterisk-2024-01-02T02-03-19Z-thread1.txt](https://github.com/asterisk/asterisk/files/13806735/core-asterisk-2024-01-02T02-03-19Z-thread1.txt)
[full.log](https://github.com/asterisk/asterisk/files/13806736/full.log)

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jiangxc** [comment]
The call was initiated using the Originate method，originate PJSIP/5001 extension 6000@robot，The call was initiated using the G.729 codec. and I will try using A-law encoding again.

**Comment by jcolp** [comment]
Asterisk version 20.0.1 is also over a year old, and a newer version should be tested too.

**Comment by jiangxc** [comment]
Ok, I will try again after upgrading to 20.5.2.

**Comment by jiangxc** [comment]
I have upgraded to 20.5.2, and the codec order is alaw, ulaw, g729, gsm, g726, but the crash still occurs. I have uploaded the log file. Since the crash occurs at irregular intervals, the full.log file is relatively large. I have extracted some parts of it. If you need me to upload the complete file, please let me know what the problem might be. Thank you.

[core-asterisk-2024-01-05T03-56-30Z-brief.txt](https://github.com/asterisk/asterisk/files/13838426/core-asterisk-2024-01-05T03-56-30Z-brief.txt)
[core-asterisk-2024-01-05T03-56-30Z-full.txt](https://github.com/asterisk/asterisk/files/13838427/core-asterisk-2024-01-05T03-56-30Z-full.txt)
[core-asterisk-2024-01-05T03-56-30Z-info.txt](https://github.com/asterisk/asterisk/files/13838428/core-asterisk-2024-01-05T03-56-30Z-info.txt)
[core-asterisk-2024-01-05T03-56-30Z-locks.txt](https://github.com/asterisk/asterisk/files/13838429/core-asterisk-2024-01-05T03-56-30Z-locks.txt)
[core-asterisk-2024-01-05T03-56-30Z-thread1.txt](https://github.com/asterisk/asterisk/files/13838430/core-asterisk-2024-01-05T03-56-30Z-thread1.txt)
[Uploading full.log…]()

**Comment by jcolp** [comment]
I still see a line about setting up a translation path involving the outside g729 module. Please remove the module and ensure that g729 is NOT used:

[Jan  5 11:56:30] DEBUG[14549][C-000000f9] channel.c: Channel PJSIP/t60111111-000002a9 setting write format path: slin -> g729

That module must be eliminated as a possible source of issue.

**Comment by jiangxc** [comment]
Okay, I will try again after deleting g729 from the allow column in the table ps_endpoints.

**Comment by jiangxc** [comment]
I have uninstalled the external g729 plugin，set allow=alaw,ulaw,gsm,g726, and now it crashes again. Could you please take a look and let me know what's going on? Thank you very much.
`
asterisk -rx "module show like g729"
Module                         Description                              Use Count  Status      Support Level
codec_g729a.so                 Digium G.729 Annex A Codec (optimized fo 0          Running          extended
format_g729.so                 Raw G.729 data                           0          Running              core
res_format_attr_g729.so        G.729 Format Attribute Module            1          Running              core
3 modules loaded
`

[core-asterisk-2024-01-09T10-23-38Z-brief.txt](https://github.com/asterisk/asterisk/files/13873179/core-asterisk-2024-01-09T10-23-38Z-brief.txt)
[core-asterisk-2024-01-09T10-23-38Z-full.txt](https://github.com/asterisk/asterisk/files/13873180/core-asterisk-2024-01-09T10-23-38Z-full.txt)
[core-asterisk-2024-01-09T10-23-38Z-info.txt](https://github.com/asterisk/asterisk/files/13873181/core-asterisk-2024-01-09T10-23-38Z-info.txt)
[core-asterisk-2024-01-09T10-23-38Z-locks.txt](https://github.com/asterisk/asterisk/files/13873182/core-asterisk-2024-01-09T10-23-38Z-locks.txt)
[core-asterisk-2024-01-09T10-23-38Z-thread1.txt](https://github.com/asterisk/asterisk/files/13873183/core-asterisk-2024-01-09T10-23-38Z-thread1.txt)
[full.log](https://github.com/asterisk/asterisk/files/13873184/full.log)

**Comment by jcolp** [comment]
It's memory corruption. What further complicates things (and something I didn't notice before) is that you're using a second third party module, one for speech recognition. We've received no other reports of such things that I can see. Does this only occur when speech recognition is done?

**Comment by jiangxc** [comment]
yes,I use the scene of originate to initiate a call,  then there is a res plugin that listens to voice data, and then sends voice data through websocket to the voice recognition end, the code is as follows,thanks!
[resspeech.txt](https://github.com/asterisk/asterisk/files/13873626/resspeech.txt)

**Comment by jcolp** [comment]
That is outside code that I will not look at. My question was strictly - does it only happen when SpeechRecognize is being done? That would most likely isolate it to that, or in some way the outside module.

**Comment by jiangxc** [comment]
Okay, thank you. I have only used this scenario so far. I will check it again. Thank you once again.

**Comment by jcolp** [comment]
@jiangxc Have you confirmed that this only happens in SpeechRecognize with this outside module?

**Comment by asteriskteam** [comment]
This issue has been marked stale because it has been open 7 days with no feedback. Please provide feedback within 7 days or this issue will be closed.

**Comment by asteriskteam** [comment]
This issue has been closed because it has been open 14 days with no feedback.
