### ISSUE TITLE
[bug]: queue unable to break out if playing announcement

### ISSUE THREAD

**Issue by macocheung** [asterisk/asterisk#543]
### Severity

Trivial

### Versions

18

### Components/Modules

app_queue

### Operating Environment

Debian

### Frequency of Occurrence

None

### Issue Description

I have set the ivr breakout menu in Queue, press 8 will break-out the queue and go to voicemail, but it doesn't work when there are more than 1 caller waiting in queue, and playing position announcement to caller, when press 8, it just stop the position announcement and return to moh.

I have traced the app_queue.c, I found that "res" will get 1 no matter what  I pressed.

![image](https://github.com/asterisk/asterisk/assets/5525407/7a037d9e-3110-41ba-a27f-9d0d7154cbae)

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Please provide the complete configuration you are using including the dialplan you are breaking out into and queue configuration, as well as a debug log: https://docs.asterisk.org/Operation/Logging/Collecting-Debug-Information/?h=collecting
