### ISSUE TITLE
Compile Error since 21.x and 20.6  --- 20.5.2 is ok

### ISSUE THREAD

**Issue by walter59** [asterisk/asterisk#554]
### Severity

Critical

### Versions

20.6.* - 

### Components/Modules

compile

### Operating Environment

linux , gentto base 

kernel 6.8_rc1 
before 6.7,1 --- same problems

### Frequency of Occurrence

None

### Issue Description

error compile 21.x and 20.6.*
version 20.5.2 works fine
./configure: line 11294: syntax error near unexpected token `ALSA_DESCRIP="Advanced Linux Sound Architecture"'
./configure: line 11294: `    ALSA_DESCRIP="Advanced Linux Sound Architecture"'

error 

### Relevant log output

```shell
./configure: line 11294: syntax error near unexpected token `ALSA_DESCRIP="Advanced Linux Sound Architecture"'
./configure: line 11294: `    ALSA_DESCRIP="Advanced Linux Sound Architecture"'
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
What version is your configure output from? It doesn't seem to match either. What are the complete steps used to build Asterisk? Is it unmodified from the tarball as distributed? Is it patched?

**Comment by jcolp** [comment]
And what is the complete configure output up to that point?

**Comment by jkroonza** [comment]
I can reproduce for 20.6, looking into the cause now.

```
checking for OPENSSL... yes
./configure: line 11294: syntax error near unexpected token `ALSA_DESCRIP="Advanced Linux Sound Architecture"'
./configure: line 11294: `    ALSA_DESCRIP="Advanced Linux Sound Architecture"'
```

More likely than not this is a Gentoo specific problem though.

**Comment by jkroonza** [comment]
```
11280     LIBJWT_CONFIGURE()
11281 
11282 
11283 # AST_EXT_LIB_SETUP is used to tell configure to handle variables for
11284 # various packages.
11285 # $1 is the prefix for the variables in makeopts and autoconfig.h
11286 # $2 is the short comment, $4 is the long comment
11287 # $3 is the name used in --with- or --without- flags for configure.
11288 #
11289 # Package option names should be in alphabetical order
11290 # by the --with option name (the third field),
11291 # to make things easier for the users.
11292 
11293 
11294     ALSA_DESCRIP="Advanced Linux Sound Architecture"
11295     ALSA_OPTION="asound"
11296     PBX_ALSA=0
```

**Comment by jkroonza** [comment]
This is a problem in the asterisk ebuild due to changes w.r.t. libjwt, needs to be brought in line on gentoo side, I'll action, I'll tag you on the PR.
