### ISSUE TITLE
[bug]: res_pjsip_t38.c: Potential IP family mismatch

### ISSUE THREAD

**Issue by seanbright** [asterisk/asterisk#558]
### Severity

Trivial

### Versions

master

### Components/Modules

res_pjsip_t38

### Operating Environment

Irrelevant

### Frequency of Occurrence

None

### Issue Description

It appears to me that the last argument to this `ast_sockaddr_resolve(...)` call should be `AST_AF_UNSPEC` but I am unsure:

https://github.com/asterisk/asterisk/blob/f4845f756f27952eb16229abcc930c4b16b0e884/res/res_pjsip_t38.c#L886-L898

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Looking at the code, I believe you are correct.
