### ISSUE TITLE
[bug]: EndIf() causes next priority to be skipped

### ISSUE THREAD

**Issue by silvaalex2021** [asterisk/asterisk#560]
### Severity

Major

### Versions

20.6.0, 21.1.0

### Components/Modules

app_if

### Operating Environment

Debian 12.04

### Frequency of Occurrence

Constant

### Issue Description

When running an ‘if’ branch where the expression result was true (see dialplan from priority 25 onwards), upon reaching ‘EndIf()’ (priority 28), the log shows that Asterisk is jumping to priority 29 and continuing execution from there. However, priority 29 (ConfBridge()) is never executed, going straight to priority 30 where a block of ‘GotoIf()’ begins, causing a loop because there is a ‘Goto’ pointing to the label “ENTRASAL1” up above.

### Relevant log output

[dialplan.txt](https://github.com/asterisk/asterisk/files/14075887/dialplan.txt)
[debug-log.txt](https://github.com/asterisk/asterisk/files/14075888/debug-log.txt)

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by InterLinked1** [comment]
@jcolp You can assign this to me.
