### ISSUE TITLE
[bug]: Application Read() returns immediately

### ISSUE THREAD

**Issue by btriller** [asterisk/asterisk#565]
### Severity

Major

### Versions

20.6

### Components/Modules

app_read

### Operating Environment

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
```

### Frequency of Occurrence

Constant

### Issue Description

Application `Read(read_pin,,4)` returns immediately to dial plan without waiting for digits.
This worked in 20.5.2.
[Test](https://github.com/asterisk/testsuite/blob/master/tests/apps/read/test-config.yaml) also fails.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by InterLinked1** [comment]
I actually received a report of this as well, but hadn't had time to investigate yet.

**Comment by jcolp** [comment]
It's the change from issue #172

**Comment by jcolp** [comment]
I think it's a behavior difference between strsep and ast_strsep, in the ast_strsep case I think it is returning NULL which is skipping the logic, instead of returning a pointer to "".

**Comment by jcolp** [comment]
Yeah, that seems to be the case and the logic is explicitly written as such, doesn't seem to be documented. I think ast_strsep should return NULL if passed NULL, but if it is passed an empty string it should return the empty string will match strsep behavior.

**Comment by seanbright** [comment]
So you’re suggesting modifying `ast_strsep(…)` as a resolution?

**Comment by jcolp** [comment]
Yes, I think it should behave the same as strsep in that case.

**Comment by jcolp** [comment]
Maybe something as simple as having it return "st" instead of NULL, for the case where it is passed a NULL or empty string...

**Comment by jcolp** [comment]
Pull request is up which makes the behavior match, and resolves this issue. Give it a whirl.

**Comment by lukaszMaster** [comment]
I observed the same behavior on 18.21.0. The trick was to fill in the second parameter (name of sound file). After that 'Read' started to wait for digits.
