### ISSUE TITLE
[bug]: The "restrict" keyword used in chan_iax2.c isn't supported in older gcc versions

### ISSUE THREAD

**Issue by gtjoseph** [asterisk/asterisk#586]
### Severity

Major

### Versions

18.21.0,20.6.0,21.1.0

### Components/Modules

chan_iax2

### Operating Environment

GCC versions <= 4.9

### Frequency of Occurrence

None

### Issue Description

Commit 59bc6ceb61cacd4f751b made use of the `restrict` keyword in the definition of the new `auth_method_names` function but that keyword isn't supported in gcc versions <= 4.9 unless the `-std=gnu99` flag is used (which it isn't by default).  This causes compilation to fail in distros like CentOS7 which have only gcc 4.8 available.

The work around is to add the flag when running ./configure:
```
$ ./configure --with-jansson-bundled CFLAGS=-std=gnu99
```

### Relevant log output

```shell
[CC] chan_iax2.c → chan_iax2.o
chan_iax2.c:418:64: error: expected ‘;’, ‘,’ or ‘)’ before ‘buf’
static char *auth_method_names(int authmethods, char *restrict buf)
^
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by gtjoseph** [comment]
@InterLinked1 Can you create a PR to remove the restrict keyword?

**Comment by InterLinked1** [comment]
> @InterLinked1 Can you create a PR to remove the restrict keyword?

Yeah, I can... but would it be fine to detect the GCC version and keep restrict if it's >= 4.9?
I want to say I've seen restrict used a few other places in the codebase as well...

**Comment by InterLinked1** [comment]
Actually, I'm leaning more towards having configure check for restrict availability, or at least some kind of macro that could be used automatically to either restrict or no op, like we do for some other things. What do you think?

**Comment by jcolp** [comment]
That is generally the best approach, checking for availability instead of versioning and making it optional.
