### ISSUE TITLE
[bug]: segfault in libasteriskpj.so.2 when using recording button on Sangoma Phones D-Series

### ISSUE THREAD

**Issue by otonedv** [asterisk/asterisk#591]
### Severity

Critical

### Versions

20.6.0,21.1.0

### Components/Modules

libasteriskpj.so.2

### Operating Environment

Ubuntu 22.0.4 with latest patches

### Frequency of Occurrence

Constant

### Issue Description

When pressing the record key on the phone (D40,D50,D60 and D70) it causes asterisk to crash with a segfault in the libasteriskpj.so.2. We are using the latest firmware 2.9.26 on the phones and latest DPMA version 3.6.7. In Asterisk 18 everything works as expected. The recording via *1 is fully functional. The error occurs with minimal asterisk config (make basic-pbx) and using minimal res_digium_phone.conf with record_own_calls=yes.

### Relevant log output

```shell
asterisk kernel: [ 4674.836869] asterisk[3050]: segfault at 82 ip 00007f7f6f086bb0 sp 00007f7f54093940 error 4 in libasteriskpj.so.2[7f7f6f003000+108000]
asterisk kernel: [ 4674.836890] Code: 48 c7 83 d8 02 00 00 00 00 00 00 eb ae 41 89 c4 44 89 e0 5b 5d 41 5c c3 f3 0f 1e fa 53 48 89 fb e8 f5 79 f8 ff 83 f8 05 7f 1c <48> 8b 7b 48 e8 17 71 f8 ff 83 83 c8 02 00 00 01 e8 db 79 f8 ff 83
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Thank you for the crash report. However, we need more information to investigate the crash. Please provide:

1. A backtrace generated from a core dump using the instructions provided on the Asterisk wiki [1].

Thanks!

As well, in the future it is ideal to raise such issues through Sangoma technical support. DPMA, and phones, are a commercial product of Sangoma and not part of the open source project.

I would also ask - when installing DPMA for each version, you are changing to the DPMA build for that version, correct?

[1]: https://docs.asterisk.org/Development/Debugging/Getting-a-Backtrace/?h=getting

**Comment by jcolp** [comment]
And did this just start happening from a minor version upgrade?

**Comment by otonedv** [comment]
We've tried generating a coredump with the safe_asterisk script but it did not wrote anything as the segfault occurred.
Yes, we were using the dpma for the specified asterisk version. Even in a fresh minimal install of asterisk 20.6.0 the error is present.

**Comment by gtjoseph** [comment]
Nevermind.  We found the issue.  There will be new res_digium_phone versions pushed up later today.

**Comment by gtjoseph** [comment]
@otonedv Version 3.6.8 of res_digium_phone are now available at:

https://downloads.digium.com/pub/telephony/res_digium_phone/asterisk-18.0/x86-64/
https://downloads.digium.com/pub/telephony/res_digium_phone/asterisk-20.0/x86-64/
https://downloads.digium.com/pub/telephony/res_digium_phone/asterisk-21.0/x86-64/

If you've used menuselect to enable the res_digium_phone external module, the next time you do a `make install`, you'll get the new version.

If you still have a problem, you can re-open this issue.

**Comment by otonedv** [comment]
Thank you for your fast support! Everything works like a charm now!
