### ISSUE TITLE
[bug]: ps_aors table inconsistency

### ISSUE THREAD

**Issue by viktike** [asterisk/asterisk#617]
### Severity

Minor

### Versions

master

### Components/Modules

ast-db-manage

### Operating Environment

MySQL 8

### Frequency of Occurrence

Constant

### Issue Description

After executing all alembic migrations in contrib/ast-db-manage, the ps_aors table has inconsistency between remove_unavailable and remove_existing fields. The possible enum values doesn't match. 

### Relevant log output

```shell
mysql> SHOW COLUMNS FROM ps_aors LIKE 'remove_%';
+--------------------+----------------------------------------------------+------+-----+---------+-------+
| Field              | Type                                               | Null | Key | Default | Extra |
+--------------------+----------------------------------------------------+------+-----+---------+-------+
| remove_existing    | enum('yes','no')                                   | YES  |     | NULL    |       |
| remove_unavailable | enum('0','1','off','on','false','true','no','yes') | YES  |     | NULL    |       |
+--------------------+----------------------------------------------------+------+-----+---------+-------+
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by seanbright** [comment]
There are many more inconsistencies than just the provided examples:

```
SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE DATA_TYPE = 'enum'
    AND TABLE_NAME LIKE 'ps_%'
    AND COLUMN_TYPE LIKE '%yes%'
```

| TABLE\_NAME | COLUMN\_NAME | COLUMN\_TYPE |
| :--- | :--- | :--- |
| ps\_asterisk\_publications | device\_state | enum\('yes','no'\) |
| ps\_asterisk\_publications | mailbox\_state | enum\('yes','no'\) |
| ps\_subscription\_persistence | prune\_on\_boot | enum\('yes','no'\) |
| ps\_systems | compact\_headers | enum\('yes','no'\) |
| ps\_systems | disable\_tcp\_switch | enum\('yes','no'\) |
| ps\_systems | follow\_early\_media\_fork | enum\('yes','no'\) |
| ps\_systems | accept\_multiple\_sdp\_answers | enum\('yes','no'\) |
| ps\_systems | disable\_rport | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_resource\_list | full\_state | enum\('yes','no'\) |
| ps\_resource\_list | resource\_display\_name | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_globals | disable\_multi\_domain | enum\('yes','no'\) |
| ps\_globals | mwi\_disable\_initial\_unsolicited | enum\('yes','no'\) |
| ps\_globals | ignore\_uri\_user\_options | enum\('yes','no'\) |
| ps\_globals | use\_callerid\_contact | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_globals | send\_contact\_status\_on\_update\_registration | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_globals | norefersub | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_globals | allow\_sending\_180\_after\_183 | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_globals | all\_codecs\_on\_empty\_reinvite | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_aors | remove\_existing | enum\('yes','no'\) |
| ps\_aors | authenticate\_qualify | enum\('yes','no'\) |
| ps\_aors | support\_path | enum\('yes','no'\) |
| ps\_aors | remove\_unavailable | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_contacts | authenticate\_qualify | enum\('yes','no'\) |
| ps\_contacts | prune\_on\_boot | enum\('yes','no'\) |
| ps\_endpoint\_id\_ips | srv\_lookups | enum\('yes','no'\) |
| ps\_endpoints | direct\_media | enum\('yes','no'\) |
| ps\_endpoints | disable\_direct\_media\_on\_nat | enum\('yes','no'\) |
| ps\_endpoints | force\_rport | enum\('yes','no'\) |
| ps\_endpoints | ice\_support | enum\('yes','no'\) |
| ps\_endpoints | rewrite\_contact | enum\('yes','no'\) |
| ps\_endpoints | rtp\_ipv6 | enum\('yes','no'\) |
| ps\_endpoints | rtp\_symmetric | enum\('yes','no'\) |
| ps\_endpoints | send\_diversion | enum\('yes','no'\) |
| ps\_endpoints | send\_pai | enum\('yes','no'\) |
| ps\_endpoints | send\_rpid | enum\('yes','no'\) |
| ps\_endpoints | timers | enum\('forced','no','required','yes'\) |
| ps\_endpoints | 100rel | enum\('no','required','peer\_supported','yes'\) |
| ps\_endpoints | aggregate\_mwi | enum\('yes','no'\) |
| ps\_endpoints | trust\_id\_inbound | enum\('yes','no'\) |
| ps\_endpoints | trust\_id\_outbound | enum\('yes','no'\) |
| ps\_endpoints | use\_ptime | enum\('yes','no'\) |
| ps\_endpoints | use\_avpf | enum\('yes','no'\) |
| ps\_endpoints | inband\_progress | enum\('yes','no'\) |
| ps\_endpoints | fax\_detect | enum\('yes','no'\) |
| ps\_endpoints | t38\_udptl | enum\('yes','no'\) |
| ps\_endpoints | t38\_udptl\_nat | enum\('yes','no'\) |
| ps\_endpoints | t38\_udptl\_ipv6 | enum\('yes','no'\) |
| ps\_endpoints | one\_touch\_recording | enum\('yes','no'\) |
| ps\_endpoints | allow\_transfer | enum\('yes','no'\) |
| ps\_endpoints | allow\_subscribe | enum\('yes','no'\) |
| ps\_endpoints | srtp\_tag\_32 | enum\('yes','no'\) |
| ps\_endpoints | force\_avp | enum\('yes','no'\) |
| ps\_endpoints | media\_use\_received\_transport | enum\('yes','no'\) |
| ps\_endpoints | user\_eq\_phone | enum\('yes','no'\) |
| ps\_endpoints | moh\_passthrough | enum\('yes','no'\) |
| ps\_endpoints | media\_encryption\_optimistic | enum\('yes','no'\) |
| ps\_endpoints | rpid\_immediate | enum\('yes','no'\) |
| ps\_endpoints | g726\_non\_standard | enum\('yes','no'\) |
| ps\_endpoints | bind\_rtp\_to\_media\_address | enum\('yes','no'\) |
| ps\_endpoints | mwi\_subscribe\_replaces\_unsolicited | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_endpoints | preferred\_codec\_only | enum\('yes','no'\) |
| ps\_endpoints | asymmetric\_rtp\_codec | enum\('yes','no'\) |
| ps\_endpoints | rtcp\_mux | enum\('yes','no'\) |
| ps\_endpoints | allow\_overlap | enum\('yes','no'\) |
| ps\_endpoints | refer\_blind\_progress | enum\('yes','no'\) |
| ps\_endpoints | notify\_early\_inuse\_ringing | enum\('yes','no'\) |
| ps\_endpoints | webrtc | enum\('yes','no'\) |
| ps\_endpoints | bundle | enum\('yes','no'\) |
| ps\_endpoints | dtls\_auto\_generate\_cert | enum\('yes','no'\) |
| ps\_endpoints | follow\_early\_media\_fork | enum\('yes','no'\) |
| ps\_endpoints | accept\_multiple\_sdp\_answers | enum\('yes','no'\) |
| ps\_endpoints | suppress\_q850\_reason\_headers | enum\('yes','no'\) |
| ps\_endpoints | trust\_connected\_line | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_endpoints | send\_connected\_line | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_endpoints | ignore\_183\_without\_sdp | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_endpoints | send\_history\_info | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_endpoints | stir\_shaken | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_endpoints | allow\_unauthenticated\_options | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_endpoints | t38\_bind\_udptl\_to\_media\_address | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_endpoints | send\_aoc | enum\('0','1','off','on','false','true','no','yes'\) |
| ps\_outbound\_publishes | multi\_user | enum\('yes','no'\) |
| ps\_transports | require\_client\_cert | enum\('yes','no'\) |
| ps\_transports | verify\_client | enum\('yes','no'\) |
| ps\_transports | verify\_server | enum\('yes','no'\) |
| ps\_transports | allow\_reload | enum\('yes','no'\) |
| ps\_transports | symmetric\_transport | enum\('yes','no'\) |
| ps\_transports | allow\_wildcard\_certs | enum\('yes','no'\) |
| ps\_registrations | auth\_rejection\_permanent | enum\('yes','no'\) |
| ps\_registrations | support\_path | enum\('yes','no'\) |
| ps\_registrations | line | enum\('yes','no'\) |

**Comment by seanbright** [comment]
It looks like the `enum('0','1','off','on','false','true','no','yes')` was introduced in [this commit](https://github.com/asterisk/asterisk/commit/d60411a2b498f7d4cd2c9e785be847944727e01d) due to [ASTERISK-27988](https://issues-archive.asterisk.org/ASTERISK-27988), and others (myself included) carried it forward from there.

An integer (or bit) type would have been better from the get-go, but that ship has sailed.

A PR that moved everything to the more "permissive" enum definition doesn't seem unreasonable to me.

**Comment by jcolp** [comment]
@seanbright Agreed about moving to the more permissive definition.
