### ISSUE TITLE
[bug]: shared variables mostly fail to work when using prefix method 

### ISSUE THREAD

**Issue by tekach** [asterisk/asterisk#621]
### Severity

Minor

### Versions

asterisk 18.21

### Components/Modules

SHARED

### Operating Environment

Centos

### Frequency of Occurrence

Frequent

### Issue Description

I am getting very inconsistent results when trying to use SHARED() with prefix [(as described in docs).](https://docs.asterisk.org/Asterisk_16_Documentation/API_Documentation/Dialplan_Functions/SHARED/?h=shared%28%29) It mostly doesn't work (cca 90%), but then again, rarely it does.

I am trying to pass a channel variables of call1 to another, parallel call2 while call1 is on hold.

Excerpts of my dialplan:

```
[ECHOUDIAL] ; subroutine called with Dial U option, call1
exten => s,1,NoOp(UDIAL triggered ON CONNECT, DIALED party)
exten => s,n,NoOp(CHANNEL is ${CHANNEL})
exten => s,n,NoOp(CUT CHANNEL is ${CUT(CHANNEL,-,1)})
exten => s,n,Set(SHARED(ECHOVARPREFIX,${CUT(CHANNEL,-,1)})=ECHOUDIAL)
exten => s,n,Set(GLOBAL(TESTCHANNELNAME)=${CHANNEL})
exten => s,n,NoOp(SHARED ECHOVARPREFIX is ${SHARED(ECHOVARPREFIX)})
exten => s,n,Return()

[macro-dialout-one-predial-hook] ;macro called before a new, parallel call2 while call1 being on hold
exten => s,1,NoOp(MACRO DIALOUT ONE PREDIAL HOOK)
exten => s,n,NoOp(CHANNEL is ${CHANNEL})
exten => s,n,NoOp(CUT CHANNEL is ${CUT(CHANNEL,-,1)})
exten => s,n,NoOp(SHARED ECHOVARPREFIX is ${SHARED(ECHOVARPREFIX,${CUT(CHANNEL,-,1)})})
exten => s,n,NoOp(Test channel name is ${GLOBAL(TESTCHANNELNAME)})
exten => s,n,NoOp(Test channel exists: ${CHANNEL_EXISTS(${GLOBAL(TESTCHANNELNAME)})})
exten => s,n(exit),MacroExit()
```

### Relevant log output

```shell
WHEN IT DOESNT WORK:
;UDIAL PART FOR CALL1
    -- SIP/1002-00000076 Internal Gosub(ECHOUDIAL,s,1) start
    -- Executing [s@ECHOUDIAL:1] NoOp("SIP/1002-00000076", "UDIAL triggered ON CONNECT, DIALED party") in new stack
    -- Executing [s@ECHOUDIAL:2] NoOp("SIP/1002-00000076", "CHANNEL is SIP/1002-00000076") in new stack
    -- Executing [s@ECHOUDIAL:3] NoOp("SIP/1002-00000076", "CUT CHANNEL is SIP/1002") in new stack
    -- Executing [s@ECHOUDIAL:4] Set("SIP/1002-00000076", "SHARED(ECHOVARPREFIX,SIP/1002)=ECHOUDIAL") in new stack
    -- Executing [s@ECHOUDIAL:5] Set("SIP/1002-00000076", "GLOBAL(TESTCHANNELNAME)=SIP/1002-00000076") in new stack
  == Setting global variable 'TESTCHANNELNAME' to 'SIP/1002-00000076'
    -- Executing [s@ECHOUDIAL:6] NoOp("SIP/1002-00000076", "SHARED ECHOVARPREFIX is ECHOUDIAL") in new stack
    -- Executing [s@ECHOUDIAL:7] Return("SIP/1002-00000076", "") in new stack

;PREDIAL PART FOR CALL2
    -- Executing [s@macro-dialout-one-predial-hook:1] NoOp("SIP/1002-00000077", "MACRO DIALOUT ONE PREDIAL HOOK") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:2] NoOp("SIP/1002-00000077", "CHANNEL is SIP/1002-00000077") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:3] NoOp("SIP/1002-00000077", "CUT CHANNEL is SIP/1002") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:4] NoOp("SIP/1002-00000077", "SHARED ECHOVARPREFIX is ") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:5] NoOp("SIP/1002-00000077", "SHARED ECHOVARPREFIX2 is ") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:6] NoOp("SIP/1002-00000077", "Test channel name is SIP/1002-00000076") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:7] NoOp("SIP/1002-00000077", "Test channel exists: 1") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:8] MacroExit("SIP/1002-00000077", "") in new stack

WHEN IT WORKS:
;UDIAL PART FOR CALL1
  -- SIP/1002-00000088 Internal Gosub(ECHOUDIAL,s,1) start
    -- Executing [s@ECHOUDIAL:1] NoOp("SIP/1002-00000088", "UDIAL triggered ON CONNECT, DIALED party") in new stack
    -- Executing [s@ECHOUDIAL:2] NoOp("SIP/1002-00000088", "CHANNEL is SIP/1002-00000088") in new stack
    -- Executing [s@ECHOUDIAL:3] NoOp("SIP/1002-00000088", "CUT CHANNEL is SIP/1002") in new stack
    -- Executing [s@ECHOUDIAL:4] Set("SIP/1002-00000088", "SHARED(ECHOVARPREFIX,SIP/1002)=ECHOUDIAL") in new stack
    -- Executing [s@ECHOUDIAL:5] Set("SIP/1002-00000088", "GLOBAL(TESTCHANNELNAME)=SIP/1002-00000088") in new stack
  == Setting global variable 'TESTCHANNELNAME' to 'SIP/1002-00000088'
    -- Executing [s@ECHOUDIAL:6] NoOp("SIP/1002-00000088", "SHARED ECHOVARPREFIX is ECHOUDIAL") in new stack
    -- Executing [s@ECHOUDIAL:7] Return("SIP/1002-00000088", "") in new stack
  == Spawn extension (macro-dial-one, s, 1) exited non-zero on 'SIP/1002-00000088'

;PREDIAL PART FOR CALL2
    -- Executing [s@macro-dialout-one-predial-hook:1] NoOp("SIP/1002-00000089", "MACRO DIALOUT ONE PREDIAL HOOK") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:2] NoOp("SIP/1002-00000089", "CHANNEL is SIP/1002-00000089") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:3] NoOp("SIP/1002-00000089", "CUT CHANNEL is SIP/1002") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:4] NoOp("SIP/1002-00000089", "SHARED ECHOVARPREFIX is ") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:5] NoOp("SIP/1002-00000089", "SHARED ECHOVARPREFIX2 is ECHOUDIAL") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:6] NoOp("SIP/1002-00000089", "Test channel name is SIP/1002-00000088") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:7] NoOp("SIP/1002-00000089", "Test channel exists: 1") in new stack
    -- Executing [s@macro-dialout-one-predial-hook:8] MacroExit("SIP/1002-00000089", "") in new stack
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Please provide a complete dialplan for reproducing this issue and step by step instructions.

**Comment by tekach** [comment]
Thanks for super-fast response.

Full dialplan will be super huge and bloated as it is Freepbx-based. :/

Please advise.

**Comment by jcolp** [comment]
Then I would suggest coming up with non-FreePBX dialplan to show your issue and reproduce it. If not possible then we may or may not be able to reproduce it. This is why on issues like this I always ask for dialplan to reproduce it, because otherwise it can end up with us assuming things that are incorrect.

**Comment by tekach** [comment]
I am afraid I am not proficient enough to set everything needed for this test from scratch. 

Can I kindly and really pretty ask to try to reproduce it? Its about setting one SHARED var with prefix on channel A then try to use/read it on channel B while channel A is on hold.

Not sure if subroutines matter. They should not, to my understanding.

If that is not possible, I'll try my best to put something together, it might take a month though :-D

**Comment by jcolp** [comment]
I think I actually understand what is going on. If multiple channels exist that would match the prefix, there is no guarantee of the channel you will query. Only with a single channel are you guaranteed to get that single channel. It is dependent on the storage and hashing of the channel. This is why it sometimes works. The rest of the time it ends up querying the wrong channel, which doesn't have the value on it. I don't think it's a bug, and I'm not even sure you could really "fix" such a thing. The documentation could be updated to be explicit about the behavior.

**Comment by tekach** [comment]
Thanks for your thoughts.

What would be the point of func SHARED with prefix if not behavior where, once set, SHARED var is accessible to all channels that match a prefix?

**Comment by jcolp** [comment]
I don't know, such functionality is over 15 years old so I don't know the original intention or if that was considered. It could have been back in that period of time the channel ordering was predictable. Even then once that channel went away, the shared information would be gone from it and you'd end up looking at a different channel.

The way SHARED works is that the information is stored on each channel, and reading a variable using SHARED goes to a channel and gets the information. Either the same channel, a channel name you specify, or it finds one by prefix.

**Comment by tekach** [comment]
Based on logic and docs, I understood the SHARED is "a shared variable area, in which you may share variables between channels., meaning that it is not really channel based, but shared between all channels in scope.

Of course, when the channel that set SHARED in the first place gets destroyed, so does it's SHARED var.

Docs also mention a potential race condition between channels that are in scope of SHARED var, which makes sense if things are as described above.

But maybe I misunderstood the whole concept.

Or there is a bug. 😉

**Comment by jcolp** [comment]
SHARED is not shared between all channels in scope, they are variables defined on the channel but in a separate namespace on the channel behind the SHARED name to force you to realize that they can change underneath you. From looking at the history, that has always been the case. Documentation could certainly be improved to be explicit about it.

**Comment by tekach** [comment]
If you need to set UID or use channel name explicitly, why the prefix option and how should it work?

I am not challenging you, just wondering and trying to understand the concept.

**Comment by jcolp** [comment]
If you have a single channel, then it would work so I suspect that was the original usage - but the only information I have to go on is the history of the project from 15+ years ago which is not detailed. I also don't know how others use it (if they do - it may be something that in practice noone uses).

**Comment by tekach** [comment]
Would it be possible to understand the intended behavior from source code? Prefix is there as well but my I can't read / understand the code.

**Comment by jcolp** [comment]
I'm not sure what you mean. If a channel (or prefix) is specified the code tries to get a channel to access its shared variable namespace based on name, if that fails then it falls back to retrieving a channel based on prefix. The method it uses for prefix has never been documented to be deterministic.

Beyond that there's nothing I can see as to intentions or goal of prefix in the implementation.

**Comment by tekach** [comment]
I believe it is down to me misunderstanding the concept then.

It would be a nice (and way more useful) feature for prefixes to work as I *thought* they do.

Thank you for your continued help and support. I believe this ticket can be closed.
