### ISSUE TITLE
[bug]: Park() application does not continue execution if lot is full

### ISSUE THREAD

**Issue by lukeescude** [asterisk/asterisk#624]
### Severity

Minor

### Versions

20.6.0

### Components/Modules

res_parking

### Operating Environment

Debian 12 x64

### Frequency of Occurrence

None

### Issue Description

When attempting to Park() and the lot is full, I believe (according to the documentation at least) that dial plan should continue to the next line - however, it's hanging up the call instead.

There is actually no way (that I've found so far) to know if a parking lot is full either, so it seems impossible to handle scenarios where a lot is full.

Steps to recreate: Set up a parking lot with 1 space, call into it to occupy it. Then, attempt to call into it with a separate device, and the call will hang up rather than continue execution.

### Relevant log output

```shell
[Feb 27 21:11:18] NOTICE[34629][C-00000042]: parking/parking_bridge.c:148 generate_parked_user: Failed to get parking space in lot 'park-9b6e40cd-2549-4b9a-99bb-9f4fed979bc4'. All full.
  == Spawn extension (park-9b6e40cd-2549-4b9a-99bb-9f4fed979bc4, s, 6) exited non-zero on 'PJSIP/external-kamailio-00000054'
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by InterLinked1** [comment]
> Hmm you're right, maybe I saw it anecdotally. Someone else reported the issue a while back here:
> 
> http://lists.digium.com/pipermail/asterisk-dev/2018-December/077144.html

Thanks, I was just curious if it said something in particular was supposed to be done, which doesn't seem to be the case.

> I suppose it's just strange to simply hang up the call when the parking lot is full - but the docs don't actually mention it, so maybe it's intended behavior?

I doubt it... it doesn't seem like proper behavior to me, either, and the module's author agreed in that link, too.

If you do something like this, do you find this to be reasonable behavior?

```
diff --git a/res/parking/parking_applications.c b/res/parking/parking_applications.c
index 7d11516a1e..5353a466cd 100644
--- a/res/parking/parking_applications.c
+++ b/res/parking/parking_applications.c
@@ -567,7 +567,7 @@ static int park_app_exec(struct ast_channel *chan, const char *data)
        RAII_VAR(struct ast_bridge *, parking_bridge, NULL, ao2_cleanup);

        struct ast_bridge_features chan_features;
-       int res;
+       int res = 0;
        int silence_announcements = 0;
        int blind_transfer;

@@ -590,16 +590,16 @@ static int park_app_exec(struct ast_channel *chan, const char *data)
        }

        /* Initialize bridge features for the channel. */
-       res = ast_bridge_features_init(&chan_features);
-       if (res) {
+       if ((res = ast_bridge_features_init(&chan_features))
+               || ast_bridge_join(parking_bridge, chan, NULL, &chan_features, NULL, 0)) { /* Now for the fun part... park it! */
+               if (!silence_announcements && !blind_transfer) {
+                       ast_stream_and_wait(chan, "pbx-parkingfailed", "");
+               }
                ast_bridge_features_cleanup(&chan_features);
                publish_parked_call_failure(chan);
-               return -1;
+               return res;
        }

-       /* Now for the fun part... park it! */
-       ast_bridge_join(parking_bridge, chan, NULL, &chan_features, NULL, 0);
-
```

**Comment by lukeescude** [comment]
Oh thanks man, testing this today!!

**Comment by lukeescude** [comment]
Naveen, your patch works perfectly - However, for the official PR, I would suggest removing the following:

```
if (!silence_announcements && !blind_transfer) {
	ast_stream_and_wait(chan, "pbx-parkingfailed", "");
}
```

as there may be users (like us) that don't use any of Asterisk's recordings, and it causes the Park application to fail when pbx-parkingfailed is not found.

**Comment by InterLinked1** [comment]
> Naveen, your patch works perfectly - However, for the official PR, I would suggest removing the following:
> 
> ```
> if (!silence_announcements && !blind_transfer) {
> 	ast_stream_and_wait(chan, "pbx-parkingfailed", "");
> }
> ```
> 
> as there may be users (like us) that don't use any of Asterisk's recordings, and it causes the Park application to fail when pbx-parkingfailed is not found.
> 
> Supplying parameters 's' is a workaround but it conflicts with the way an attended transfer to Parking works, so I think it's better to allow the user to playback parking errors rather than the application itself.

Thanks for the feedback... I think you're pointing out a separate issue with this, maybe, since the application already attempts to play "pbx-parkingfailed" in that case. Maybe the issue is that silence_announcements shouldn't be modifying behavior in the other way you mention?

**Comment by lukeescude** [comment]
Ah, you're thinking my original reported failure was actually due to the missing file, and not the Parking application itself...

OK I'll remove your patch and re-test with 's' - Sorry for the wild goose chase, we've been constructing large amounts of dialplan over the last couple months and haven't run into a dialplan application that required a specific hard-coded recording before.

**Comment by lukeescude** [comment]
OK so there is still an issue, even with 's' supplied:

[Mar  4 16:08:46] NOTICE[285][C-00000003]: parking/parking_bridge.c:148 generate_parked_user: Failed to get parking space in lot 'park-9b6e40cd-2549-4b9a-99bb-9f4fed979bc4'. All full.


So, your patch makes sense to fix the original problem.

**Comment by InterLinked1** [comment]
> Ah, you're thinking my original reported failure was actually due to the missing file, and not the Parking application itself...
> 
> OK I'll remove your patch and re-test with 's' - Sorry for the wild goose chase, we've been constructing large amounts of dialplan over the last couple months and haven't run into a dialplan application that required a specific hard-coded recording before.

Nope, I don't think it's due to the missing file. I'm just saying your recent comment about not playing that audio file seems like a separate issue to me, unrelated to what we're trying to fix in this one.

The result of ast_stream_and_wait is not failed, so I'm not seeing either why the Park application would fail if the file were missing.

**Comment by lukeescude** [comment]
I commented out ast_stream_and_wait and now we can announce the park # and continue dialplan execution gracefully.

The errors that it gave when pbx-invalidpark.wav was missing were:

```
[Mar  4 15:30:14] NOTICE[381][C-00000002]: parking/parking_bridge.c:148 generate_parked_user: Failed to get parking space in lot 'park-9b6e40cd-2549-4b9a-99bb-9f4fed979bc4'. All full.
[Mar  4 15:30:14] WARNING[381][C-00000002]: file.c:825 ast_openstream_full: File pbx-parkingfailed does not exist in any format
[Mar  4 15:30:14] WARNING[381][C-00000002]: file.c:1322 ast_streamfile: Unable to open pbx-parkingfailed (format (ulaw)): No such file or directory
```

And I think Asterisk tends to prefer a hard failure (drop the call, basically) when it can't find a file in Playback.

So, yeah, that's likely a separate issue.

**Comment by lukeescude** [comment]
It is not the case, the call simply drops without your patch.

**Comment by InterLinked1** [comment]
> It is not the case, the call simply drops without your patch.

Sorry, I mean with the patch, but even if the audio file does not exist... it shouldn't drop in that case.

**Comment by lukeescude** [comment]
Oh, yeah I can test it again, maybe I changed too many variables at once.

**Comment by lukeescude** [comment]
Well, you're right. Wonder what I mixed with my test earlier. The recording just pushes out an error but dialplan execution does still continue.

So, the patch is good to go, whether or not you feel like including the playback code!
