### ISSUE TITLE
[bug]: Unstable memory usage after multiple diaplan reload, no memory leak

### ISSUE THREAD

**Issue by sduthil** [asterisk/asterisk#627]
### Severity

Minor

### Versions

20.5.2

### Components/Modules

pbx_config

### Operating Environment

OS: Debian 11 Bullseye
CPU: 2 vCPU
RAM: 4GB

### Frequency of Occurrence

Constant

### Issue Description

Given I have a dialplan file `extensions.conf` with 6000 contexts
Given each context has 40 simple extensions with application `Hangup` (total: 240k dialplan lines)
Given all Asterisk modules are disabled, except for pbx_config.so
When I run `dialplan reload`
Then the memory usage increases (Resident Set Size memory metric on Linux)

Expected: the memory usage remains constant or near-constant

* mmlog and valgrind did not detect any memory leak
* Attached is an example of the memory usage during 128 sequential `dialplan reload`, memory values are in kB, so 1e6 is 1GB of RAM (RSS): 
![memory-usage](https://github.com/asterisk/asterisk/assets/5632013/7df71dc0-460b-466d-ad41-d5460a5416b1)
* Attached is the dialplan file with 6000 contexts: 
[extensions-hangup-only.conf.gz](https://github.com/asterisk/asterisk/files/14433947/extensions-hangup-only.conf.gz)

We are willing to help fix this issue, and we would welcome any explanation of the observed behavior, i.e. why the memory usage varies so much and why it stops growing after a few reloads, potential places where this memory could be allocated / used and useful tools or commands in order to guide our investigation.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
The two places would be main/pbx.c and pbx/pbx_config.c - they are what handle this. In the case of the reload operation itself it creates an entirely new instance of the dialplan and then swaps it into the core so during that you'd have two complete instances in memory. If there's no memory leak and no real issue, this type of discussion is probably better for the asterisk-dev mailing list which has a wider audience than the few people who generally monitor issues. They may have more ideas.

**Comment by jcolp** [comment]
I'm closing this out and any discussion should occur on the thread at https://groups.io/g/asterisk-dev/message/47 so that things aren't split. If the result of that discussion is an issue, then this can be reopened.
