### ISSUE TITLE
[improvement]: ARI debug should contain endpoint and method

### ISSUE THREAD

**Issue by nnew2** [asterisk/asterisk#666]
### Improvement Description

It would be really helpful if the Asterisk ARI debug would contain the actual endpoint and method. 

For an example
`GET /ari/channels/1711100856.29624`

Here's an ARI debug output and how it is logged today.

```
[Mar 22 08:12:58] VERBOSE[6273] res_ari.c: <--- ARI request received from: 127.0.0.1:48258 --->
user-agent: MyHTTPAgent
Content-Type: application/json
Accept: application/json
Authorization: Basic XXXXXXXXX
Host: localhost:8088
Connection: close
body:

[Mar 22 08:12:58] VERBOSE[6273] res_ari.c: <--- Sending ARI response to 127.0.0.1:48258 --->
204 No Content
```

**Comment by jcolp** [comment]
Is this something you are planning to work on?

**Comment by nnew2** [comment]
I was not planning on doing it, but you know what, I think I will give it a go. It would be my first contribution ever.
