### ISSUE TITLE
[improvement]: Remove deprecation warning for 'core show channels concise' in main/cli.c

### ISSUE THREAD

**Issue by ronlockard** [asterisk/asterisk#675]
### Improvement Description

I have seen several core developers state that 'core show channels concise' is NOT deprecated, but the code says that it is.  Can the deprecation warning from main/cli.c lines 1122-1123 please be removed, if 'concise' is not deprecated.

**Comment by seanbright** [comment]
> I have seen several core developers state that 'core show channels concise' is NOT deprecated,

Link?

**Comment by ronlockard** [comment]
Sorry my bad.  The last one I saw was Lorne Gaetz, but he's the FreePPX lead not an Asterisk dev.https://community.freepbx.org/t/asterisk-cli-column-width-for-channels/72546/4I swear I saw Joshua Culp say it's not deprecated somewhere too, but I can't find that one at the moment.  I'll send the link if I find it.If it is truly deprecated, can you please provide the Asterisk version it will be removed in?  I believe it's been marked deprecated since 1.6, but has yet to be removed in 10+ major versions so I've started to question whether someone just forgot to remove that warning when the intention to remove it changed.Thanks,RonSent from my Samsung Galaxy smartphone
-------- Original message --------From: Sean Bright ***@***.***> Date: 3/29/24  10:17 AM  (GMT-08:00) To: asterisk/asterisk ***@***.***> Cc: Ron Lockard ***@***.***>, Author ***@***.***> Subject: Re: [asterisk/asterisk] [improvement]: Remove deprecation warning for 'core show channels concise' in main/cli.c (Issue #675) 

I have seen several core developers state that 'core show channels concise' is NOT deprecated,

Link?

**Comment by jcolp** [comment]
I don't think I've ever said such thing, mostly because I forgot concise even existed.

**Comment by jcolp** [comment]
From what I can tell it was marked deprecated back in 2007, I think in an effort to drive scripts and other things to use AMI instead. That seemingly did not pan out as scripts and people continue to use concise. I don't think it's been a problem for us and I don't have any concern with it continuing to exist. We haven't been adding any additional concise functionality, though, but noone has brought up that.
