### ISSUE TITLE
[bug]: res_stir_shaken implicit declaration of function errors/warnings

### ISSUE THREAD

**Issue by lukeescude** [asterisk/asterisk#676]
### Severity

Minor

### Versions

20.7.0

### Components/Modules

res_stir_shaken

### Operating Environment

CentOS 7.9 x64
openssl.x86_64 1:1.0.2k-26.el7_9

### Frequency of Occurrence

Constant

### Issue Description

We are unable to get Asterisk 20.7 compiled with stir_shaken support, and this may be why. During the build process on CentOS, the following errors/warnings occur:

res_stir_shaken/crypto_utils.c: In function 'crypto_get_raw_pubkey_from_cert':
res_stir_shaken/crypto_utils.c:285:2: warning: implicit declaration of function 'X509_get0_pubkey' [-Wimplicit-function-declaration]
  public_key = X509_get0_pubkey(cert);
  ^
res_stir_shaken/crypto_utils.c:285:13: warning: assignment makes pointer from integer without a cast [enabled by default]
  public_key = X509_get0_pubkey(cert);
             ^
res_stir_shaken/crypto_utils.c: In function 'crypto_lock_cert_store':
res_stir_shaken/crypto_utils.c:322:2: warning: implicit declaration of function 'X509_STORE_lock' [-Wimplicit-function-declaration]
  return X509_STORE_lock(store) == 1 ? 0 : -1;
  ^
res_stir_shaken/crypto_utils.c: In function 'crypto_unlock_cert_store':
res_stir_shaken/crypto_utils.c:331:2: warning: implicit declaration of function 'X509_STORE_unlock' [-Wimplicit-function-declaration]
  return X509_STORE_unlock(store) == 1 ? 0 : -1;
  ^
res_stir_shaken/crypto_utils.c: In function 'crypto_show_cli_store':
res_stir_shaken/crypto_utils.c:380:2: warning: implicit declaration of function 'X509_STORE_get0_objects' [-Wimplicit-function-declaration]
  certs = X509_STORE_get0_objects(store);
  ^
res_stir_shaken/crypto_utils.c:380:8: warning: assignment makes pointer from integer without a cast [enabled by default]
  certs = X509_STORE_get0_objects(store);
        ^
res_stir_shaken/crypto_utils.c:384:3: warning: implicit declaration of function 'X509_OBJECT_get0_X509' [-Wimplicit-function-declaration]
   X509 *c = X509_OBJECT_get0_X509(o);
   ^
res_stir_shaken/crypto_utils.c:384:13: warning: initialization makes pointer from integer without a cast [enabled by default]
   X509 *c = X509_OBJECT_get0_X509(o);
             ^
   [CC] res_stir_shaken/tn_config.c -> res_stir_shaken/tn_config.o
   [CC] res_stir_shaken/common_config.c -> res_stir_shaken/common_config.o
   [CC] res_stir_shaken/profile_config.c -> res_stir_shaken/profile_config.o
   [CC] res_stir_shaken/verification_config.c -> res_stir_shaken/verification_config.o
res_stir_shaken/verification_config.c: In function 'vs_copy_cfg_common':
res_stir_shaken/verification_config.c:132:3: warning: implicit declaration of function 'X509_STORE_up_ref' [-Wimplicit-function-declaration]
   X509_STORE_up_ref(cfg_src->tcs);

### Asterisk Issue Guidelines

- [x] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
@gtjoseph Do we have a possible missing dependency check?

**Comment by gtjoseph** [comment]
I'm checking.

**Comment by seanbright** [comment]
At least some of the problematic functions are not in 1.0.2 as far as I can tell (the `0` variants that don't increment the key ref counts specifically).

**Comment by gtjoseph** [comment]
I could swear I tested this with CentOS7 but yeah, it's broken.  I'm working on it.

**Comment by gtjoseph** [comment]
@lukeescude Give PR #680 a try.  It's not easy for us to test it because the testsuite won't run under CentOS7 any more.  Let me know how it goes.

**Comment by lukeescude** [comment]
Tested and works well!
