### ISSUE TITLE
[new-feature]: new module: format_aac

### ISSUE THREAD

**Issue by viktike** [asterisk/asterisk#692]
### Feature Description

Advanced Audio Coding (MP4) format module. Uses libfaac and libfaad external libraries. The configure script needs upgrading to check the new dependencies, but running bootstrap.sh resulted more than the wanted changes, so I didn't add it to my commit.

**Comment by seanbright** [comment]
> running bootstrap.sh resulted more than the wanted changes, so I didn't add it to my commit.

What version of autoconf are you using? If you use 2.71 that should minimize the number of changes.

**Comment by viktike** [comment]
> > running bootstrap.sh resulted more than the wanted changes, so I didn't add it to my commit.
> 
> What version of autoconf are you using? If you use 2.71 that should minimize the number of changes.

I have 2.69 from Ubuntu 22.04 LTS (jammy).

It's not looking good:

```
git diff configure | egrep "^(\+|\-)" | wc -l
18435
```

Let me know if I should add it to my commit anyway.

**Comment by viktike** [comment]
Managed to update to 2.71, it's better, but...

```
git diff configure | egrep "^(\+|\-)" | wc -l
621
```

**Comment by seanbright** [comment]
It’s fine to be added to the PR and will need to end up there before merge regardless.

**Comment by viktike** [comment]
> It’s fine to be added to the PR and will need to end up there before merge regardless.

Added, thanks.

**Comment by viktike** [comment]
According to this document: https://web.archive.org/web/20170213191747/https://graphics.ethz.ch/teaching/mmcom12/slides/mp3_and_aac_brandenburg.pdf 
It's beneficial to enable Tns (Temporal Noise Reduction) for speech workloads in the encoder, so I just did that.

**Comment by seanbright** [comment]
I've done zero research before asking this question - are there publicly available UACs that support AAC?

**Comment by viktike** [comment]
> I've done zero research before asking this question - are there publicly available UACs that support AAC?

No, I don't think so. But please note, this is a format module (not a codec module), used to read/write files in the filesystem, and has nothing to do with VoIP, just digital audio. This module can be used to Record() or do MixMonitor() with great audio compression and retaining most of the sound quality, which was my primary goal. It can also be used to Playback() or Background() voice prompts in IVRs.

I hope it adds context to your question.

**Comment by seanbright** [comment]
> > I've done zero research before asking this question - are there publicly available UACs that support AAC?
> 
> No, I don't think so. But please note, this is a format module (not a codec module), used to read/write files in the filesystem, and has nothing to do with VoIP, just digital audio.

Ah yes. Bone-headed of me. Thank you for the clarification.

**Comment by viktike** [comment]
Due to license issues, this module cannot be merged into Asterisk. It's available here: https://github.com/viktike/asterisk-aac
