### ISSUE TITLE
[bug]: chan_pjsip uses wrong IP in SIP messages if at least two ip addresses are configured

### ISSUE THREAD

**Issue by thaeger71** [asterisk/asterisk#718]
### Severity

Major

### Versions

18.20.2

### Components/Modules

chan_pjsip.so

### Operating Environment

freePBX/RHEL

### Frequency of Occurrence

Constant

### Issue Description

If freePBX/asterisk has two source IP addresses, for example 192.168.1.100 and 192.168.2.100 (even in this order), asterisk uses 192.168.2.100 as source address in SIP message text, for example server part in CONTACT header, even it was sent from 192.168.1.100 in reality.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
I assume you are referring to SIP messages using PJSIP. What is the transport configuration?

Additionally, res_hep is community supported.

**Comment by thaeger71** [comment]
Hi,
I have news about this issue. The problem seems not be res_hep or res_hep_pjsip, the problem seems to be in asterisk or chan_pjsip. I traced a SIP registration from an account which is definitively bound to ip 192.168.1.100. In the trace, the package was even send from 192.168.1.100. But, in the REGISTER message, the contact field contains the second ip 192.168.2.100.

![image](https://github.com/asterisk/asterisk/assets/17908240/14e34115-aa09-49ee-ba28-e1099c7be555)

Should we close this case and open a new one ?

**Comment by jcolp** [comment]
If the underlying cause appears to be that, then you can edit this issue if you wish.

**Comment by gtjoseph** [comment]
@thaeger71 Are you specifying "transport" on the endpoints sending the requests?  Can you include the full endpoint configuration?
Also, you should include the netmask in the transport "local_net" parameters otherwise it defaults to `255.255.255.255`.

**Comment by asteriskteam** [comment]
This issue has been marked stale because it has been open 7 days with no feedback. Please provide feedback within 7 days or this issue will be closed.

**Comment by thaeger71** [comment]
Hello,
meanwhile I discovered that the problem was caused by the fact that the second IP (192.168.2.1) was on a virtual interface (eth0:1). In this case chan_pjsip or res_hep_pjsip.so takes the wrong address. Now I have a real dedicated NIC and it works.
Feel free to investigate this further, or closes this. I think it must be a very little bug, but I have a working solution now.

**Comment by asteriskteam** [comment]
This issue has been marked stale because it has been open 7 days with no feedback. Please provide feedback within 7 days or this issue will be closed.
