### ISSUE TITLE
[new-feature]: Add multi-tenant identifier to chan_pjsip

### ISSUE THREAD

**Issue by bkford** [asterisk/asterisk#740]
### Feature Description

Add multi-tenant identifier to chan_pjsip for general purpose use.

**Comment by alex2grad** [comment]
Why don't use '@' variable for PJSIP endpoint?
https://www.asterisk.org/did-you-know-you-can-use-variables-in-pjsip-conf/

For example

[myendpoint]
type=endpoint
@tenantid=MY_COMPANY

**Comment by jcolp** [comment]
That doesn't put such information in events or other things.

**Comment by alex2grad** [comment]
> That doesn't put such information in events or other things.

The Feature Description is too short to understand why it is needed and how to use it.
Nothing about "events or other things."

I do multi-tenant in my setup using PJSIP endpoint '@'variable and CALLERID(tag)/CONNECTEDLINE(tag)

BTW, I read the PR description and am confused.
