### ISSUE TITLE
[bug]: Asterisk not building C++ source due to "template" in ast_file_mkftemp

### ISSUE THREAD

**Issue by Jamesfryer1998** [asterisk/asterisk#744]
### Severity

Minor

### Versions

Asterisk 18.10.0

### Components/Modules

File.h

### Operating Environment

Ubuntu 22.04.4 LTS
gcc version 11.4.0

### Frequency of Occurrence

None

### Issue Description

I am trying to build Asterisk 18.10.0 however I am met with:

/usr/include/asterisk/file.h:148:30: error: expected ',' or '...' before 'template'
  148 | FILE *ast_file_mkftemp(char *template, mode_t mode);

I cannot find any other posts related to this issue, so wondering if anyone has any pointers?

### Relevant log output

```shell
[ 73%] Building CXX object phones_status/tests/CMakeFiles/NewAsterisk_Main_run.dir/app_phonestatus_tests.cxx.o
In file included from /source/AsteriskApps/phones_status/tests/../app_phonestatus.c:21,
                 from /source/AsteriskApps/phones_status/tests/app_phonestatus_tests.cxx:5:
/usr/include/asterisk/file.h:148:30: error: expected ',' or '...' before 'template'
  148 | FILE *ast_file_mkftemp(char *template, mode_t mode);
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
You are building a C++ file not part of Asterisk. The source code has not been fully tested against C++ in quite a few years, and the use of "template" in that API call is likely causing it to fail due to that being a keyword in C++. It would need to be changed most likely.

**Comment by Jamesfryer1998** [comment]
Thank for the speedy response @jcolp

Okay I will change this to something else.

**Comment by Jamesfryer1998** [comment]
Changing "*template" to "*_template" worked.

Thanks @jcolp
