### ISSUE TITLE
[bug]: PJSIP_PARSE_URI throws error when name has comma in it

### ISSUE THREAD

**Issue by blazestudios97** [asterisk/asterisk#756]
### Severity

Trivial

### Versions

18, 20, 21

### Components/Modules

chan_pjsip

### Operating Environment

Ubuntu 20

### Frequency of Occurrence

Constant

### Issue Description

When calling PJSIP_PARSE_URI, if the URI name field has a comma present the parsing fails.

### Relevant log output

```shell
SIP Headers:
From:  "THOMPSON,ALICIA" <sip:1NXXNXXXXXX@67.x.x.x>;tag=gK0c029832
Contact:  "THOMPSON,ALICIA" <sip:+1NXXNXXXXXX@67.x.x.x:5060>

Dialplan:
exten = s,n,ExecIf($["${CHANNEL(channeltype)}"="PJSIP"]?Set(__fromUser=${PJSIP_PARSE_URI(${CHANNEL(pjsip,remote_uri)},user)}))

Log output:
[2024-05-28 03:44:09.246] WARNING[28464] pjsip/dialplan_functions.c: Failed to parse URI '"THOMPSON'
[2024-05-28 03:44:09.246] VERBOSE[5907][C-00028968] pbx.c: Executing [s@user-callerid:2] ExecIf("PJSIP/switch-pstn-00067ded", "1?Set(__fromUser=)") in new stack
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by seanbright** [comment]
The argument parsing in `PJSIP_PARSE_URI` is the issue.

**Comment by jcolp** [comment]
I wonder if an immediate workaround would be to use STRREPLACE to replace "," with "\,"

**Comment by jcolp** [comment]
I played with some dialplan and confirmed that escaping the "," by placing a` "\"` in front works.
