### ISSUE TITLE
[bug]: PJSIP call fails when using call files.

### ISSUE THREAD

**Issue by silvaalex2021** [asterisk/asterisk#757]
### Severity

Minor

### Versions

18.17.1

### Components/Modules

pjsip (?)

### Operating Environment

ubuntu 20.04 LTS.

### Frequency of Occurrence

Constant

### Issue Description

We connect this server with other asterisk boxes we own. For this reason, none of the "trunks" use username and password authentication, just ip based. Everything works great, except when using Asterisk call files. Whenever we try, asterisk complains that there is no authentication ID available.

When trying to make calls directly to the external server, everything works fine as expected. the same occurs with incoming calls. I've even tried the "channel originate" command from the CLI, and it worked like a charm!

For reference, I'm attaching the call file I used to test, as well as the debug that shows the error.

[debug.txt](https://github.com/asterisk/asterisk/files/15503149/debug.txt)
[callfile.txt](https://github.com/asterisk/asterisk/files/15503150/callfile.txt)

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
We appreciate the difficulties you are facing, however this does not appear to be a bug report and your request or comments would be better served in a different forum.

The Asterisk community provides support over IRC, mailing lists, and forums[1] as described at http://asterisk.org/community. The Asterisk issue tracker is used specifically to track issues concerning bugs and documentation errors.

[1] https://community.asterisk.org/
