### ISSUE TITLE
[bug]: When the ast_bridge_channel already been destroyed, calling ast_bridge_channel_queue_frame results in a crash. 

### ISSUE THREAD

**Issue by Tinet-mucw** [asterisk/asterisk#768]
### Severity

Trivial

### Versions

18.10

### Components/Modules

bridge

### Operating Environment

Linux cti-clink-dev-saas 3.10.0-862.14.1.5.h654.eulerosv2r7.x86_64 #1 SMP Fri Dec 17 18:05:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Frequency of Occurrence

Occasional

### Issue Description

First, initiate a call using originate.

<--- Examining AMI action: -->
action: Originate
actionid: 424543336_294#AJ_ORIGINATE_85
channel: PJSIP/webrtc_1/sip:60000012005@172.16.0.xx:3xx66
priority: 1
exten: 60000012005
timeout: 30000
async: true
context: preview_outcall
callerid: xxxxx

Then, perform a dial operation in the dialplan to call the customer.

After that, initiate the action atxfer.

action: Atxfer
actionid: 985624711_297#
context: interact
channel: PJSIP/vos_c_1-00000005
exten: 2,1.2.1#

After performing the action atxfer, the customer hangs up within one second.

[core-asterisk-2024-06-03T00-42-06Z-brief.txt](https://github.com/user-attachments/files/15817885/core-asterisk-2024-06-03T00-42-06Z-brief.txt)
[core-asterisk-2024-06-03T00-42-06Z-full.txt](https://github.com/user-attachments/files/15817887/core-asterisk-2024-06-03T00-42-06Z-full.txt)
[core-asterisk-2024-06-03T00-42-06Z-info.txt](https://github.com/user-attachments/files/15817888/core-asterisk-2024-06-03T00-42-06Z-info.txt)
[core-asterisk-2024-06-03T00-42-06Z-locks.txt](https://github.com/user-attachments/files/15817890/core-asterisk-2024-06-03T00-42-06Z-locks.txt)
[core-asterisk-2024-06-03T00-42-06Z-thread1.txt](https://github.com/user-attachments/files/15817891/core-asterisk-2024-06-03T00-42-06Z-thread1.txt)

The above issue can be easily reproduced with the following changes.

```shell

--- a/asterisk/asterisk-18.10.1/main/bridge_channel.c
+++ b/asterisk/asterisk-18.10.1/main/bridge_channel.c
@@ -1094,9 +1094,11 @@ int ast_bridge_queue_everyone_else(struct ast_bridge *bridge, struct ast_bridge_
                if (cur == bridge_channel) {
                        continue;
                }
+
+               if (frmae->frametype == AST_FRAME_CONTROL && frame->subclass.frame_ending == AST_CONTROL_UNHOLD) {
+                       sleep(1);
 +              }

                if (!ast_bridge_channel_queue_frame(cur, frame)) {
                        not_written = 0;
                }
```

Later, I will provide my analysis and submit a PR.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by Tinet-mucw** [comment]
ast_bridge_join -> bridge_channel_internal_alloc -> bridge_channel reference +1
ast_bridge_join -> bridge_channel_internal_join -> bridge_channel_internal_pull -> AST_LIST_REMOVE(&bridge->channels, bridge_channel, entry); -> removed from bridge->channels
       AST_LIST_REMOVE(&bridge->channels, bridge_channel, entry); -> bridge is already locked (at the beginning of bridge_channel_internal_join function)
ast_bridge_join -> ao2_ref(bridge_channel, -1); -> bridge_channel reference -1, destroyed

**Comment by jcolp** [comment]
Does this occur under current Asterisk 18?

**Comment by jcolp** [comment]
Additionally, the line numbers don't match between the backtrace you've provided and Asterisk 18.10.1.

**Comment by Tinet-mucw** [comment]
My proposed modification is as follows. I did not see similar changes; ast_bridge is not locked, which can lead to race conditions.


--- a/asterisk/asterisk-18.10.1/main/bridge_channel.c
+++ b/asterisk/asterisk-18.10.1/main/bridge_channel.c
@@ -1090,17 +1090,17 @@ int ast_bridge_queue_everyone_else(struct ast_bridge *bridge, struct ast_bridge_
                return 0;
        }
 
+       ast_bridge_lock(bridge);
        AST_LIST_TRAVERSE(&bridge->channels, cur, entry) {
                if (cur == bridge_channel) {
                        continue;
                }
-               if (frame->frametype == AST_FRAME_CONTROL && frame->subclass.integer == AST_CONTROL_UNHOLD) {
-                       sleep(1);
-               }
+
                if (!ast_bridge_channel_queue_frame(cur, frame)) {
                        not_written = 0;
                }
        }
+       ast_bridge_unlock(bridge);
        return not_written;
 }

**Comment by jcolp** [comment]
You'll need to put an actual PR up and sign the CLA for actual proposal.

**Comment by jcolp** [comment]
I still ask though, why do the line numbers not match 18.10.1? Are there other modifications to bridge_basic.c?

**Comment by Tinet-mucw** [comment]
Later, I will attempt to reproduce using the current Asterisk 18.
And i will need to put an actual PR up and sign the CLA for actual proposal.

**Comment by Tinet-mucw** [comment]
Using version 18.17, the issue was not reproduced. because, based on the manager event, the positions of the new channel and hangup events for the local channel differ from those in version 18.10.
