### ISSUE TITLE
[bug]: Phantom PJSIP UUID endpoint

### ISSUE THREAD

**Issue by harryyoud** [asterisk/asterisk#778]
### Severity

Trivial

### Versions

Asterisk 21.0.2 built by jenkins @ c1b0d5abe4bd on a x86_64 running Linux

### Components/Modules

PJSIP

### Operating Environment

Debian Linux 12, running FreePBX 17

### Frequency of Occurrence

Constant

### Issue Description

PJSIP endpoint exposed by `/ari/endpoints`, which is not visible by CLI. Cosmetic issue only as far as I am aware. First noticed as FreePBX status page shows channels and lists this one (backend of this uses ARI). UUID has no matches in log file (full), or in /etc/asterisk directory.

```
# curl http://localhost:8088/ari/endpoints | jq
[
  {
    "technology": "PJSIP",
    "resource": "7cdaa062-2eac-4689-aa1a-82bc38c49507",
    "state": "offline",
    "channel_ids": []
  },
........., remaining extensions listed
```

The UUID changes on every restart of asterisk and always shows as offline.

Endpoint not visible in CLI with 'pjsip show endpoints'

Discussion about issue I found on Google available here: https://community.freepbx.org/t/unknown-pjsip-channel/66380.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Do you have DPMA loaded? It creates a UUID endpoint for its usage.
