### ISSUE TITLE
500 Internal Server Error on download page

### ISSUE THREAD

**Issue by chatUnicorn** [asterisk/asterisk#804]
### Severity

Critical

### Versions

16.6.0

### Components/Modules

Asterisk

### Operating Environment

Ubuntu 14.04.6

### Frequency of Occurrence

Every time

### Issue Description

We are dependent on version 16.6.0 and when our CI process tries to download it it fails. http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-16.6.0.tar.gz

500 Internal Server Error

nginx/1.20.1

Please fix the issue!

### Relevant log output

```shell
500 Internal Server Error

nginx/1.20.1
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
That's an old release, meaning it is in the old-releases directory:

https://downloads.asterisk.org/pub/telephony/asterisk/old-releases/asterisk-16.6.0.tar.gz
