### ISSUE TITLE
[bug]: Endpoints periodically deemed Unreachable after responding to OPTIONS request

### ISSUE THREAD

**Issue by zylinc-ms** [asterisk/asterisk#805]

**Comment by zylinc-ms** [comment]
Will add new bug info without sensitive material

**Comment by asteriskteam** [comment]
This issue has been marked stale because it has been open 7 days with no feedback. Please provide feedback within 7 days or this issue will be closed.

**Comment by asteriskteam** [comment]
This issue has been closed because it has been open 14 days with no feedback.
