### ISSUE TITLE
[bug]: CLI stir_shaken show verification kills asterisk

### ISSUE THREAD

**Issue by oza4h07** [asterisk/asterisk#809]
### Severity

Major

### Versions

20.8.1

### Components/Modules

PJSIP

### Operating Environment

Debian Bullseye

### Frequency of Occurrence

Constant

### Issue Description

CLI "stir_shaken show verification" kills asterisk.
stir_shaken.conf file is set with specific data (that privately) be shared if necessary.

[backtrace_files.tar.gz](https://github.com/user-attachments/files/16270581/backtrace_files.tar.gz)

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by gtjoseph** [comment]
I see what's happening.  Thanks for the report.

**Comment by oza4h07** [comment]
PR #815 seems to solve this issue
