### ISSUE TITLE
[bug] Exceptionally long voice queue length queuing to Local/exten@context-channel

### ISSUE THREAD

**Issue by GiovanniLira** [asterisk/asterisk#813]
### Severity

Critical

### Versions

Asterisk 13.32.0

### Components/Modules

--enable BUILD_NATIVE \ --enable OPTIONAL_API \ --enable-category MENUSELECT_BRIDGES \ --enable app_bridgewait \ --enable app_chanisavail \ --enable app_chanspy \ --enable app_controlplayback \ --enable app_dial \ --enable app_macro \ --enable app_mixmonitor \ --enable app_originate \ --enable app_playback \ --enable app_read \ --enable app_senddtmf \ --enable app_softhangup \ --enable app_stack \ --enable app_stasis \ --enable app_system \ --enable app_talkdetect \ --enable app_transfer \ --enable app_userevent \ --enable app_verbose \ --enable app_waitforsilence \ --enable chan_bridge_media \ --enable chan_rtp \ --enable chan_sip \ --enable codec_alaw \ --enable codec_ulaw \ --enable format_g729 \ --enable format_pcm \ --enable format_sln \ --enable format_wav \ --enable func_callerid \ --enable func_channel \ --enable func_config \ --enable func_cut \ --enable func_devstate \ --enable func_dialplan \ --enable func_env \ --enable func_extstate \ --enable func_global \ --enable func_groupcount \ --enable func_hangupcause \ --enable func_jitterbuffer \ --enable func_logic \ --enable func_math \ --enable func_module \ --enable func_presencestate \ --enable func_rand \ --enable func_realtime \ --enable func_sprintf \ --enable func_strings \ --enable func_sysinfo \ --enable func_talkdetect \ --enable func_timeout \ --enable func_version \ --enable pbx_ael \ --enable pbx_config \ --enable pbx_realtime \ --enable res_ael_share \ --enable res_clialiases \ --enable res_clioriginate \ --enable res_crypto \ --enable res_format_attr_g729 \ --enable res_format_attr_h263 \ --enable res_format_attr_h264 \ --enable res_limit \ --enable res_manager_devicestate \ --enable res_manager_presencestate \ --enable res_realtime \ --enable res_rtp_asterisk \ --enable res_rtp_multicast \ --enable res_snmp \ --enable res_sorcery_astdb \ --enable res_sorcery_config \ --enable res_sorcery_memory \ --enable res_sorcery_realtime \ --enable res_stasis \ --enable res_stasis_answer \ --enable res_stasis_device_state \ --enable res_stasis_playback \ --enable res_stasis_recording \ --enable res_stasis_snoop \ --enable res_timing_timerfd \ --enable res_security_log \ --enable astcanary \ --enable app_queue \ --enable app_amd \ --enable app_cdr \ --enable cdr_custom \ --enable func_cdr \ --enable chan_dahdi \

### Operating Environment

CentOS 7 / Kernel 3.10.0-1160.76.1.el7.x86_64
Proc: Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz
                     total        used        free      shared  buff/cache   available
Mem:           251G       5.4G        203G        5.0G         43G        240G

### Frequency of Occurrence

Frequent

### Issue Description

Currently, I use Asterisk in production with an external dialer making many calls per second via SIP.

I am receiving tons of them when I watch "rasterisk":

WARNING[5168][C-00052fbc] channel.c: Exceptionally long voice queue length queuing to Local/097210219XXXXXXXX@agentes-0003c359;1

When this happens, the system no longer accepts calls, and to make it work again, I have to completely restart it.
It doesn't happen all the time, but it always occurs at random times.

### Relevant log output

```shell
WARNING[5168][C-00052fbc] channel.c: Exceptionally long voice queue length queuing to Local/097210219XXXXXXXX@agentes-0003c359;1
[2024-07-18 09:27:53.554] WARNING[5168][C-00052fbc] channel.c: Exceptionally long voice queue length queuing to Local/097210219XXXXXXXX@agentes-0003c359;1
[2024-07-18 09:27:54.834] WARNING[5168][C-00052fbc] channel.c: Exceptionally long voice queue length queuing to Local/097210219XXXXXXXX@agentes-0003c359;1
[2024-07-18 09:27:56.114] WARNING[5168][C-00052fbc] channel.c: Exceptionally long voice queue length queuing to Local/097210219XXXXXXXX@agentes-0003c359;1
[2024-07-18 09:27:57.395] WARNING[5168][C-00052fbc] channel.c: Exceptionally long voice queue length queuing to Local/097210219XXXXXXXX@agentes-0003c359;1
[2024-07-18 09:27:58.673] WARNING[5168][C-00052fbc] channel.c: Exceptionally long voice queue length queuing to Local/097210219XXXXXXXX@agentes-0003c359;1
[2024-07-18 09:27:59.954] WARNING[5168][C-00052fbc] channel.c: Exceptionally long voice queue length queuing to Local/097210219XXXXXXXX@agentes-0003c359;1
[2024-07-18 09:28:01.233] WARNING[5168][C-00052fbc] channel.c: Exceptionally long voice queue length queuing to Local/097210219XXXXXXXX@agentes-0003c359;1
[2024-07-18 09:28:02.514] WARNING[5168][C-00052fbc] channel.c: Exceptionally long voice queue length queuing to Local/097210219XXXXXXXX@agentes-0003c359;1
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Asterisk 13.32.0 is not supported. The lowest supported branch would be the Asterisk 18 series.
