### ISSUE TITLE
[bug]: app_dial:  The progress timeout doesn't cause Dial to exit

### ISSUE THREAD

**Issue by gtjoseph** [asterisk/asterisk#821]
### Severity

Trivial

### Versions

18,20,21,master

### Components/Modules

app_dial

### Operating Environment

all

### Frequency of Occurrence

None

### Issue Description

The loop in app_dial:wait_for_answer doesn't exit when to_progress times out so even if you specify a progress_timeout, Dial will continue until the answer timeout.
Discovered by failing testsuite test tests/apps/dial/dial_progress.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by InterLinked1** [comment]
@gtjoseph I see why the test is broken and will fix that, but did you find an actual issue with the functionality? I can't replicate your described issue:

```

[2024-10-01 20:31:27.766]     -- Executing [19@from-internal:1] InbandDial("DAHDI/16-1", "Local/s@test,^3") in new stack
[2024-10-01 20:31:27.766]     -- Executing [s@test:1] Wait("Local/s@test-0000010f;2", "6") in new stack
[2024-10-01 20:31:27.766]     -- Called Local/s@test
[2024-10-01 20:31:30.770]     -- No early media received in 3000 ms
[2024-10-01 20:31:30.771]   == Spawn extension (test, s, 1) exited non-zero on 'Local/s@test-0000010f;2'
[2024-10-01 20:31:30.772]        > Call ended, DIALSTATUS: CHANUNAVAIL

[2024-10-01 20:33:56.341]     -- Executing [19@from-internal:1] InbandDial("DAHDI/16-1", "Local/s@test,6^3") in new stack
[2024-10-01 20:33:56.347]     -- Executing [s@test:1] Wait("Local/s@test-00000110;2", "6") in new stack
[2024-10-01 20:33:56.347]     -- Called Local/s@test
[2024-10-01 20:33:59.354]     -- No early media received in 3000 ms
[2024-10-01 20:33:59.354]   == Spawn extension (test, s, 1) exited non-zero on 'Local/s@test-00000110;2'
[2024-10-01 20:33:59.356]        > Call ended, DIALSTATUS: CHANUNAVAIL
```

**Comment by gtjoseph** [comment]
It's been a while but what is `InbandDial()`?  One of your apps?  Does it do something different than `Dial()`?

**Comment by InterLinked1** [comment]
> @InterLinked1 It's been a while but what is `InbandDial()`? One of your apps? Does it do something different than `Dial()`?

It's just a wrapper I use around `Dial`, there's no behavior difference

**Comment by gtjoseph** [comment]
@InterLinked1 Well, I have a dead simple sipp scenario that waits for an INVITE, then waits 10 seconds before responding with a 100-Trying.  When I call that scenario with `10^3` as the timeout, it waits 10 seconds and ends the call with `Nobody picked up in 10000 ms`.  What am I missing?

**Comment by InterLinked1** [comment]
> @InterLinked1 Well, I have a dead simple sipp scenario that waits for an INVITE, then waits 10 seconds before responding with a 100-Trying. When I call that scenario with `10^3` as the timeout, it waits 10 seconds and ends the call with `Nobody picked up in 10000 ms`. What am I missing?

Hmm... that's strange. Could you post the dialplan/scenario? I'll see if I can replicate that. I didn't test with sipp but can't see how that would matter either.

**Comment by gtjoseph** [comment]
@InterLinked1 Here you go...

Dialplan:
```
exten = 9999,1,NoOp(Local ${EXTEN} ${HINT} ${CALLERID(num)})
same  = n,Dial(PJSIP/${EXTEN}@alice,10^3)
same  = n,Hangup()
```

[recv_call.xml.txt](https://github.com/user-attachments/files/17245311/recv_call.xml.txt)
`sipp -sf recv_call.xml -i 127.0.0.2 -p 5060 -bind_local -aa`

Set up "alice" as a simple endpoint with no auth or registration needed and a contact of `sip:127.0.0.2:5060` then dial 9999 from another device.

**Comment by InterLinked1** [comment]
> @InterLinked1 Here you go...
> 
> Dialplan:
> 
> ```
> exten = 9999,1,NoOp(Local ${EXTEN} ${HINT} ${CALLERID(num)})
> same  = n,Dial(PJSIP/${EXTEN}@alice,10^3)
> same  = n,Hangup()
> ```
> 
> [recv_call.xml.txt](https://github.com/user-attachments/files/17245311/recv_call.xml.txt) `sipp -sf recv_call.xml -i 127.0.0.2 -p 5060 -bind_local -aa`
> 
> Set up "alice" as a simple endpoint with no auth or registration needed and a contact of `sip:127.0.0.2:5060` then dial 9999 from another device.

Hmm, yeah, that's interesting, I was thinking there might be a 183 here but I only see 100, and I don't see the progress verbose message from `app_dial` either so it doesn't appear 100 is being treated as progress either. I'll test again with a SIP endpoint today.

**Comment by jcolp** [comment]
A 100 Trying isn't really a progress response. It's used to stop the INVITE retransmission, but just really indicates that the INVITE is being handled, not that any progress has been made yet.

**Comment by InterLinked1** [comment]
> @InterLinked1 Here you go...
> 
> Dialplan:
> 
> ```
> exten = 9999,1,NoOp(Local ${EXTEN} ${HINT} ${CALLERID(num)})
> same  = n,Dial(PJSIP/${EXTEN}@alice,10^3)
> same  = n,Hangup()
> ```
> 
> [recv_call.xml.txt](https://github.com/user-attachments/files/17245311/recv_call.xml.txt) `sipp -sf recv_call.xml -i 127.0.0.2 -p 5060 -bind_local -aa`
> 
> Set up "alice" as a simple endpoint with no auth or registration needed and a contact of `sip:127.0.0.2:5060` then dial 9999 from another device.

@gtjoseph Would you mind providing the full PJSIP configuration for this alice endpoint, just to make sure I've got it right? I seem to be missing something for this configuration but can't place it:

```
[alice]
type = endpoint
disallow = all
allow = ulaw
context = from-internal

[alice]
type = aor
contact = sip:127.0.0.2:5060

[Oct  3 15:23:46]     -- Executing [9999@from-internal:2] Dial("Local/9999@from-internal-00000005;2", "PJSIP/9999@alice,10^3") in new stack
[Oct  3 15:23:46] WARNING[100123]: res_pjsip/location.c:280 ast_sip_location_retrieve_contact_and_aor_from_list_filtered: Unable to determine contacts from empty aor list
[Oct  3 15:23:46] ERROR[100123]: res_pjsip_session.c:3369 ast_sip_session_create_outgoing: Endpoint 'alice': No URI available.  Is endpoint registered?
[Oct  3 15:23:46] ERROR[100123]: chan_pjsip.c:2702 request: Failed to create outgoing session to endpoint 'alice'
[Oct  3 15:23:46] NOTICE[100150][C-00000006]: app_dial.c:2703 dial_exec_full: Unable to create channel of type 'PJSIP' (cause 3 - No route to destination)
[Oct  3 15:23:46]   == Everyone is busy/congested at this time (1:0/0/1)
```

**Comment by gtjoseph** [comment]
@InterLinked1 you need to add `aors = alice` to the endpoint.

**Comment by InterLinked1** [comment]
> @InterLinked1 you need to add `aors = alice` to the endpoint.

Thanks... it's been a while since I've manually configured a PJSIP endpoint :)

I figured out what's going on here... I'll fix the issues with the test as well and submit a patch.

**Comment by gtjoseph** [comment]
@InterLinked1 dial_progress continues to fail.
```
apps/dial/dial_progress                                          [  65 of  168][Failed][  64][   1]
---------------------------------------------------------------------
Making sure Asterisk isn't running ...
Making sure SIPp isn't running...
Running tests/apps/dial/dial_progress ...
[Oct 12 03:24:53] WARNING[10484]: asterisk.test_case:547 _reactor_timeout: Reactor timeout: '30' seconds
[Oct 12 03:24:53] WARNING[10484]: asterisk.ami:207 __check_result: Event occurred 0 times, which is out of the allowable range
[Oct 12 03:24:53] WARNING[10484]: asterisk.ami:209 __check_result: Event description: {'conditions': {'match': {'Event': 'UserEvent', 'UserEvent': 'DialProgress'}}, 'requirements': {'match': {'Result': 'Pass'}}, 'count': 2}
Test tests/apps/dial/dial_progress failed
```

**Comment by InterLinked1** [comment]
@gtjoseph Okay, I've identified a few issues that I will submit.

However, I'm also running into a strange issue with the test suite (which I got running on a different system). For some reason, channel allocation will fail in the middle of the test due to active shutdown. I haven't found a clear reason why the test suite is shutting Asterisk down in the middle of the test. The usual things don't seem to apply - there is clearly still a channel in existence (i.e. all channels have *not* hung up), and the criteria for test passing isn't met yet either.

I'm a bit confused on that, but I'll put a WIP PR up with changes if you want to take a look from there. I could just delete the last part of the test to make it work, but that shouldn't be necessary.

**Comment by gtjoseph** [comment]
@InterLinked1 The yappcap issue is known (it's just too old to compile successfully) and we're working on a replacement.  You can comment out that line in extras.txt for now.

Does the asterisk code need to be updated or just the testsuite test?

**Comment by InterLinked1** [comment]
> @InterLinked1 The yappcap issue is known (it's just too old to compile successfully) and we're working on a replacement. You can comment out that line in extras.txt for now.

Gotcha, thanks.

> Does the asterisk code need to be updated or just the testsuite test?

Both, for different things. The Asterisk change is good to go (at least from my side), the test suite one I'd like some input on as to why the test is behaving that way. I'll get PRs up for both later today.

**Comment by Ug-Okun** [comment]
Hello,

I am experiencing the exact same issue described in this thread, specifically the "AOR '' not found for endpoint" warning and the subsequent 404 Not Found response for PJSIP REGISTER requests, even after successful authentication challenge (when authentication is authentication is enabled).

Here are my details:

**Asterisk Version:** Asterisk 20.12.0
**SIP Client:** Jigasi 1.1.391-g31ab705 (running on a separate host, [JIGASI_IP_ADDRESS])

**Relevant pjsip.conf configuration:**

```ini
; For endpoint 9101
[9101_endpoint]
type=endpoint
context=from-jigasi
aors=!9101_aor
auth=9101_auth                 ; Initially set, then temporarily removed for testing
disallow=all
allow=opus,ulaw,alaw,gsm,speex
dtmf_mode=rfc4733
direct_media=no
rewrite_contact=yes
rtp_symmetric=yes
force_rport=yes
force_avp=yes

[9101_auth] ; Renamed from [9101] for clarity, original was [9101]
type=auth
auth_type=userpass
username=9101
password=[Password]

[9101_aor] ; Renamed from [9101] for clarity, original was [9101]
type=aor
max_contacts=1
remove_existing=yes
(Note: My original pjsip.conf had the auth and aor sections both named [9101]. I've used _auth and _aor suffixes here for clarity in the issue report, but confirmed pjsip show auth and pjsip show aors picked them up correctly with the original names.)

Observed Behavior (SIP Debug Log):

First attempt (with auth=9101_auth):

<--- Received SIP request (XXX bytes) from UDP:[JIGASI_IP_ADDRESS]:YYYYY --->
REGISTER sip:[JIGASI_IP_ADDRESS] SIP/2.0
... (initial REGISTER from Jigasi)

<--- Transmitting SIP response (YYY bytes) to UDP:[JIGASI_IP_ADDRESS]:YYYYY --->
SIP/2.0 401 Unauthorized
... (Asterisk challenges)

<--- Received SIP request (ZZZ bytes) from UDP:[JIGASI_IP_ADDRESS]:YYYYY --->
REGISTER sip:[JIGASI_IP_ADDRESS] SIP/2.0
Authorization: Digest username="9101",realm="asterisk",nonce="...",uri="sip:[JIGASI_IP_ADDRESS]",response="...",algorithm=MD5,opaque="...",qop=auth,cnonce="...",nc=00000001
... (Jigasi sends REGISTER with Authorization)

<--- Transmitting SIP response (408 bytes) to UDP:[JIGASI_IP_ADDRESS]:YYYYY --->
SIP/2.0 404 Not Found
...

[] WARNING[XXXX]: res_pjsip_registrar.c:1174 find_registrar_aor: AOR '' not found for endpoint '9101_endpoint' ([JIGASI_IP_ADDRESS]:YYYYY)
Test after temporarily commenting out auth=9101_auth from [9101_endpoint] (for debugging):

<--- Received SIP request (487 bytes) from UDP:[JIGASI_IP_ADDRESS]:52626 --->
REGISTER sip:[JIGASI_IP_ADDRESS] SIP/2.0
... (initial REGISTER from Jigasi)

<--- Transmitting SIP response (408 bytes) to UDP:[JIGASI_IP_ADDRESS]:52626 --->
SIP/2.0 404 Not Found
...

 []WARNING[48895]: res_pjsip_registrar.c:1174 find_registrar_aor: AOR '' not found for endpoint '9101_endpoint' ([JIGASI_IP_ADDRESS]:52626)
Troubleshooting Steps Taken:

Verified pjsip.conf syntax and parameter names multiple times.
Confirmed pjsip show endpoints and pjsip show aors correctly load 9101_endpoint and 9101_aor (and 9101_auth).
Restarted Asterisk service (systemctl restart asterisk) and reloaded modules (pjsip reload) after every config change.
Restarted Jigasi service (systemctl restart jigasi).
Upgraded Asterisk from 18.10.0 to 20.12.0 (manually, due to PPA issues).
Temporarily removed the auth parameter from the 9101_endpoint section to rule out authentication as the cause (as shown in the second log snippet above). The 404 Not Found and AOR '' not found warning persisted without the 401 challenge, confirming authentication is not the root cause.
The behavior is consistent across Asterisk 18 and 20, and regardless of whether authentication is enabled or not. The username="9101" is clearly present in the Authorization header and the From header of the REGISTER request.

This issue is preventing Jigasi from registering. Any insights or suggestions would be greatly appreciated.

Thank you.

**Comment by jcolp** [comment]
@Ug-Okun This is a better ft for the community forum at https://community.asterisk.org/ instead of this old issue.

**Comment by Ug-Okun** [comment]
@jcolp Thank you for your guidance. I will create a new topic on the Asterisk Community Forum as suggested. I appreciate your advice.
