### ISSUE TITLE
[bug]: app_voicemail ODBC

### ISSUE THREAD

**Issue by sysnux** [asterisk/asterisk#831]
### Severity

Critical

### Versions

20.9.1

### Components/Modules

app_voicemail

### Operating Environment

Linux

### Frequency of Occurrence

Constant

### Issue Description

Crash in odbc_insert_data_cb and messagecount

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by gtjoseph** [comment]
Even though you've submitted a pull request for this, we still need the backtraces...
https://docs.asterisk.org/Development/Debugging/Getting-a-Backtrace/

**Comment by sysnux** [comment]
Well, I spent most of yesterday chasing these two bugs, and they are quite obvious, I won't spend more time on that, sorry.

**Comment by bkervaski** [comment]
Same issue, it appears starting with 20.9.0.

**Comment by gtjoseph** [comment]
It should be fixed before the next set of releases.

**Comment by seanbright** [comment]
Seems this can be closed now?

**Comment by sysnux** [comment]
Yes, thanks!

**Comment by sysnux** [comment]
Resolved
