### ISSUE TITLE
[bug]:  wrong properties in stir_shaken.conf.sample

### ISSUE THREAD

**Issue by bit-willi** [asterisk/asterisk#854]
### Bug Description

In the file https://raw.githubusercontent.com/asterisk/asterisk/master/configs/samples/stir_shaken.conf.sample
Both examples, for attestation and tn objects are poorly documented, the example shows **private_key_path**, when it should be **private_key_file**

This is the example:
`
;[18005551515]
;type = tn
;private_key_path = /var/lib/asterisk/keys/stir_shaken/tns/18005551515-key.pem
;public_cert_url = https://example.com/tncerts/18005551515-cert.pem
;attest_level = C

;[attestation]
;global_disable = no
;private_key_path = /var/lib/asterisk/keys/stir_shaken/tns/multi-tns-key.pem
;public_cert_url = https://example.com/tncerts/multi-tns-cert.pem
;attest_level = C
`

It should be 

`
;[18005551515]
;type = tn
;private_key_file = /var/lib/asterisk/keys/stir_shaken/tns/18005551515-key.pem
;public_cert_url = https://example.com/tncerts/18005551515-cert.pem
;attest_level = C

;[attestation]
;global_disable = no
;private_key_file = /var/lib/asterisk/keys/stir_shaken/tns/multi-tns-key.pem
;public_cert_url = https://example.com/tncerts/multi-tns-cert.pem
;attest_level = C
`

Source: https://raw.githubusercontent.com/asterisk/asterisk/master/res/res_stir_shaken/stir_shaken_doc.xml, lines 12 and 37

**Comment by gtjoseph** [comment]
Hmmm.  How'd I miss that???  
Thanks for finding it.

**Comment by gtjoseph** [comment]
PRs up for fixing in the sample config file and also in the documentation: asterisk/documentation#100.

**Comment by bit-willi** [comment]
@gtjoseph Does the review need to be done by someone specific or can I review and approve as it is a simple change?

**Comment by gtjoseph** [comment]
> @gtjoseph Does the review need to be done by someone specific or can I review and approve as it is a simple change?

Feel free :)
The only reason I didn't merge it today is that I'm off today.
