### ISSUE TITLE
[bug]: Voicemail - Mailbox resequencing ignores messages beyond maxmsg+10, breaking mailbox

### ISSUE THREAD

**Issue by sharlow** [asterisk/asterisk#86]
### Severity

Trivial

### Versions

18.15.1

### Components/Modules

app_voicemail

### Operating Environment

FreePBX Distro SNG7 16.0.39

### Frequency of Occurrence

Constant

### Issue Description

We have a custom dialplan application that records responses to a few prompts, then combines those recordings in to a single file and emails it while also sticking it in a mailbox to allow users without email access to check it remotely.  Since this goes around the normal voicemail system it doesn't abide by the configured limits and after a period of time where the users were handling it entirely through email the mailbox ended up with 392 messages out of an allowed 100.

Eventually someone started calling in to the mailbox again and attempted to work their way through the backlog.  They got through what we now know to have been 110 messages and then they reported that the system was just repeating the menu prompts.

I called in to check the mailbox myself while watching the Asterisk console and immediately after entering the password to the mailbox was greeted with the message ```app_voicemail.c:9007 open_mailbox: Resequencing Mailbox: /var/spool/asterisk/voicemail/default/8550/INBOX, expected 100 but found 282 message(s) in box with max threshold of 100.``` repeated twice as the system voiced "You have 282 new messages".  I pressed 1 for new messages, got the "First message" prompt, then an error on the console ```app_voicemail.c:8727 play_message: No message attribute file?!! (/var/spool/asterisk/voicemail/default/8550/INBOX/msg0000.txt)``` and the advanced options prompt exactly as the user had reported.

I looked in the mailbox folder and found that the files present were msg0110 through msg0392, so knowing it was so close to the limit I guessed that might be relevant.  I raised maxmsg to 1000, reloaded Asterisk, and tried again.  This time I got a different error reflecting the raised limits, ```app_voicemail.c:9007 open_mailbox: Resequencing Mailbox: /var/spool/asterisk/voicemail/default/8550/INBOX, expected 392 but found 282 message(s) in box with max threshold of 1000.``` and was able to play messages.  Looking in the folder after that point I saw msg0000 through msg0281 as expected and redialing the mailbox another time resulted in no further errors.

Looking in to the Asterisk code I found that this behavior seems to be intentional.  The error message about resequencing the mailbox comes from [line 9007 of app_voicemail.c](https://github.com/asterisk/asterisk/blob/7c917618f488c0738b67b57fad0be1ecc4a3c8b2/apps/app_voicemail.c#L9007) and right above that on line 8999 is the comment ```/* for local storage, checks directory for messages up to maxmsg limit */```, though the [actual for loop in resequence_mailbox()](https://github.com/asterisk/asterisk/blob/7c917618f488c0738b67b57fad0be1ecc4a3c8b2/apps/app_voicemail.c#L7053) looks as far as maxmsg + 10.  Clearly from the logs and audible prompts Asterisk knows there are really 282 messages in the mailbox, but it intentionally fails to handle that situation properly and as a result makes the mailbox unusable until an admin intervenes, so I think it should count as a bug even though it's "working as designed".  Why should it stop resequencing at maxmsg+10 if it knows there are more messages?

Of course our specific situation was caused by our unorthodox use of the mailbox allowing new messages to be inserted after it was "full" but as far as I can tell this same behavior could be triggered by simply reducing maxmsg when a mailbox already has 10 or more messages beyond the new limit.

---

Replication steps:

1. Have a mailbox with > maxmsg+10 messages in it.
2. Trigger resequencing.
3. Messages beyond maxmsg+10 will not have been resequenced, but will still be counted, attempts to play the resulting gap in the sequence will fail.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by phoneben** [comment]
This same behavior is when i have a number of the messages over the max limit 
lets say the limit is 100 and i have 99 messages numbered 101-199.
 Will have more or less the same results

**Comment by seanbright** [comment]
I'm trying to reproduce this but not having much luck. 

> Eventually someone started calling in to the mailbox again and attempted to work their way through the backlog.

Before this user started, were the messages numbered sequentially from `msg0000` to `msg0391` or were there gaps or...?

**Comment by sharlow** [comment]
> Before this user started, were the messages numbered sequentially from `msg0000` to `msg0391` or were there gaps or...?

When I first looked at it the oldest file was msg0110 and that through msg0391 were present, msg0000-0109 were not there.

We could see that the user had called in and spent some time on the line with the voicemail system earlier that morning, then hung up, then had called back in later for a short period of time before they reported the problem to us.  My assumption based on that is that a full 392 messages were present that morning, the user had called in and deleted the first 110, then gone to do something else before coming back to it later at which point the bug was triggered.

The code I linked in the initial report seems to still be the same, and if I'm reading it correctly if resequence_mailbox() is triggered while the lowest msgXXXX number is greater than maxmsg + 10 this will happen, so that should be a reliable path to replication.

Either manually inject a bunch of messages directly in to the mailbox directory from external software like we did, or presumably you could also trigger this by filling up a mailbox the normal way then lowering maxmsg by a significant amount.

Let's say maxmsg is 100, you fill up the mailbox, then lower maxmsg to 10.  Delete 20 or more messages from that mailbox and you should hit it.

**Comment by seanbright** [comment]
> When I first looked at it the oldest file was msg0110 and that through msg0391 were present, msg0000-0109 were not there.

This is what I’m not able to reproduce. If I seed the voicemail directory with msg0000 thru msg0391 I’m not able to delete any messages through the voicemail system so it’s not clear to me how to get the messages in the state you describe.

To be clear there is obviously a problem but I was hoping to reproduce the “oldest file was msg0110” part organically.

**Comment by sharlow** [comment]
I just took a look at the custom dialplan that got us in this situation in the first place and it's also generating the "vmNNNN.txt" metadata files so if you're just filling the directory with wav files that might be the reason it's not working for you.

Here's the part of our custom dialplan that sticks the recorded file in to the mailbox so you can see how it's building the metadata file:

```
; Send to VM

; Generate Voicemail Metadata File
exten => s,n,Set(CUREPOCH=${EPOCH})
exten => s,n,Set(TARGETMAILBOX=8550)
exten => s,n,Set(VMNUM=${VMCOUNT(${TARGETMAILBOX})})
exten => s,n,Set(VMTXTFILE=/tmp/msg${SPRINTF(%04d,${VMNUM})}.txt)
exten => s,n,System(echo "[message]" > ${VMTXTFILE})
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=origmailbox=${TARGETMAILBOX})
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=context=macro-vm)
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=macrocontext=from-internal)
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=exten=dovm)
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=rdnis=unknown)
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=priority=2)
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=callerchan=${CHANNEL})
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=callerid=${CALLERID(all)})
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=origdate=${STRFTIME(${CUREPOCH},,%a %b %d %I:%M:%S %p %Z %Y)})
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=origtime=${CUREPOCH})
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=category=)
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=msg_id=${CUREPOCH}-00000000)
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=flag=)
exten => s,n,Set(FILE(${VMTXTFILE},,,al)=duration=2)

; Move recording and metadata to mailbox
exten => s,n,System(mv ${VMTXTFILE} /var/spool/asterisk/voicemail/default/${TARGETMAILBOX}/INBOX/)
exten => s,n,System(mv /var/lib/asterisk/sounds/${CALLERID(number)}-${TIMESTAMP}.wav /var/spool/asterisk/voicemail/default/${TARGETMAILBOX}/INBOX/msg${SPRINTF(%04d,${VMNUM})}.wav)
${SPRINTF(%04d,${VMNUM})}.wav
```

Obviously we are coloring outside the lines here so I'm not ruling out that something about that is screwing things up in ways that could never happen in a "normal" system, but I am still pretty sure that this could happen in any case where through whatever method a system ends up with a mailbox containing more than `maxmsg + 10` messages.  `maxmsg` being lowered after a mailbox was already filled up or a mailbox backup being restored on to a system with `maxmsg` set lower both seem like plausible paths.

**Comment by sharlow** [comment]
I also just noticed that my .txt metadata file generation is just hardcoding `duration` to 2 which is obviously not correct but also doesn't seem likely to be related.

**Comment by sharlow** [comment]
and I just noticed your PR that looks to fix it, neat.
