### ISSUE TITLE
[bug]: 'formats' parameter when creating channel does not work to specify the codec

### ISSUE THREAD

**Issue by fabian-borot** [asterisk/asterisk#878]
### Severity

Trivial

### Versions

18.12

### Components/Modules

ARI

### Operating Environment

ubuntu

### Frequency of Occurrence

Constant

### Issue Description

When I use the python ARI libray, and try to create a channel and pass the 'formats' parameter with only 1 codec, the INVITE that is sent contains all codecs in the 'allow' column for the pjsip endpoint.
`<--- ARI request received from: 127.0.0.1:54270 --->
Host: localhost:8088
User-Agent: python-requests/2.27.1
Accept-Encoding: gzip, deflate
Accept: application/json
Connection: keep-alive
Content-type: application/json
Content-Length: 303
Authorization: Basic cmFwaWRzb3M6cmFwaWRzb3MxMjM=
endpoint: pjsip/phone-number-1@test-provider-sbc0
app: ari-default-app-11e3461a-2651-445b-90b9-64e0dd8da146
callerId: +12053426754
timeout: 30
formats: ulaw
body:
{"variables":{"PJSIP_HEADER(add,P-Asserted-Identity)":"<sip:12053426754@myorgname.com>",
"PJSIP_HEADER(add,X-ORG-ID)":"c930ccae-3f6c-4250-8d67-73c0c8b3d03a"}
<--- Sending ARI response to 127.0.0.1:54270 --->
200 OK
Content-type: application/json
{"id":"ch_CALL0_c930ccae-3f6c-4250-8d67-73c0c8b3d03a_pjsip_phone-number-1_test-provider-sbc0",
"name":"PJSIP/test-provider-sbc0-00000058",
"state":"Down",
"caller":{"name":"","number":"+12053426754"},
"connected":{"name":"","number":"+12053426754"},
"accountcode":"","dialplan":{"context":"default","exten":"s","priority":1,"app_name":"AppDial2","app_data":"(Outgoing Line)"},"creationtime":"2024-09-10T13:39:45.095+0000","language":"en"}

    -- Called phone-number-1@test-provider-sbc0
    -- Executing [phone-number-1@midas_tests:1] NoOp("PJSIP/same-asterisk-incoming-00000059", "Receiving call 1") in new stack
<--- Sending ARI event to 127.0.0.1:53218 --->
{"type":"Dial","timestamp":"2024-09-10T13:39:45.099+0000","dialstatus":"","forward":"","dialstring":"phone-number-1@test-provider-sbc0","peer":{"id":"ch_CALL0_c930ccae-3f6c-4250-8d67-73c0c8b3d03a_pjsip_phone-number-1_test-provider-sbc0","name":"PJSIP/test-provider-sbc0-00000058","state":"Down","caller":{"name":"","number":"+12053426754"},"connected":{"name":"","number":"+12053426754"},"accountcode":"","dialplan":{"context":"default","exten":"s","priority":1,"app_name":"AppDial2","app_data":"(Outgoing Line)"},"creationtime":"2024-09-10T13:39:45.095+0000","language":"en"},"asterisk_id":"08:00:27:a3:dc:46","application":"ari-default-app-11e3461a-2651-445b-90b9-64e0dd8da146"}
    -- Executing [phone-number-1@midas_tests:2] Answer("PJSIP/same-asterisk-incoming-00000059", "") in new stack
       > 0x7f04280429d0 -- Strict RTP learning after remote address set to: 127.0.0.1:10066
       > 0x7f041c00cee0 -- Strict RTP learning after remote address set to: 127.0.0.1:10012
<--- Sending ARI event to 127.0.0.1:53218 --->
{"type":"ChannelStateChange","timestamp":"2024-09-10T13:39:45.113+0000","channel":{"id":"ch_CALL0_c930ccae-3f6c-4250-8d67-73c0c8b3d03a_pjsip_phone-number-1_test-provider-sbc0","name":"PJSIP/test-provider-sbc0-00000058","state":"Up","caller":{"name":"","number":"+12053426754"},"connected":{"name":"","number":"+12053426754"},"accountcode":"","dialplan":{"context":"default","exten":"s","priority":1,"app_name":"AppDial2","app_data":"(Outgoing Line)"},"creationtime":"2024-09-10T13:39:45.095+0000","language":"en"},"asterisk_id":"08:00:27:a3:dc:46","application":"ari-default-app-11e3461a-2651-445b-90b9-64e0dd8da146"}
    -- PJSIP/test-provider-sbc0-00000058 answered
<--- Sending ARI event to 127.0.0.1:53218 --->
{"type":"Dial","timestamp":"2024-09-10T13:39:45.113+0000","dialstatus":"ANSWER","forward":"","dialstring":"phone-number-1@test-provider-sbc0","peer":{"id":"ch_CALL0_c930ccae-3f6c-4250-8d67-73c0c8b3d03a_pjsip_phone-number-1_test-provider-sbc0","name":"PJSIP/test-provider-sbc0-00000058","state":"Up","caller":{"name":"","number":"+12053426754"},"connected":{"name":"","number":"+12053426754"},"accountcode":"","dialplan":{"context":"default","exten":"s","priority":1,"app_name":"AppDial2","app_data":"(Outgoing Line)"},"creationtime":"2024-09-10T13:39:45.095+0000","language":"en"},"asterisk_id":"08:00:27:a3:dc:46","application":"ari-default-app-11e3461a-2651-445b-90b9-64e0dd8da146"}
       > Launching Stasis(ari-default-app-11e3461a-2651-445b-90b9-64e0dd8da146) on PJSIP/test-provider-sbc0-00000058
<--- Sending ARI event to 127.0.0.1:53218 --->
{"variable":"STASISSTATUS","value":"","type":"ChannelVarset","timestamp":"2024-09-10T13:39:45.113+0000","channel":{"id":"ch_CALL0_c930ccae-3f6c-4250-8d67-73c0c8b3d03a_pjsip_phone-number-1_test-provider-sbc0","name":"PJSIP/test-provider-sbc0-00000058","state":"Up","caller":{"name":"","number":"+12053426754"},"connected":{"name":"","number":"+12053426754"},"accountcode":"","dialplan":{"context":"default","exten":"s","priority":1,"app_name":"Stasis","app_data":"ari-default-app-11e3461a-2651-445b-90b9-64e0dd8da146"},"creationtime":"2024-09-10T13:39:45.095+0000","language":"en"},"asterisk_id":"08:00:27:a3:dc:46","application":"ari-default-app-11e3461a-2651-445b-90b9-64e0dd8da146"}
<--- Sending ARI event to 127.0.0.1:53218 --->
{"type":"StasisStart","timestamp":"2024-
`

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
This is expected behavior. The option does not explicitly set the formats, it is a request. The specific behavior can be configured in PJSIP on a per-endpoint basis[1].

[1] https://docs.asterisk.org/Asterisk_21_Documentation/API_Documentation/Module_Configuration/res_pjsip/#codec_prefs_outgoing_offer
