### ISSUE TITLE
[bug]: Value CHANNEL(userfield) is lost by BRIDGE_ENTER

### ISSUE THREAD

**Issue by pjannesen** [asterisk/asterisk#882]
### Severity

Minor

### Versions

20.9.3

### Components/Modules

cel

### Operating Environment

debian container with Asterisk build from sources.

### Frequency of Occurrence

None

### Issue Description

CHANNEL(userfield) is lost by BRIDGE_ENTER. 

Following sample from cel_custom logging
```
"1726076868.487565","CHAN_START","dhg1tn01-1726076868.27","",""
"1726076869.488925","ANSWER","dhg1tn01-1726076868.27","11690910/1",""
"1726076873.676815","BRIDGE_ENTER","dhg1tn01-1726076868.27","","{""bridge_id"":""8f7477f5-e62a-4da2-88ca-fc03964095c5"",""bridge_technology"":""simple_bridge""}"
"1726076919.807386","BRIDGE_EXIT","dhg1tn01-1726076868.27","","{""bridge_id"":""8f7477f5-e62a-4da2-88ca-fc03964095c5"",""bridge_technology"":""simple_bridge""}"
"1726076919.807929","HANGUP","dhg1tn01-1726076868.27","","{""hangupcause"":16,""hangupsource"":"""",""dialstatus"":""""}"
"1726076919.807929","CHAN_END","dhg1tn01-1726076868.27",""""
```

The 4th field in CHANNEL(userfield). After the channel is bridge with a other channel the CHANNEL(userfield) value is lost.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Please provide the complete console output as well with this.

**Comment by pjannesen** [comment]
Your application controls asterisk using the AMI.
Channel "dhg1tn01-1726076868.27" was an incoming channel that was answered and put on a wait loop.
The CHANNEL(userfield) was assigned using AMI SetVar.
The seconds channel was create by a AMI Originate.
When then seconds channel was up (and after some prompts) both channels are bridge using AMI: Bridge.

**Comment by jcolp** [comment]
Please provide a way to reproduce this issue, such as strictly dialplan or a dialplan+script that someone can run. Your scenario is complicated enough that this is needed.

**Comment by pjannesen** [comment]
I have found the bug the 'userfield' is not copied in channel_do_masquerade

**Comment by pjannesen** [comment]
I have create a pull request #887
