### ISSUE TITLE
[bug]: Stir-Shaken doesn’t allow B or C attestation for unknown callerid which is allowed by ATIS-1000074.v003, §5.2.4

### ISSUE THREAD

**Issue by oza4h07** [asterisk/asterisk#921]
### Severity

Major

### Versions

20.10

### Components/Modules

stir_shaken

### Operating Environment

Debian 11

### Frequency of Occurrence

Constant

### Issue Description

When sending an outbound call from an unknown number, according ATIS-1000074.v003, §5.2.4, an ITSP should attest the call with a B level as it:

1.   he is responsible of the origination of the SIP call
2.   he has a direct authenticated relationship with the customer
3.   he has not established a verified relation with the callerid

As the number is unknown to him/her, the ITSP cannot configure in advance any corresponding TN entry.

Asterisk should allow the ITSP to define a default attestation B evel for those "unknown TNs".
Currently, as of 20.10.0-rc2, Asterisk doesn't define such default attestation level  and Asterisk sends these calls (from unrkown numbers) without any Identity header.
According some local regulations, a call without any Identity header may be dropped by any transit or termination provider.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by gtjoseph** [comment]
@oza4h07 Please test PR #987 and see if it does what you need.
