### ISSUE TITLE
[bug]: "Failed to retrieve exit status: No child processes" during handling of #exec includes

### ISSUE THREAD

**Issue by DrPyser** [asterisk/asterisk#922]
### Severity

Trivial

### Versions

21.4.1

### Components/Modules

core(config)

### Operating Environment

debian 11 bullseye
Wazo-Platform 24.13

### Frequency of Occurrence

Frequent

### Issue Description

When using `#exec` include statements in config files in order to dynamically generate configs,
invocations of the `#exec` subcommand often results in error messages in asterisk logs.
(example):
```
ERROR[2204657]: config.c:1880 handle_include_exec: #exec </usr/bin/wazo-confgen asterisk/extensions.conf>: Failed to retrieve exit status: No child processes
```

We can see this occur(in a reproducible manner) in [wazo-platform](https://wazo-platform.org/) deployments, where the `wazo-confgen` command(a python client for a python TCP server) is used to generate many of the asterisk configs from database data.

This issue does not occur on every deployments, and does not seem to occur directly after a restart of asterisk, so this seems to hint to a stateful issue. 

One hypothesis is the `level` global variable used to implement reentrancy of `ast_replace_sigchld`/`ast_unreplace_sigchld` functions for `SIGCHLD` handler management.

See also JIRA ticket on our public/community JIRA: https://wazo-dev.atlassian.net/browse/WAZO-3724 .

### Relevant log output

```shell
ERROR[2204657]: config.c:1880 handle_include_exec: #exec </usr/bin/wazo-confgen asterisk/extensions.conf>: Failed to retrieve exit status: No child processes
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by seanbright** [comment]
Reverting 8c3ebf974787ebc432ce591c072868cc1b33a227 would resolve this.

**Comment by seanbright** [comment]
> One hypothesis is the `level` global variable used to implement reentrancy of `ast_replace_sigchld`/`ast_unreplace_sigchld` functions for `SIGCHLD` handler management.

That variable is protected by a mutex (the versions in extconfig.c are not relevant):

https://github.com/asterisk/asterisk/blob/a988506a3e8dc19e08150523bc66068ed8873d0a/main/asterisk.c#L1094-L1129

**Comment by seanbright** [comment]
[Here is a diagnostic patch against 21.](https://github.com/user-attachments/files/17192093/0001-asterisk.c-Detect-unbalanced-calls-to-ast_-un-replac.patch) If you were able to test it and report your results that would help.

**Comment by seanbright** [comment]
Your analysis is generally correct. The issue is that `safe_system_level` is allowed to underflow if calls to `ast_replace_sigchild()` and `ast_unreplace_sigchild()` are not matched.

This can trivially be reproduced by making an AGI call to an invalid script:

```text
exten = _X.,1,AGI(doesnotexist.py)
```

And then issuing a `dialplan reload` where an `#exec` is present.

**Comment by DrPyser** [comment]
> Your analysis is generally correct. The issue is that `safe_system_level` is allowed to underflow if calls to `ast_replace_sigchild()` and `ast_unreplace_sigchild()` are not matched.
> 
> This can trivially be reproduced by making an AGI call to an invalid script (although it would occur with a successful FastAGI call too):
> 
> ```
> exten = _X.,1,AGI(doesnotexist.py)
> ```
> 
> And then issuing a `dialplan reload` where an `#exec` is present.
> 
> The patch I provided above _should_ prevent this, and I am inclined to propose essentially the same fix but without the log message. Thank you for the report and doing most of the legwork.

Thank you for the quick and efficient response and the fix, didn't expect it to be resolved that quickly!
Many of our partners will be pleased to see less red in their logs.

Take care Sean!
