### ISSUE TITLE
[bug]: unattendeded port listening

### ISSUE THREAD

**Issue by APachLv** [asterisk/asterisk#943]
### Severity

Trivial

### Versions

20..9.3

### Components/Modules

Network

### Operating Environment

Debian 12

### Frequency of Occurrence

None

### Issue Description

Dear Team.

Freshly compiled & installed Asterisk.

Port configuretion is, port 5060 tcp + udp & 5061 tls.

Agter restart Asterisl pick configured ports + another unattended.
And every restart, the port is different.

Could someone point me to how to configure or disable this radom port binding?

Scr. attached.

Thanks.

-   -   -   -   -   -  -  -  -

![2024-10-12_15-59-12](https://github.com/user-attachments/assets/6afceca7-a0b6-480e-ae96-5210b29eb81c)
![2024-10-12_15-29-18](https://github.com/user-attachments/assets/b0bfba6f-1aa5-4aad-9b1c-32ca6d0c9c77)
![2024-10-12_15-27-51](https://github.com/user-attachments/assets/58f95ea0-74f3-4069-8b6f-4027c7cd50d4)
![2024-10-12_15-24-21](https://github.com/user-attachments/assets/5af303a9-7329-4778-bfeb-8d174f223bb0)

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
We appreciate the difficulties you are facing, however this does not appear to be a bug report and your request or comments would be better served in a different forum.

The Asterisk community provides support over IRC, mailing lists, and forums as described at http://asterisk.org/community. The Asterisk issue tracker is used specifically to track issues concerning bugs and documentation errors.

In this case please start a discussion on the forum[1].

Thanks!

[1] https://community.asterisk.org/
