### ISSUE TITLE
[bug]: invite with pjsip headers too long generates errors

### ISSUE THREAD

**Issue by pablodz** [asterisk/asterisk#956]
### Severity

Trivial

### Versions

18+

### Components/Modules

pjsip

### Operating Environment

Ubuntu

### Frequency of Occurrence

Constant

### Issue Description

If an incoming INVITE message in PJSIP contains more than 4000 bytes of headers, it results in UDP fragmentation. Asterisk, when handling these fragmented packets, only processes the first fragment and fails to properly handle or reassemble the subsequent fragments. This causes Asterisk to generate errors and drop the INVITE, as it cannot interpret the full message

### Relevant log output

```shell
WARNING[50]: pjproject: <?>:                sip_transport.c Dropping 4000 bytes packet from UDP XX.XXX.XXX.XX:11000 : PJSIP syntax error exception when parsing 'X-' header on line 54 col 3
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by gtjoseph** [comment]
@pablodz Can you provide a pcap that demonstrates the issue?  I think it's actually pjproject's fixed 4000 byte buffer that's the issue rather than UDP fragmentation.

**Comment by gtjoseph** [comment]
@pablodz Actually, can you confirm the exact asterisk version you're using and whether you're building it yourself or installing from packages?  If you're building from source with the bundled pjproject, we override the default PJSIP_MAX_PKT_LEN of 4000 to 65535.

**Comment by pablodz** [comment]
> @pablodz Can you provide a pcap that demonstrates the issue? I think it's actually pjproject's fixed 4000 byte buffer that's the issue rather than UDP fragmentation.

I’ve noticed log entries for each failed INVITE. Here’s the PCAP file: [PCAP File](https://gist.github.com/pablodz/616c74fca87408e6bf6a9d184d9bd394). I’ve modified it to remove any sensitive information.

On sngrep looks like INVITE fails, so, another one is sent from host

> @pablodz Actually, can you confirm the exact asterisk version you're using and whether you're building it yourself or installing from packages? If you're building from source with the bundled pjproject, we override the default PJSIP_MAX_PKT_LEN of 4000 to 65535.

For debugging, I'm working with a dockerized version of Asterisk 20.9.3 (alpine) using the docker mlan/asterisk:xtra image. I've also tried a CentOS-based installation with Asterisk 18.20.0 compiled from source, but I'm encountering the same issue; the same log entries appear with the same packet length.

**Comment by gtjoseph** [comment]
@pablodz When you compiled from source, are you using the bundled version of pjproject?
Can you confirm that PJSIP_MAX_PKT_LEN is set to 65535 in BOTH
./third-party/pjproject/patches/config_site.h and in
./third-party/pjproject/source/pjlib/include/pj/config_site.h
?

**Comment by gtjoseph** [comment]
I should also probably mention that you should be using a TCP transport instead of UDP if you expect packets of this size.

**Comment by pablodz** [comment]
Yes, it was PJSIP_MAX_PKT_LEN, looks like was miss configured during building from scratch, thanks
