### ISSUE TITLE
[bug]: Could not create dialog with endpoint $SIPSERVER$. Invalid URI (PJSIP_EINVALIDURI) for incoming calls via IPv6 if contact_user is set in endpoint configuration

### ISSUE THREAD

**Issue by nvsystems** [asterisk/asterisk#985]
### Severity

Major

### Versions

20.5.0, 21.5.0

### Components/Modules

res_pjsip.c

### Operating Environment

Asterisk 21.5.0 with FreePBX 17 on Debian 12.7

### Frequency of Occurrence

Constant

### Issue Description

Incoming calls via IPv6 transport do not work since Asterisk 20.5.0 (it was working with 20.4.0) if "contact_user" is set in the type=endpoint section. When the call is made, the message:
`Could not create dialog with endpoint $SIPSERVER$. Invalid URI (PJSIP_EINVALIDURI)`
appears on the asterisk console and the call fails - outgoing calls work fine.

In the pjsip history (logs attached) it can be seen that the provider sends:
INVITE sip:08171XXXXXX@[2001:a61:2a03:1:201:2eff:fea9:f467]:5060;line=umdhlhm SIP/2.0
and asterisk responds with
SIP/2.0 500 Server Internal Error

Full configuration is attached as text files, but it's nothing out of the ordinary. I'm testing with SIP provider sipgate.de but this also happens with easybell.de - a completely different company and I've found a forum discussion with people from italy who encountered this problem as well (they are using voip.iliad.it).

My configuration for the provider was initially done with FreePBX which adds "contact_user=" to both the type=registration and type=endpoint configuration directives if it is configured in the GUI. I did further testing and everything is fine with contact_user=08171XXXXXX in the type=registration section - calls are then routed to this number, but if contact_user=08171XXXXXX (or contact_user=s) appears in the type=endpoint section, the above PJSIP_EINVALIDURI message appears and the incoming call fails. But ONLY if transport is IPv6! Same extension config with just the transport changed to IPv4 works fine for incoming calls!

I cannot see any difference in the INVITE sip message (see attached bug_contact_user_a_broken_08171XXXXXX.txt vs. bug_contact_user_b_working_08171XXXXXX.txt) yet one time asterisk responds with 500 Server Internal Error and the other time with 100 Trying.

Something changed between 20.4.0 and 20.5.0 as far as I know. I'm not the expert here but this does not seem intentional? According to pjsip.conf.sample: contact_user= ; On outgoing requests, force the user portion of the Contact header to this value (default: "")

I don't fully understand the implications on what setting contact_user in the type=endpoint is supposed to accomplish but
a) I don't think it makes sense that it breaks on IPv6 connectivity but not on IPv4, also the description in pjsip.conf.sample does not sound like it should break incoming calls
b) From the release notes I would guess this new bug was created by fixing https://github.com/asterisk/asterisk/issues/226 
c) this is as far as I can tell the commit that broke things on IPv6: https://github.com/asterisk/asterisk/pull/232/commits/dce4c80abe18fbd499b0d2748a729b320a1f39bd

I would very much appreciate if someone can fix this. I have not tried it on Asterisk 22, but from what I can see in the master branch for asterisk/res/res_pjsip.c it does not look like any changes have been made to the code so it's highly likely to be also the same in Asterisk 22.
[bug_contact_user_a_broken_08171XXXXXX.txt](https://github.com/user-attachments/files/17668340/bug_contact_user_a_broken_08171XXXXXX.txt)
[bug_contact_user_b_working_08171XXXXXX.txt](https://github.com/user-attachments/files/17668338/bug_contact_user_b_working_08171XXXXXX.txt)
[bug_contact_user_c_pjsip_configuration.txt](https://github.com/user-attachments/files/17668339/bug_contact_user_c_pjsip_configuration.txt)

### Relevant log output

```shell
Could not create dialog with endpoint $SIPSERVER$. Invalid URI (PJSIP_EINVALIDURI)

abbreviated pjsip log, see txt attachments for full logs

<--- History Entry 0 Received from [2001:ab7::2]:5060 at 1731004228 --->
INVITE sip:08171XXXXXX@[2001:a61:2a03:1:201:2eff:fea9:f467]:5060;line=umdhlhm SIP/2.0
Record-Route: <sip:[2001:ab7::2];lr;r2=on;ftag=as2f8394dc>
Record-Route: <sip:217.10.78.108;lr;r2=on;ftag=as2f8394dc>
Record-Route: <sip:172.20.40.6;lr;did=4eb.1772>
Record-Route: <sip:217.10.68.137;lr>
Via: SIP/2.0/UDP [2001:ab7::2];received=2001:ab7::2;branch=z9hG4bK6bac.63fc8b0b2a6c06d2f6581c95c4205c3c.0
Via: SIP/2.0/UDP 172.20.40.6;branch=z9hG4bK6bac.65a5e74b2ff3d902a7de51c0acf05392.0
Via: SIP/2.0/UDP 217.10.68.137;branch=z9hG4bK6bac.fde23ee28b993c8cf6b1baf1cf5976b6.0
Via: SIP/2.0/UDP 212.9.44.152:5060;branch=z9hG4bK25bbf2db
Max-Forwards: 67
From: "08171XXXXXX" <sip:0179210XXXX@sipgate.de>;tag=as2f8394dc
To: <sip:1774652e0@sipgate.de>
Contact: <sip:0179210XXXX@212.9.44.152:5060>
Call-ID: 1271f23073d7bb4d1e708b674d169710@sipgate.de
CSeq: 103 INVITE

<--- History Entry 1 Sent to [2001:ab7::2]:5060 at 1731004228 --->
SIP/2.0 500 Server Internal Error
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by nvsystems** [comment]
I have no experience writing C code so please don't expect a pull request from me. But I've looked at the code and I'm pretty sure I figured out what went wrong here. The code that generates the URI as currently in master:asterisk/res/res_pjsip.c is as follows:

`contact.slen = pj_ansi_snprintf(contact.ptr, PJSIP_MAX_URL_SIZE,
			"<%s:%s%s%s%.*s%s:%d%s%s>",
			uas_use_sips_contact(rdata) ? "sips" : "sip",
			(type & PJSIP_TRANSPORT_IPV6) ? "[" : "",
			S_OR(endpoint->contact_user, ""),
                        (!ast_strlen_zero(endpoint->contact_user)) ? "@" : "",
			(int)transport->local_name.host.slen,
			transport->local_name.host.ptr,
			(type & PJSIP_TRANSPORT_IPV6) ? "]" : "",
			transport->local_name.port,
			(type != PJSIP_TRANSPORT_UDP && type != PJSIP_TRANSPORT_UDP6) ? ";transport=" : "",
			(type != PJSIP_TRANSPORT_UDP && type != PJSIP_TRANSPORT_UDP6) ? pjsip_transport_get_type_name(type) : "");`

This generates the sip URI in the wrong order if the transport is IPv6! It should generate a sip URI that looks something like:
`<sip:contact_user@[v6adr]:port>`

but the order of the lines is wrong! Probably the line "(type & PJSIP_TRANSPORT_IPV6) ? "[" : ""," needs to move down two lines to encompass the IP address, because currently the code generates an address something like this:
`<sip:[contact_user@v6adr]:port>`

**Comment by seanbright** [comment]
> This generates the sip URI in the wrong order if the transport is IPv6!

You are correct. PR #986 opened.
