### ISSUE TITLE
[bug]: Crash when setting a global variable with invalid UTF8 characters

### ISSUE THREAD

**Issue by lamespotting** [asterisk/asterisk#999]
### Severity

Minor

### Versions

20,21,22,master

### Components/Modules

core

### Operating Environment

Linux

### Frequency of Occurrence

Occasional

### Issue Description

When setting a global variable with invalid UTF8 characters, a warning log will trigger a crash as it's trying to reference chan->name. When we are setting global variables, chan will always be NULL.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by seanbright** [comment]
Example code?
